photutils/aperture_core.py
=> Decorating aperture_photometry() with support_nddata

.appveyor_windows_sdk.cmd, .install-miniconda.ps1, appveyor.yml, photutils/tests/test_morphology.py
=> Enable AppVeyor Windows CI testing

docs/photutils/aperture.rst
Uses the Aperture `area()` method (also see #223).
=> Update local background subtraction docs

README.rst
I think we should add the badge, though I'm not sure where to place it on the page.
=> Adding astropy badge to gh

appveyor.yml
=> Update Appveyor to use astropy 1.0.1

CHANGES.rst, photutils/aperture_core.py, photutils/tests/test_aperture_photometry.py
Fixes issue https://github.com/astropy/photutils/issues/267.
=> Fix aperture photometry masking to include nans and infs

.travis.yml, photutils/tests/test_aperture_photometry.py
Changing the way of the astropy install should act as a workaround #274, while we track down a fix for that. 
I've changed the aperture tests that triggered the failures leading to the discovery this issue.
=> Change travis install of astropy from conda to pip

docs/photutils/detection.rst, docs/photutils/getting_started.rst
These are flagged remote, thus travis didn't notice them.
=> Fixing failing doctests (due to changes in the table print output)

CHANGES.rst, docs/photutils/detection.rst, docs/photutils/segmentation.rst, photutils/utils/__init__.py, photutils/utils/colormaps.py, photutils/utils/tests/test_colormaps.py
This is extremely useful for plotting segmentation images.
More segmentation additions coming soon....
=> Add a colormap comprised of random colors

photutils/utils/interpolation.py, photutils/utils/tests/test_interpolation.py
This is useful for estimating 2D backgrounds.  I plan to add this feature to the `Background` class.
=> Add Inverse Distance Weighting Interpolator

CHANGES.rst, docs/photutils/detection.rst, photutils/detection/__init__.py, photutils/detection/core.py, photutils/detection/deblend.py, photutils/detection/tests/test_deblend.py, photutils/segmentation.py
This deblender uses a combination of multi-thresholding and watershed segmentation.
=> Add an experimental source deblender

photutils/utils/interpolation.py
=> generalized interpolate_masked_data to n dimensions

photutils/aperture_core.py, photutils/aperture_funcs.py
At the moment the methods do_photometry & co. accept only 2d input data.
This is problematic when doing aperture photometry on a data cube (e.g. create aperture spectra).
The fastest method is to get the pixel weights (fractions) directly.
An alternative implementation would see heavier edits, with an added ``axes`` keyword which specifies which axes will be suppressed by ``do_photometry``.
=> Retrieve the fractions associated with a given aperture/photometry

docs/photutils/getting_started.rst
Quoting @eteq: "This is about as trivial as a PR gets".
=> DOC: fixed typo in getting started page

photutils/detection/deblend.py
=> update slices when deblending

CHANGES.rst, photutils/utils/wcs_helpers.py
Fixes #346.  Thanks, @bsipocz!
=> Fix incorrect pixel origin in pixel_to_icrs_coords

docs/photutils/install.rst
This PR adds installation instructions using `conda`, separates the stable and development versions in different sections, and generally cleans up the instructions.
=> Update and improve installation docs

photutils/tests/test_aperture_photometry.py
… to be consistent with the rest of the test files [skip ci]
=> Importing pytest from astropy

docs/photutils/detection.rst
Fixes issue #387. cc @larrybradley
=> [DOC]: clarify find_peaks documentation

docs/photutils/detection.rst
While reviewing the doc build after #379, it occurred to me the minor clarification here might be helpful.  @mirca, look good to you?
=> add mention of table in detection docs

CHANGES.rst, photutils/background/core.py, photutils/background/tests/test_core.py, photutils/extern/biweight_stats.py, photutils/extern/stats.py
This will also be used in an object-oriented interface for the 2D background classes.
=> Add axis keyword to Background classes

.rtd-environment.yml, docs/rtd-pip-requirements, readthedocs.yml
This may be enough to fix the current rtd fails. If not I'll add a mpl version requirement, too.
=> Changing rtd configs to use conda

docs/photutils/getting_started.rst, photutils/detection/findstars.py, photutils/psf/groupstars.py
In addition to fixing #393, I also cleaned up several things in this PR, mainly in the star finder docs.
=> Fixes PDF docs build

docs/photutils/psf_matching.rst, photutils/psf/matching/windows.py
(e.g. `origin=lower` and `cmap='viridis'`)
=> Some minor plot fixes for PSF matching docs

photutils/psf/photometry.py
This should fix the currently broken RTD build.
=> Adding one liner to the docstring of __call__ to fix the rtd latex build

docs/photutils/psf.rst
Hi all,
I'm writing narrative docs for the PSF photometry module.
Is there anything else that you would like to see? @hamogu @bsipocz @eteq @larrybradley 
PS: the doctests depends on #385
=> [DOC]: Narrative docs for PSF Photometry

photutils/psf/funcs.py, photutils/psf/groupstars.py, photutils/psf/models.py, photutils/psf/photometry.py, photutils/psf/sandbox.py, photutils/psf/tests/test_groupstars.py, photutils/psf/tests/test_misc.py, photutils/psf/tests/test_photometry.py, photutils/psf/tests/test_prf_adapter.py, photutils/psf/tests/test_psf_photometry.py
PEP8 (mostly) and some minor wording changes.
=> Minor fixes in PSF subpackage

photutils/psf/funcs.py
=> remove prepare_psf_model from psf.funcs

docs/photutils/aperture.rst, docs/photutils/background.rst, docs/photutils/detection.rst, docs/photutils/getting_started.rst, docs/photutils/psf_matching.rst, docs/photutils/segmentation.rst
All instances of `pylab` are now `pyplot`.
=> Replace pylab with pyplot

photutils/segmentation.py, photutils/utils/__init__.py, photutils/utils/errors.py, photutils/utils/prepare_data.py, photutils/utils/tests/test_errors.py
This PR fixes some bugs with units in `SourceProperties` and removes some outdated functions in `prepare_data`.
=> Fix some bugs with units

docs/photutils/psf.rst
Minor language fixes in the new PSF docs attached.
=> Minor language fixes in PSF docs

docs/photutils/aperture.rst, photutils/aperture/core.py
Updated for the changes in #453 and #454.  Also adds docs for aperture masks.
=> Update aperture narrative docs

photutils/psf/tests/test_imagemodel.py
This closes #461 by implementing the regression test suggested there.  I checked that this does indeed fail if I revert the fix in #460.
=> add regression test for #460

docs/photutils/datasets.rst, photutils/datasets/load.py
=> Update datasets module to use data.astropy.org

photutils/geometry/circular_overlap.pyx, photutils/geometry/core.pxd, photutils/geometry/core.pyx
This bug affects only 32-bit machines.
=> Fix aperture photometry computation for 32-bit machines

CHANGES.rst, photutils/psf/photometry.py, photutils/psf/tests/test_photometry.py
Fixes #482
cc @eteq, @bsipocz, @hamogu, @stefanocovino
=> Fix bug which modified user's input table when doing forced photometry

photutils/aperture/bounding_box.py, photutils/aperture/tests/test_bounding_box.py
Also adds `BoundingBox` tests.
=> Raise exception if BoundingBox inputs are not integers

CHANGES.rst, photutils/background/background_2d.py, photutils/background/tests/test_background_2d.py
=> Fix Background2D for case when padding is zero along only one axis

docs/conf.py
=> Remove html_static_path from docs/conf.py

.travis.yml, CHANGES.rst, docs/photutils/install.rst, photutils/aperture/tests/test_aperture_photometry.py
as the latest stable is 1.12
@larrybradley - What do you think about dropping np1.7 at some point?
=> Adding np 1.11 to the travis matrix

.gitignore, .travis.yml, appveyor.yml, photutils/background/core.py, photutils/psf/models.py, photutils/psf/tests/test_imagemodel.py, photutils/segmentation/properties.py, photutils/utils/errors.py, setup.cfg, setup.py
Includes adding a PEP8 travis test (allowed failure).
=> Updates to package template files

CHANGES.rst, docs/photutils/segmentation.rst, photutils/segmentation/core.py
This is a convenience method to a generate random matplotlib colormap when plotting a segmentation image.
=> Add cmap method for SegmentationImage

.travis.yml, docs/photutils/grouping.rst
This makes it easier to find `DBSCANGroup`.  I also added the class inheritance diagram to the grouping narrative docs.
=> Add DBSCANGroup to grouping docs

setup.cfg
=> Change section name to pycodestyle

CHANGES.rst, photutils/psf/photometry.py, photutils/psf/tests/test_photometry.py
In summary I'm getting the uncertainties reported by ``self.fitter`` and putting them in the final result table.
=> Retrieve uncertainties of fitted parameters from fitter

photutils/psf/photometry.py, photutils/psf/tests/test_photometry.py
Small clean up towards v0.4 release.
=> Clean up psf sub-package in preparation for v0.4

.run_docker_tests.sh
Addendum to https://github.com/astropy/photutils/pull/570.
=> Update .run_docker_test.sh script

CHANGES.rst, docs/photutils/background.rst, photutils/background/background_2d.py, photutils/background/core.py, photutils/background/tests/test_core.py, photutils/psf/photometry.py, photutils/psf/tests/test_photometry.py
This PR removes the `SigmaClip` class, replacing it with the one I moved upstream in `astropy.stats`.
=> Use astropy SigmaClip class

.travis.yml, setup.cfg, setup.py
=> Minor setup updates

photutils/psf/photometry.py
=> rm extra accent char

docs/psf.rst
=> rm extra 'you'

ah_bootstrap.py
~NO NOT MERGE YET~ 2.0.4 is released, so this can be merged now.
=> Updating helpers to v2.0.4

CHANGES.rst, photutils/isophote/isophote.py
=> Correct units for isophote sarea in documentation

CHANGES.rst, photutils/segmentation/detect.py, photutils/segmentation/tests/test_detect.py
Fixes #661.
Thanks to @ysBach for reporting this.
=> Fix issue where detect_sources could return sources with a size < npixels

CHANGES.rst, photutils/detection/core.py, photutils/detection/tests/test_core.py
Fixes #667.
Thanks to @abeelen for reporting this.
=> find_peaks:  return an empty Table and issue a warning when no peaks are found

CHANGES.rst, photutils/aperture/ellipse.py, photutils/aperture/rectangle.py
=> Add default theta values for elliptical and rectangular apertures

CHANGES.rst, photutils/detection/findstars.py
=> Remove deprecation of exclude_border in star finders

photutils/detection/core.py, photutils/psf/photometry.py, photutils/segmentation/properties.py, photutils/segmentation/tests/test_properties.py
Removes old deprecations and cleans up some tests.  Code deprecated in `v0.5` won't be removed until `v0.7`.
=> Remove old deprecated code

CHANGES.rst, photutils/segmentation/properties.py, photutils/segmentation/tests/test_properties.py
Thanks to @sosey for reporting this issue.
=> Fix computation of sky bounding box values in SourceCatalog

docs/detection.rst
Thanks to @zabop for reporting (via email) the missing import.
=> Fix typos in detection docs

docs/aperture.rst
This PR provides a step-by-step example in the aperture docs showing how the user can perform custom local background subtraction in annulus apertures.  This example uses the sigma-clipped median in circular apertures as the local background value.
=> Add docs for custom local background estimation

photutils/detection/findstars.py
=> Note that an empty table is returned if no sources are found

.travis.yml
~Don't yet merge, it's opened for testing and needs to be updated to point to the actual release when it's released.~
This should be merged now when CI is green.
=> Updating astropy_helpers to v3.1

photutils/psf/models.py
This is minor fix in `GriddedPSFModel` to allow it to work with the PSF-fitting classes.
=> Minor GriddedPSFModel fix

photutils/aperture/ellipse.py
Fixes #839.  Thanks to @mdcleir for reporting this!
=> Fix SkyEllipticalAnnulus docstring

photutils/utils/errors.py
The PR improves the `calc_total_error` docstring describing the error calculation.
=> Improve calc_total_error docstring

CHANGES.rst, photutils/aperture/core.py, photutils/aperture/tests/test_aperture_photometry.py
This PR improves the performance of aperture photometry, especially when using `errors` and `Quantity` inputs with many aperture positions (factors of 10-20x speed up).
=> Improve aperture photometry performance

CHANGES.rst, photutils/datasets/make.py, photutils/datasets/tests/test_make.py
This will also be useful for testing implementation of the astropy unified WCS APE (PR in work).
=> Add function to make example gwcs object

.travis.yml, photutils/__init__.py, setup.cfg
...from `numpy 1.11` to `numpy 1.13`.
=> Bump minimum required numpy version

photutils/isophote/ellipse.py, photutils/psf/epsf.py
Removed a couple unnecessary assignments.
=> Misc cleanup

README.rst
This PR makes the badges more uniform.  It also adds a new badge for LGTM code grade.
=> Update badges on README

photutils/isophote/ellipse.py, photutils/isophote/tests/test_ellipse.py
This fixes the problem reported in issue #911
=> Fix #911: linear mode not working

.travis.yml, photutils/psf/models.py
First of all, there were tons of broken API links, not sure how those passed the docs build test.
=> Some fix for psf modeling

photutils/psf/epsf.py
Minor pull request to fix memory issues with `EPSFBuilder`, removing variables which save snapshots of various things in each loop, which increased in usage as a result of refactoring to the ePSF framework in #817. Other ancillary and unused variables were removed at the same time.
I wasn't 100% sure what 'type' the changelog should be under so I just put the change in the 'other' section for now, but feel free to move it (or ask me to move it) if it's better suited to another changelog section.
cc @larrybradley
=> Removable of unused and memory intense ePSF iteration save states

.pep8speaks.yml
=> TST: pep8speak to use flake8

setup.cfg
In case we'll have a new release at some point to 0.7.x
to close #964
=> Be more specific about the astropy version

ah_bootstrap.py
The prime reason for this PR is to test the new helpers release.
=> Updating astropy helpers to v3.2.2

.travis.yml
1.15 is not 4.0 compatible, thus the failure.
=> Use older astropy with older numpy

docs/conf.py, docs/contributing.rst, docs/detection.rst, docs/epsf.rst, docs/grouping.rst, docs/install.rst, docs/isophote.rst, docs/isophote_faq.rst, docs/psf.rst, docs/psf_matching.rst, photutils/detection/findstars.py, photutils/isophote/ellipse.py, photutils/isophote/fitter.py, photutils/morphology/non_parametric.py, photutils/psf/epsf.py, photutils/psf/groupstars.py, photutils/psf/photometry.py, photutils/segmentation/properties.py
Based on running `linkcheck`.  These are mostly due to the new ADS server.
=> Update URLs in docs

setup.py
xref https://github.com/astropy/astropy/pull/10449
=> Move imports in setup.py

photutils/conftest.py
=> Remove extraneous line in conftest

CHANGES.rst, photutils/segmentation/properties.py, photutils/segmentation/tests/test_properties.py
This PR adds Kron radius, Kron flux (and flux error), and Kron aperture to `SourceProperties`.
Closes #194.
=> Add Kron radius and flux

docs/psf.rst
Fix #985
For when you think it can come off. 😉
=> MNT: Remove PSF experimental warning

CHANGES.rst, photutils/background/core.py, photutils/segmentation/properties.py, photutils/segmentation/tests/test_properties.py
Also adds a `local_background_aperture` attribute to return the `RectangularAnnulus` aperture.
=> Add local background estimator to SourceProperties

docs/epsf.rst
Due to recent changes to the random number generator.
=> Fix epsf doctest

docs/background.rst, docs/detection.rst, docs/epsf.rst, docs/morphology.rst, docs/psf.rst, docs/segmentation.rst
This PR replaces links to internal docs with references.
=> Update doc references

CHANGES.rst, photutils/psf/models.py, photutils/psf/tests/test_epsf.py, photutils/psf/tests/test_models.py
@olebole Can you please check if this fixes your issues in #1085?
=> Fix checks on oversampling

photutils/CITATION.rst
=> Replace unicode characters in citation.rst

.travis.yml
~!I'm going to replace this with a Windows test in GitHub Actions.~
This installs windows in CI with choco for now....  GitHub Actions coming very soon.
=> Remove broken windows CI test

docs/conf.py, photutils/__init__.py, photutils/aperture/attributes.py, photutils/aperture/core.py, photutils/aperture/photometry.py, photutils/datasets/load.py, photutils/datasets/make.py, photutils/detection/tests/test_findstars.py, photutils/isophote/geometry.py, photutils/isophote/tests/test_regression.py, photutils/psf/epsf.py, photutils/psf/epsf_stars.py, photutils/psf/groupstars.py, photutils/psf/photometry.py, photutils/psf/sandbox.py, photutils/psf/utils.py, photutils/segmentation/core.py, photutils/segmentation/deblend.py, photutils/segmentation/detect.py, photutils/segmentation/properties.py, photutils/segmentation/tests/test_core.py, photutils/segmentation/tests/test_properties.py, photutils/utils/_misc.py, photutils/utils/check_random_state.py
I used `flynt`, followed by additional manual changes.
=> Update code to use f-strings

README.rst
From travis to GitHub actions.
=> Update CI badge in README

.github/workflows/ci_tests.yml, .github/workflows/cron_tests.yml
and some cleanup.  Tested here:  https://github.com/larrybradley/photutils/actions/runs/342903650
=> Remove name section from GitHub Actions workflow

.github/workflows/ci_tests.yml, CHANGES.rst, docs/install.rst, setup.cfg, tox.ini
To stay in sync with the astropy 4.2 release.
=> Drop support for python 3.6

.github/workflows/ci_tests.yml, .github/workflows/cron_tests.yml
Some minor improvements to the GitHub actions workflows.
=> Update actions workflows

docs/install.rst
The astropy conda channel will be retired soon:  https://github.com/astropy/conda-channel-astropy/issues/187
=> DOC: Replace astropy channel with conda-forge channel

CHANGES.rst, photutils/isophote/ellipse.py, photutils/isophote/fitter.py
Bug was reported by a user (issue #1128)
=> Fix bug with zero length samples 

LICENSE.rst
Update license year.
But more importantly, to see if `[ci skip]` really works on Actions.
=> DOC: Update license year 

photutils/__init__.py
Removes some unnecessary items in the package top-level namespace.
=> Clean up top-level namespace

docs/psf.rst
The site and page no longer exists
=> Remove outdated link

CHANGES.rst, photutils/morphology/core.py, photutils/morphology/tests/test_core.py
=> Fix scalar background input in data_properties

photutils/aperture/bounding_box.py, photutils/aperture/circle.py, photutils/aperture/core.py, photutils/aperture/ellipse.py, photutils/aperture/mask.py, photutils/aperture/rectangle.py, photutils/background/background_2d.py, photutils/background/core.py, photutils/centroids/core.py, photutils/datasets/load.py, photutils/detection/_utils.py, photutils/isophote/ellipse.py, photutils/isophote/fitter.py, photutils/isophote/geometry.py, photutils/isophote/integrator.py, photutils/isophote/isophote.py, photutils/isophote/model.py, photutils/isophote/tests/make_test_data.py, photutils/psf/epsf.py, photutils/psf/epsf_stars.py, photutils/psf/groupstars.py, photutils/psf/models.py, photutils/psf/photometry.py, photutils/psf/sandbox.py, photutils/psf/utils.py, photutils/segmentation/core.py, photutils/segmentation/detect.py
I used the nice tool https://github.com/carreau/velin for the initial checking of formatting issues.
=> Fix docstring formatting

docs/install.rst
`linkcheck` test started failing.
=> Update conda URL

docs/aperture.rst, docs/background.rst, docs/centroids.rst, docs/datasets.rst, docs/detection.rst, docs/epsf.rst, docs/getting_started.rst, docs/grouping.rst, docs/isophote.rst, docs/psf.rst, docs/psf_matching.rst, docs/segmentation.rst
Fixes example plots in the narrative docs.
=> MNT: Fix PEP8 issues in documentation examples

CHANGES.rst, photutils/background/_utils.py, photutils/background/core.py, photutils/background/interpolators.py, photutils/background/tests/test_core.py
This PR enables all background classes to work with `Quantity` inputs.
=> Update all background classes to work with Quantity inputs

photutils/detection/_utils.py, photutils/detection/daofinder.py, photutils/detection/findstars.py, photutils/detection/irafstarfinder.py, photutils/detection/starfinder.py, photutils/detection/tests/test_daofinder.py, photutils/detection/tests/test_irafstarfinder.py
This PR refactors the implementation details of `DAOStarFinder` and `IRAFStarFinder` to allow the addition of new features (prompted by astropy/photutils#1231).  There are no user-facing public API changes (inputs or outputs) and the results are identical to previous versions.
=> Refactor DAOStarFinder and IRAFStarFinder

docs/centroids.rst, photutils/segmentation/detect.py
This PR updates the `detect_sources` docstring example and addd `centroid_quadratic` to the examples in the centroid narrative docs.
=> Documentation updates

photutils/segmentation/deblend.py
This pull request addresses issue #1266. 
Closes #1266.
=> To fix the documentation of deblend_sources function

CHANGES.rst, photutils/segmentation/detect.py, photutils/segmentation/tests/test_detect.py
`astropy.convolution.convolve` allows masking pixels during convolution.
=> Use astropy convolve in detect_sources

CHANGES.rst, docs/aperture.rst, photutils/aperture/__init__.py, photutils/aperture/circle.py, photutils/aperture/core.py, photutils/aperture/ellipse.py, photutils/aperture/mask.py, photutils/aperture/photometry.py, photutils/aperture/rectangle.py, photutils/aperture/stats.py, photutils/aperture/tests/test_stats.py, photutils/segmentation/catalog.py, photutils/utils/_quantity_helpers.py, photutils/utils/_wcs_helpers.py, photutils/utils/tests/test_misc.py, photutils/utils/tests/test_quantity_helpers.py
This PR adds an `ApertureStats` class for computing statistics of unmasked pixels within an aperture.
=> Add ApertureStats class

CHANGES.rst, photutils/aperture/mask.py, photutils/segmentation/catalog.py, photutils/segmentation/core.py, photutils/segmentation/deblend.py
This PR makes several performance improvements to `SegmentationImage` and `SourceCatalog`, especially for large images.  It also adds a ``dtype`` keyword to the ``ApertureMask`` ``to_image`` method.
=> Segmentation performance improvements

CHANGES.rst, docs/segmentation.rst, photutils/segmentation/catalog.py, photutils/segmentation/tests/test_catalog.py
This PR also makes some improvements to the Kron-related docstrings.
=> Set default kron_apers parameter in plot_kron_apertures method

photutils/segmentation/core.py, photutils/segmentation/detect.py
This improves performance, especially with large segmentation images.
=> Initialize SegmentationImage in detect_sources with labels and slices

photutils/aperture/tests/test_photometry.py, photutils/background/tests/test_background_2d.py, photutils/detection/tests/test_peakfinder.py, photutils/psf/tests/test_epsf.py, photutils/psf/tests/test_photometry.py, photutils/segmentation/tests/test_core.py, photutils/segmentation/tests/test_finder.py, photutils/utils/errors.py, photutils/utils/tests/test_errors.py
This includes adding the `match` keyword string.
=> Update tests with expected warnings

docs/dev/releasing.rst
This PR updates the release documentation using the new automated workflow for building and publishing the source distribution and wheels.
=> Update the release documentation

.github/workflows/ci_tests.yml, .github/workflows/cron_tests.yml
This PR updates to the newest setup-python Action.
=> Update setup-python action to v4

CHANGES.rst, photutils/utils/__init__.py, photutils/utils/depths.py, photutils/utils/tests/test_depths.py
This PR adds a `ImageDepth` class for computing the limiting fluxes and magnitudes of an image.
=> Add class to compute image limiting depths

CHANGES.rst, photutils/psf/photometry.py
This PR adds an option to use a progressbar when doing PSF photometry.
=> Progressbar in PSF photometry

photutils/aperture/tests/test_stats.py, photutils/segmentation/catalog.py, photutils/segmentation/tests/test_catalog.py
There are no user-facing changes.
=> Some refactoring of SourceCatalog

CHANGES.rst, photutils/segmentation/catalog.py
=> Add cutout_centroid_win to SourceCatalog

.circleci/config.yml, .github/workflows/ci_tests.yml, .github/workflows/cron_tests.yml
=> Pin tox<4 in CI

docs/psf.rst
`subtract_psf` needs to be updated to include the `sigma` parameter of `IntegratedGaussianPRF`.
=> Update psf example image

.circleci/config.yml, .github/workflows/ci_tests.yml, .github/workflows/cron_tests.yml, tox.ini
While I was at it for astroquery it was an easy fix for photutils, too.
=> MAINT: fix tox v4 compatibility

CHANGES.rst, docs/profiles.rst, photutils/profiles/radial_profile.py, photutils/profiles/tests/test_radial_profile.py
This PR adds 1D `Gaussian` fits the the `RadialProfile`.  The new attributes are `gaussian_fit`, `gaussian_profile`, and `gaussian_fwhm`.
=> Add 1D Gaussian fits to RadialProfile

docs/Makefile, docs/aperture.rst, docs/background.rst, docs/conf.py, docs/detection.rst, docs/profiles.rst, docs/psf.rst, docs/psf_matching.rst, photutils/aperture/core.py, photutils/centroids/core.py, photutils/datasets/make.py, photutils/detection/peakfinder.py, photutils/morphology/non_parametric.py, photutils/psf/__init__.py, photutils/psf/matching/windows.py, photutils/psf/photometry.py, photutils/segmentation/catalog.py, photutils/segmentation/core.py, photutils/segmentation/deblend.py, photutils/utils/_convolution.py, photutils/utils/_moments.py, photutils/utils/errors.py, photutils/utils/interpolation.py
This PR makes various improvements to the docs:
- Classes now inherit docstrings from parent classes whenever possible
- Updated sphinx Makefile and config
- Consistently use array_like to agree to numpy convention
- Fix codestyle issues in narrative doc plots
- Updates the psf.matching narrative docs
=> Doc improvements

CHANGES.rst, photutils/segmentation/catalog.py, photutils/segmentation/tests/test_catalog.py
...instead of converting to a `ndarray`.
=> Keep kron_params as a tuple

CHANGES.rst, photutils/psf/models.py, photutils/psf/tests/test_models.py
This PR fixes an issue with the local model cache in ``GriddedPSFModel``, significantly improving performance.
=> Fix GriddedPSFModel local model cache

CHANGES.rst, docs/profiles.rst, photutils/profiles/core.py, photutils/profiles/curve_of_growth.py, photutils/profiles/radial_profile.py, photutils/profiles/tests/test_radial_profile.py
This PR adds a `EdgeRadialProfile` class defined using radial bin edges.
Closes: #1529
=> Add EdgeRadialProfile class

docs/background.rst, docs/detection.rst, docs/grouping.rst, docs/index.rst
This PR adds descriptive categories on the main doc page and updates a few of the narrative doc pages.
=> DOC: narrative doc updates

photutils/profiles/radial_profile.py
Adds clarification that the radius values are calculated using the arithmetic mean.
=> Update RadialProfile radius docstring

CHANGES.rst, photutils/aperture/attributes.py, photutils/aperture/tests/test_circle.py
This PR fixes a bug in the `PixelPositions` `positions` validator.
=> Fix bug in PixelPositions validator

photutils/centroids/core.py, photutils/psf/epsf.py, photutils/utils/_round.py, photutils/utils/tests/test_round.py
=> Minor updates to py2intround

photutils/psf/epsf.py, photutils/psf/photometry.py, photutils/psf/photometry_depr.py, photutils/segmentation/catalog.py, photutils/segmentation/deblend.py, photutils/utils/_progress_bars.py, photutils/utils/depths.py
Also updates the code to use the new (private) `add_progress_bar` function for all progress bars.
=> Add helper function for adding progress bars

photutils/psf/photometry.py, photutils/psf/tests/test_photometry.py
Fixes issue where negative x, y float values were rounded incorrectly.
=> Fix issue in PSFPhotometry with negative x/y values

docs/grouping.rst, photutils/psf/groupers.py
This PR updates the source grouper narrative docs using the new `SourceGrouper` class.
=> Update source grouper narrative docs

photutils/psf/models.py, photutils/psf/photometry.py, photutils/psf/tests/test_models.py
This PR further lowers memory usage (followup to #1581) to address #1580.
=> Lower memory usage when fitting with GriddedPSFModel

photutils/detection/tests/test_irafstarfinder.py, photutils/isophote/tests/test_ellipse.py, photutils/isophote/tests/test_model.py, photutils/psf/tests/test_photometry-depr.py, photutils/tests/helper.py
pytest 8.0 now re-emits all warnings
=> MNT: pytest 8.0 compatibility

docs/psf.rst
Also fixes plots to have 'origin="lower"'.
=> PSF narrative doc additions

photutils/psf/photometry.py
=> Ignore NoOverlap in iterativepsf

docs/conf.py, docs/contributing.rst
xref: https://github.com/sphinx-doc/sphinx/issues/11542
=> Do not skip anchors in linkcheck

.github/workflows/ci_cron_daily.yml, .github/workflows/ci_cron_weekly.yml, .github/workflows/ci_tests.yml
Also renames a few actions yml files.
=> Allow daily cron to be run with Extra CI label

photutils/background/background_2d.py, photutils/conftest.py, photutils/isophote/fitter.py, setup.cfg
=> Fixes for NumPy 2.0 changes

CHANGES.rst, photutils/morphology/core.py, photutils/morphology/tests/test_core.py
As requested in #1645.
Closes #1645.
=> Add wcs keyword to data_properties

CONTRIBUTING.rst, docs/contributing.rst
Motivated by fixing a broken link to the astropy developer docs.
=> Update contributor docs

CHANGES.rst, docs/psf.rst, photutils/datasets/make.py, photutils/datasets/tests/test_make.py, photutils/psf/tests/test_photometry.py, photutils/utils/_coords.py
This PR makes some improvements to the `make_test_psf_data` function:
- Added a ``border_size`` keyword to ``make_test_psf_data``.
- Improved the generation of random PSF positions
=> Improve make_test_psf_data

CHANGES.rst, photutils/utils/depths.py, photutils/utils/tests/test_depths.py
This PR improves the generation of random aperture positions in ``ImageDepth``.
=> Improve random apertures in ImageDepth

photutils/background/background_2d.py, photutils/background/interpolators.py, photutils/detection/daofinder.py, photutils/detection/irafstarfinder.py, photutils/detection/starfinder.py, photutils/isophote/ellipse.py, photutils/isophote/isophote.py, photutils/isophote/sample.py, photutils/psf/epsf.py, photutils/psf/epsf_stars.py, photutils/psf/griddedpsfmodel.py, photutils/psf/groupstars.py, photutils/psf/models.py, photutils/psf/utils.py, photutils/segmentation/catalog.py, photutils/segmentation/core.py, photutils/utils/_misc.py, photutils/utils/_optional_deps.py
These were found with the `numpydoc` `validate-docstrings` tool.
=> Docstring fixes

.github/workflows/ci_cron_daily.yml, .github/workflows/ci_tests.yml
Also updates `codecov-action` to v4.
=> Test with M1 macOS runner

photutils/background/background_2d.py, photutils/utils/_repr.py
=> Do not use ellipsis in make_repr if parameter value is None

photutils/isophote/tests/test_ellipse.py
This test sometimes gives Runtime warnings on arm64.
=> Remove problematic test on arm arch

photutils/aperture/mask.py, photutils/aperture/tests/test_mask.py
This PR fixes a failing devdeps test with NumPy 2.1.dev.
=> Update __array__ to copy if needed

photutils/aperture/stats.py, photutils/segmentation/catalog.py, photutils/segmentation/detect.py, photutils/utils/_quantity_helpers.py, photutils/utils/tests/test_quantity_helpers.py
This PR makes the error message more descriptive with the units for each input.
=> Update error message in process_quantities

CHANGES.rst, photutils/psf/photometry.py
With this PR, ``IterativePSFPhotometry`` will now only issue warnings after all iterations are completed.
=> Emit only unique warnings in IterativePSFPhotometry

photutils/psf/photometry.py, photutils/psf/tests/test_photometry.py
=> swap xy in validity check

photutils/datasets/sources.py, photutils/datasets/tests/test_sources.py, photutils/datasets/wcs.py
This PR also adds examples in the `datasets` subpackage.
=> Make flux_range a keyword in make_model_params

docs/aperture.rst
=> Add mock wcs to aperture docs

CHANGES.rst, docs/conf.py, docs/install.rst, photutils/utils/_optional_deps.py, pyproject.toml
This PR:
* Updates the installations docs
* Requires `regions >= 0.9` as an optional dependency
* Updates `docs/conf.py`
=> Misc infrastructure updates

docs/install.rst
Recommend `miniforge` for conda installs.
=> Update install docs

.pre-commit-config.yaml, photutils/aperture/tests/test_converters.py, photutils/aperture/tests/test_photometry.py, photutils/datasets/tests/test_load.py, photutils/isophote/tests/test_ellipse.py, photutils/isophote/tests/test_fitter.py, photutils/isophote/tests/test_integrator.py, photutils/isophote/tests/test_isophote.py, photutils/isophote/tests/test_model.py, photutils/isophote/tests/test_regression.py, photutils/psf/tests/test_utils.py
Also fixes new Ruff rule for parenthesis style.
=> Precommit update

CHANGES.rst, docs/psf.rst, photutils/datasets/images.py, photutils/datasets/tests/test_images.py, photutils/detection/tests/conftest.py, photutils/psf/functional_models.py, photutils/psf/tests/test_epsf.py, photutils/psf/tests/test_epsf_stars.py, photutils/psf/tests/test_functional_models.py, photutils/psf/tests/test_photometry.py, photutils/psf/tests/test_utils.py, photutils/psf/utils.py
`IntegratedGaussianPRF` is now deprecated.
=> Rename IntegratedGaussianPRF to CircularGaussianSigmaPRF

CHANGES.rst, docs/aperture.rst, photutils/aperture/converters.py, photutils/aperture/photometry.py, photutils/aperture/stats.py, photutils/aperture/tests/test_converters.py, photutils/aperture/tests/test_photometry.py, photutils/aperture/tests/test_stats.py, photutils/conftest.py
This PR also updates the documentation and docstrings regarding region to aperture conversions.
=> Allow regions.Region input to ApertureStats

photutils/aperture/stats.py, photutils/aperture/tests/test_stats.py
Also adds a unit test for the warning
=> Fix typo in warning

docs/psf.rst, photutils/psf/photometry.py
=> Add notes about excessive memory usage for large star groups

.pre-commit-config.yaml
=> Remove yesqa and pyupgrade pre-commit hooks

.pep8speaks.yml, .pre-commit-config.yaml, photutils/extern/biweight.py, pyproject.toml
These fixes are needed for photutils background classes.
=> Add astropy biweight stat fixes to extern

CHANGES.rst, photutils/background/background_2d.py, photutils/background/tests/test_background_2d.py
=> More memory optimization for Background2D

docs/install.rst, docs/psf.rst, photutils/detection/daofinder.py, photutils/detection/irafstarfinder.py
`iraf.net` reports "Account Suspended!".
This PR fixes the failing Daily CI tests.
=> Fix broken links

.github/workflows/ci_cron_weekly.yml, pyproject.toml
This test runner is paid by Astropy.
Closes #1883.
=> Add native arm64 test runner

photutils/psf/functional_models.py, photutils/psf/gridded_models.py, photutils/psf/image_models.py
=> Add bounding_box property to models

CHANGES.rst, photutils/segmentation/deblend.py, photutils/segmentation/finder.py
This PR improves the performance and reduces the memory usage of serial (nproc=1) source deblending.
=> Improve serial deblending performance

CHANGES.rst, docs/whats_new/2.0.rst, photutils/segmentation/deblend.py, photutils/segmentation/detect.py, photutils/segmentation/tests/test_deblend.py
The PR reduces the memory usage and improves the performance of source deblending with ``deblend_sources`` and ``SourceFinder`` when using serial processing.  Followup to #1924.
=> Improve performance of source deblending

.github/workflows/ci_tests.yml, .github/workflows/publish.yml, .readthedocs.yaml, CHANGES.rst, docs/conf.py, docs/getting_started/install.rst, photutils/aperture/mask.py, photutils/aperture/tests/test_mask.py, photutils/psf/model_plotting.py, photutils/tests/helper.py, photutils/utils/_misc.py, pyproject.toml, tox.ini
But keeps the removal of sklearn from tox.ini.
=> Temporarily revert PR 1930

.github/workflows/publish.yml
=> Generate nightly wheels

.pre-commit-config.yaml, photutils/psf/tests/test_photometry.py
Using the fixed commit on the `docformatter` master branch.
=> Reenable docformatter pre-commit hook

CHANGES.rst, photutils/psf/model_plotting.py
The ``GriddedPSFModel`` ``plot_grid`` color bar now matches the height of the displayed image.
=> Improved GriddedPSFModel plot_grid color bar

docs/user_guide/grouping.rst
Fixes a missing source marker.
=> Fix grouping figure

photutils/psf/photometry.py
Thanks to @mtewes for reporting this.
Fixes #2004
=> Fix description of PSF photometry qfit parameter

photutils/background/background_2d.py, photutils/psf/groupers.py, photutils/psf/photometry.py, photutils/utils/_repr.py, photutils/utils/tests/test_repr.py
This PR also updates the `Background2D` repr.
=> Add repr for SourceGrouper, PSFPhotometry, and IterativePSFPhotometry

photutils/aperture/core.py, photutils/isophote/model.py, photutils/isophote/sample.py, photutils/segmentation/deblend.py, photutils/utils/_coords.py, photutils/utils/_optional_deps.py, photutils/utils/_progress_bars.py, photutils/utils/tests/test_coords.py
This PR is a hodgepodge of various code improvements.  This PR also adds tests for the private _coords module in `utils`.
=> Misc code improvements

CHANGES.rst, docs/getting_started/install.rst, pyproject.toml, tox.ini
Following scientific python [SPEC-0](https://scientific-python.org/specs/spec-0000/).
=> Bump minimum versions of dependencies

.readthedocs.yaml, docs/conf.py
=> Update GitHub icon in docs header

.github/workflows/ci_cron_daily.yml, .github/workflows/ci_cron_weekly.yml, .github/workflows/ci_tests.yml, .github/workflows/codeql.yml, .pre-commit-config.yaml
Also adds `zizmor` to pre-commit hooks.
=> Set persist-credentials to false in checkout actions

.pre-commit-config.yaml, docs/user_guide/profiles.rst, photutils/datasets/tests/test_model_params.py, photutils/detection/tests/test_daofinder.py, photutils/detection/tests/test_irafstarfinder.py, photutils/detection/tests/test_peakfinder.py, photutils/detection/tests/test_starfinder.py, photutils/isophote/tests/test_angles.py, photutils/isophote/tests/test_regression.py, photutils/profiles/tests/test_radial_profile.py, photutils/psf/tests/test_epsf.py, photutils/psf/tests/test_image_models.py, photutils/psf/tests/test_photometry.py, photutils/segmentation/tests/test_deblend.py, photutils/segmentation/tests/test_finder.py, photutils/utils/_stats.py, photutils/utils/tests/test_depths.py, pyproject.toml
This PR:
* Adds `sphinx-lint` pre-commit hook
* Uses released `docformatter` hook
* Updates all other pre-commit hooks
* Fixes code to address new ruff and `sphinx-lint` issues
=> Pre-commit updates

photutils/background/core.py
Thanks to @emolter for reporting this.
Closes #2066.
=> Fix default maxiters default value listed in background docstrings

photutils/background/background_2d.py
=> Remove unused parameter from docstring

docs/user_guide/grouping.rst, docs/user_guide/index.rst
Also add a new section for PSF Matching.
=> Improve PSF grouping docs

CHANGES.rst, photutils/psf/tests/test_epsf.py
This PR is a followup to #2089.
=> Add regression tests for EPSFBuilder

CHANGES.rst, docs/getting_started/install.rst, docs/index.rst, docs/user_guide/detection.rst, docs/user_guide/psf.rst, docs/whats_new/1.1.rst, docs/whats_new/1.10.rst, docs/whats_new/1.11.rst, docs/whats_new/1.12.rst, docs/whats_new/1.13.rst, docs/whats_new/1.2.rst, docs/whats_new/1.3.rst, docs/whats_new/1.4.rst, docs/whats_new/1.5.rst, docs/whats_new/1.6.rst, docs/whats_new/1.7.rst, docs/whats_new/1.8.rst, docs/whats_new/1.9.rst, docs/whats_new/2.0.rst, docs/whats_new/2.1.rst, docs/whats_new/2.2.rst, docs/whats_new/2.3.rst, docs/whats_new/index.rst
Also adds a TOC to all previious What's New pages.
Also fixes some typos and updates the changelog.
=> Add What's New for 2.3.0
