astropy/photutils

docs/photutils/getting_started.rst
docs/photutils/morphology.rst
photutils/detection/tests/test_findstars.py

Tests are failing when the ``scikit-image`` package isn't available.

Adding requirements of skimage for daofind tests

---

.travis.yml
ah_bootstrap.py

For me this doesn't work with Python 3.4 and Astropy master:
```
$ python setup.py build_sphinx
...
File "/Users/deil/code/photutils/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 203, in run
self.arguments = [' '.join(clsnms).decode('utf-8')]
AttributeError: 'str' object has no attribute 'decode'
```
(see full traceback [here](https://gist.github.com/cdeil/99c717f807e0017246a9#file-gistfile1-txt-L83).)
Can someone confirm this issue?
I'll try running the sphinx build with Python 3 on travis-ci and then update the `astropy-helpers` pointer to the latest 0.4.4 release (see [astropy-helpers on pypi](https://pypi.python.org/pypi/astropy-helpers/)) to see if that is the issue.

build_sphinx doesn't work on Python 3

---

docs/photutils/segmentation.rst

(Temporary) fix for #237.  We can allow the doctest (including the table length) when we require `astropy >= 1.0`.

skip doctest in segmentation due to Table formating changes

---

photutils/aperture_core.py

@bsipocz @astrofrog Does it make sense to make PixelAperture.area an abstract method?
All tests pass before or after this change ... I made it because my editor was complaining here about the missing `self`.

Make PixelAperture.area an abstract method

---

photutils/tests/test_aperture_photometry.py

This adjustment of the aperture parameter makes to tests to pass on a 32bit setup. 
The discrepancy between 32/64 bit is most probably due to float precision. Some aperture parametrisations don't behave the same way on 32bit and 64bit for the pixels where the aperture goes through a pixel centre. Affects methods `center` and `subpixel`, see more discussion in [#242].
Closes #242.

Changing test parameters to avoid failure on 32bit

---

photutils/psf.py

`eval` is deprecated in `astropy 1.0`.  No more `AstropyDeprecationWarning`s with this PR.

Rename eval to evaluate in PSF models

---

CHANGES.rst
docs/conf.py
docs/nitpick-exceptions
docs/photutils/detection.rst
photutils/detection/core.py
photutils/detection/findstars.py
photutils/detection/tests/test_core.py
photutils/morphology.py
photutils/tests/test_morphology.py
photutils/utils/wcs_helpers.py

This PR implements #235.  If `subpixel=True` then the output `Table` also includes the centroid and fitted peak amplitude in addition to the (integer) peak pixel position and value.
I still need to add some tests.
This PR also removes the `segment_image` option, since one should now use `segment_properties()` when working with segmentation images.

Allow subpixel precision in find_peaks

---

.travis.yml
CHANGES.rst
ah_bootstrap.py
docs/photutils/detection.rst
docs/photutils/morphology.rst

Several updates to ``.travis.yml``:
- use released astropy v1.0 instead of v.1.0rc
- adding ``-w`` option to python3 sphinx build as https://github.com/astropy/astropy-helpers/pull/123 is released in astropy-helpers v0.4.5
- it seems that #202 is fixed on the conda side, remove workaround

Update astropy-helpers to v1.0 and update travis to use astropy v1.0 (and remove workarounds)

---

photutils/conftest.py

Currently the testing doesn't print out the version number of ``photutils`` anywhere in the header only Astropy's. 
This is the package side change, the feature is introduced in https://github.com/astropy/astropy/pull/3543
With this change the tests start as:
```
======================================= test session starts =======================================
platform darwin -- Python 2.7.5 -- pytest-2.5.1
Running tests with photutils version 0.2.dev1345.
Running tests in photutils /Users/bsipocz/munka/devel/photutils/docs.
Platform: Darwin-10.8.0-x86_64-i386-32bit
...
```

Adding photutils version number to testing header

---

CHANGES.rst
docs/changelog.rst
docs/conf.py
docs/index.rst

This PR adds the changes pages to the docs, so that it's more easily found by users.
It includes the top-level `CHANGES.rst` file, just like Astropy does it.

Add changelog page to docs

---

photutils/background.py
photutils/detection/core.py
photutils/detection/tests/test_core.py

Tests are currently failing because of changes in `sigma_clip` and `sigma_clipped_stats` in astropy master.  There is also a small bug in astropy's `sigma_clip` that I need to fix where a scalar mask is returned when no values are clipped.  In that case `ma.data[~ma.mask]` doesn't give the desired result.

Update sigma clipping based on updated astropy

---

photutils/aperture_core.py
photutils/tests/test_aperture_photometry.py

Now ``unit`` overrides the dataunit that was the result of parsing ``BUNIT``. Issues a warning if ``dataunit`` and ``unit`` is different, however still raises an error is ``data.unit`` existed (the input wasn't a fits file). I think this is the right approach, if ``data.unit`` was already set, we should trust that it's the right one.
Put in a few ``try... except``, that is not very nice and I'll come up with something else if it slows down the benchmarks.
Closes #272

Unit kwarg to override data unit from BUNIT

---

CHANGES.rst
photutils/geometry/core.pyx
photutils/geometry/elliptical_overlap.pyx
photutils/geometry/rectangular_overlap.pyx
photutils/geometry/tests/__init__.py
photutils/geometry/tests/test_circular_overlap_grid.py
photutils/geometry/tests/test_elliptical_overlap_grid.py
photutils/geometry/tests/test_rectangular_overlap_grid.py

The problem I reported in #265 was due to the pixel normalization being done twice, once in ``rectangular_overlap_single_subpixel`` and again in ``rectangular_overlap_grid``.  I have removed the 2nd one and now the results are what I expected.

Fix normalization for rectangular and elliptical regions

---

CHANGES.rst
photutils/geometry/core.pyx

This fixes #242 for me
The new if handles the case where the closest point of the triangle is **on** the circle. Then the triangle is outside the circle and the area is 0.0

Add a new case to circle-triangle intersection area

---

.travis.yml

This PR checks whether the builds are running faster when opting back to conda from pip. 
The travis build time almost doubled since we changed from conda to pip (in #275), and as @mwcraig uploaded builds for astropy v1.0.3 and matplotlib v1.4.3 I expect all tests to pass (#270 and #274).

Opt back to use conda for stable astropy and matpotlib

---

ah_bootstrap.py
docs/photutils/background.rst
docs/photutils/morphology.rst
photutils/datasets/tests/test_make.py
photutils/tests/test_aperture_photometry.py
photutils/tests/test_segmentation.py

The failing doc tests in https://github.com/astropy/photutils/pull/284 and https://github.com/astropy/photutils/issues/285 are not due to the `astropy-helpers` update.  They occurred because the `sigma_clipped_stats` `iters` default value changed from `None` to `5` in `astropy dev`.  In this PR, I explicitly set `iters=5` so all versions of `astropy` are happy.

Update astropy-helpers to 1.0.5 (and fix failing tests)

---

photutils/aperture_core.py
photutils/tests/test_aperture_photometry.py

This PR fixes an inconsistency where a scalar `Quantity` input position remains a scalar in the aperture `.positions` attribute:
```
pos1 = u.Quantity((10, 20), unit=u.pixel)
ap1 = CircularAperture(pos1, r=3)
ap1.positions
array([ 10.,  20.])
```
but for a non-`Quantity` scalar, `.positions` is always a 2D array, which is the expected behavior:
```
pos2 = (10, 20)
ap2 = CircularAperture(pos2, r=3)
ap2.positions
array([[ 10.,  20.]])
```
This PR ensures that `.positions` is always at least 2D.

Ensure that PixelAperture.positions is at least 2D

---

.travis.yml
appveyor.yml

This is the prototype for the usage of the new ci-helpers package to setup the conda environments for travis and appveyor.
cc @astrofrog

Use external ci-helpers

---

photutils/aperture_core.py

The `area` docstring is defined in the abstract `PixelAperture` class.  This PR also fixes issue #210.

Remove RectangularAnnulus.area docstring

---

.travis.yml

Closes #289.
The PR also removes duplicated py2.7 and astropy development build.

Adding travis builds against LTS astropy

---

photutils/background.py
photutils/detection/core.py
photutils/tests/test_segmentation.py

This PR uses `LooseVersion` for more robust and simpler version checking.

More robust version checking

---

photutils/detection/core.py

I originally planned to implement a way where the detection threshold could be an array for `find_peaks` (which sounds like a simple extension of the existing algorithm, since find_peaks works local anyway), but then I found that that works already.
Thus, I now only propose this minor update to the docs.
[skip ci]

find_peaks works well with a threshold array

---

CHANGES.rst
photutils/detection/deblend.py
photutils/detection/tests/test_deblend.py

This PR fixes #341.  The issue was the pixel connectivity wasn't being passed to the watershed algorithm.

Pass pixel connectivity to the watershed algorithm in source deblending

---

photutils/detection/core.py

Just fixing a minor typo in the docstring.

[DOC]: sigclip_iters should be int rather than float

---

LONG_DESCRIPTION.rst
README.rst
docs/index.rst
docs/photutils/overview.rst
setup.cfg

Updates the RTD links from `readthedocs.org` to `readthedocs.io`.

Update RTD links

---

CHANGES.rst
photutils/detection/deblend.py
photutils/detection/tests/test_core.py
photutils/detection/tests/test_deblend.py
photutils/segmentation.py
photutils/tests/test_segmentation.py

This PR significantly improves the performance of segmentation-based photometry by caching (using astropy's `@lazyproperty`) `SegmentationImage` properties.  This PR also adds a few source deblending tests.

Cache SegmentationImage properties 

---

.travis.yml
appveyor.yml

Update numpy and astropy versions for both travis and appveyor, and adding a build against the numpy prerelease for travis (as well as the now old 1.10).

Updating versions for CIs

---

CHANGES.rst
docs/photutils/aperture.rst
docs/photutils/segmentation.rst
photutils/aperture_core.py
photutils/aperture_funcs.py
photutils/psf/core.py
photutils/segmentation.py
photutils/tests/test_aperture_photometry.py
photutils/tests/test_segmentation.py
photutils/utils/prepare_data.py
photutils/utils/tests/test_prepare_data.py

This PR implements https://github.com/astropy/photutils/issues/178.  The ``effective_gain`` keyword is removed from all photometry routines, which now require the user to input the total (1-sigma std.) error.  The total error can be calculated using ``photutils.utils.calc_total_error``, which combines a "background-only" error array with the source Poisson noise using the ``effective_gain``.

Remove the "effective_gain" keyword from the photometry routines

---

photutils/aperture/core.py
photutils/utils/prepare_data.py

This should fix the failing sphinx builds. And from now on we can build the docs in either py2 or py3.
What do you prefer @larrybradley, should we switch over to py3? If yes, then we should do it on RTD, too and older older releases may may fail with it...

Fixing links for helpers 1.2

---

CHANGES.rst
photutils/psf/funcs.py
photutils/psf/tests/test_psf_photometry.py

This is just a rebased version of [#358](https://github.com/astropy/photutils/pull/358). I messed up #358 when I was rebasing :|
cc @eteq, @hamogu, @bsipocz

Add a way to get fitted params uncertainties in psf_photometry

---

CHANGES.rst
docs/nitpick-exceptions
docs/photutils/detection.rst
photutils/detection/findstars.py
photutils/detection/tests/test_findstars.py

Hi all,
this is an attempt to change the interface of the findstars module, so that it will be in accordance to what was discussed during the JWST code sprint.
With this OOP interface, users will have to create instances of ``DAOStarFinder`` or ``IRAFStarFinder`` which are classes that basically encapsulates the FIND algorithm from DAOPHOT and the starfind algorithm from IRAF, respectively.
The functional interface will still be available to users, however a deprecation warning will be raised.
cc @hamogu @bsipocz @eteq @larrybradley

findstars oop interface

---

CHANGES.rst
photutils/aperture/core.py

The origin keyword is useful for plotting apertures on a cutout or subsample of the data.
This PR also refactors the aperture `plot` methods by placing repeated code in a new `_prepare_plot` method on the `PixelAperture` base class.

Add an origin keyword to aperture plot methods

---

photutils/detection/core.py
photutils/detection/deblend.py
photutils/detection/findstars.py
photutils/segmentation.py
photutils/utils/__init__.py
photutils/utils/convolution.py

I've made _convolve_data public and renamed it filter_data. This will serve as a convenience function for users who would like to inspect their images at each step of their pipeline. This is a follow-up to PR  #397. 
Thanks

made _convolve_data public and renamed filter_data

---

photutils/detection/findstars.py

Fixed a very minor typo in the docstring of DAOStarFinder.

fixed minor typo in DAOStarFinder docstring

---

.travis.yml

This PR follows the logic of astropy (https://github.com/astropy/astropy/pull/5075) for only testing a smaller combination of old python and numpy as they should be tested with each other by numpy. This should save us a few minutes of CI time.
Also adds an OSX build.

Clearing up travis and adding osx build

---

photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

As I mentioned in https://github.com/astropy/photutils/pull/385#issuecomment-243602857, I had a few changes I wanted to suggest from #385 that seemed easier to just write up myself.  So this PR has those.  @mirca @hamogu @bsipocz, any thoughts you have on these are welcome:
* I changed `fitshape` so that it can be a lone int, meaning "a square with lengths of that shape".  I think that's one of the most common use cases so it seems sensible to have that shortcut.
* I did a bunch of renames of the attributes in `DAOPhotPSFPhotometry`.  Specifically, `group`->`grouper`, `bkg`->`bkg_estimator`, `psf`->`psf_model`, and `find`->`finder`.  I found the original names to be confusing because it's not clear it's the "thing that does that".  E.g., `group` would at first seem to be the actual list …

Modifications from #385

---

photutils/psf/groupstars.py

This fixes a warning I've been seeing pop up about an improperly-named section.  (for some reason sphinx doesn't recognize this particular type of "warning" as a sphinx build warning... but it still appears in the logs.  Anyway, this fixes it.)

fix see also section that was missing "also"

---

photutils/psf/models.py
photutils/psf/photometry.py
photutils/psf/tests/test_misc.py

This follows some of the discussion from #417 (that was about whether or not `GroupPSF` should be inside `DAOPhotPSFPhotometry`).  After looking at that I realized not only does it make sense for `GroupPSF` to not be only available from `DAOPhotPSFPhotometry`, but it probably also should be a generator function.
My reasoning is that the `GroupPSF` class is a bit surprising: it *sounds* like it's a model, but it's actually a class with a method that *generates* a model.  I think it's cleaner (and more likely to be re-usable by others) to just change this to a function which returns the new model.  That way there's not confusion between the class that *is* the model and the class that *makes* the model (because after this PR the latter is not a class at all).
This also closes #417 by moving …

Change GroupPSF class to a generator function

---

photutils/background/core.py
photutils/detection/core.py
photutils/extern/sigma_clipping.py

The function signature and feature options for `astropy.stats.sigma_clip` changed in `astropy 1.1`.  Instead of adding boilerplate astropy version checking code when `sigma_clip` or `sigma_clipped_stats` is called in `photutils`, I've simply added the latest `astropy` sigma clipping functions in `extern`.  We can remove this and update the `sigma_clip` and `sigma_clipped_stats` imports when we no longer support `astropy 1.0`.
I've updated this in `detection.core` and `background.core`.  I'll also update it in `background.background2d` within a separate PR on 2D backgorunds that I'm currently working on.

Add astropy sigma clipping functions to extern

---

.travis.yml

This PR changes the `travis-ci` test with the numpy pre-release version to be an allowed failure.
@bsipocz, you changed this in #396 from an allowed failure.  Was that intentional?
It appears that while this "test" has been passing, looking in the `travis-ci` logs, it appears that the tests haven't actually been running.  This test is now failing in the middle of the tests without any indication why it's failing:
https://travis-ci.org/astropy/photutils/jobs/159388076
Any objections to making this test an allowed failure again?

Allow failures for travis-ci test with numpy pre-release version

---

CHANGES.rst
photutils/background/core.py
photutils/background/tests/test_core.py
photutils/psf/tests/test_photometry.py

With this PR `SigmaClip` is no longer a mixin class.  Instead one must input a `SigmaClip` object to the background classes.
The `SigmaClip` class can be used in any function that performs sigma clipping as part of its functionality.  Instead of passing all of the many `sigma_clip` keywords to such a function, one can simply create a `SigmaClip` object and pass that to any function/class as needed.

Make SigmaClip a general class

---

.travis.yml
appveyor.yml

`travis-ci` tests appear to be failing because `Qt4` is missing (needed for `matplotlib` backends).  This is an attempt to fix that.
EDIT:  `appveyor` too.

Pin qt version to v4

---

.travis.yml
appveyor.yml

The upstream issues have been fixed (e.g. https://github.com/ContinuumIO/anaconda-issues/issues/1090).
Fixes https://github.com/astropy/photutils/issues/429.

Unpin qt=4

---

README.rst
docs/index.rst

This adds a section to the index page of the docs on citing photutils, pointing to zenodo (a la the discussion in #422).
One complication I realized: it's not possible to actually provide the DOI link in the docs themselves, because the DOI doesn't get minted.  So my workaround here is to just say "search for photutils on zenodo".  Formally speaking that's the write answer anyway because in principal they should cite the specific version they use.  But I'm open to any ideas on how best to address this...? (@astrofrog @larrybradley @bsipocz, or maybe @arfon has an idea of how this is supposed to work with the github integration?)
If merged, I'd say this closes #422.

add request to cite photutils via Zenodo

---

docs/index.rst

The current docs index page has a somewhat scary-sounding warning.  This PR updates it to be a bit softer, basically saying "we won't break the API unless there's a good reason."
Does this seem like reasonable wording (and something that's reasonable to keep), @larrybradley

Soften API warning

---

docs/conf.py

The `travis-ci` `build_sphinx` tests are currently failing because of a "nonlocal image URI found" Sphinx warning.  This warning is caused by the external Zenodo badge image, which was added to the docs in https://github.com/astropy/photutils/pull/434.  This PR monkey patches Sphinx to suppress "nonlocal image URI found" warnings.
For reference, I first tried using the `suppress_warnings = ['image.nonlocal_uri']` configuration option introduced in Sphinx `1.4` (http://www.sphinx-doc.org/en/stable/config.html#confval-suppress_warnings), but that gave an `astropy_helpers` warning:
```
WARNING: while setting up extension astropy_helpers.sphinx.ext.autodoc_enhancements: directive 'autoattribute' is already registered, it will be overridden
```
@eteq Is this warning related to …

Monkey patch Sphinx to suppress "nonlocal image URI found" warnings

---

CHANGES.rst
docs/photutils/aperture.rst
docs/photutils/background.rst
docs/photutils/detection.rst
docs/photutils/overview.rst
docs/photutils/segmentation.rst
photutils/background/background_2d.py
photutils/background/core.py
photutils/background/tests/test_background_2d.py
photutils/background/tests/test_core.py
photutils/utils/__init__.py
photutils/utils/stats.py
photutils/utils/tests/test_stats.py

This PR is a refactor/rewrite of the 2D Background class (`Background2D`) to use an object-oriented interface (using the background and background RMS classes).  Here's a simple example:
```
from photutils import SigmaClip, MedianBackground, StdBackgroundRMS, Background2D
sigma_clip = SigmaClip(sigma=3., iters=10)
bkg_estimator = MedianBackground()
bkgrms_estimator = StdBackgroundRMS()
bkg = Background2D(data, (50, 50), sigma_clip=sigma_clip, bkg_estimator=bkg_estimator, bkgrms_estimator=bkgrms_estimator)
```

Refactored 2D Background class to use object-oriented interface

---

docs/photutils/psf.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This is a rework of #421.
The actual plan as stated by @eteq is the following:

PSF Photometry module refactoring

---

photutils/psf/models.py
photutils/psf/tests/test_models.py

This PR adds a fittable 2D model that takes a 2D array and can evaluate the model at arbitrary (within the domain of definition) points. That is, it behaves like a continuous fittable model.

Add a fittable FittableImageModel class

---

photutils/psf/models.py
photutils/psf/tests/test_imagemodel.py

This updates `FittableImageModel` (added in #413) to support oversampling.  It also beefs up the tests of that model to be a bit more complete.
cc @larrybradley

Allow FittableImageModel to support oversampling

---

photutils/aperture/core.py

This PR allows a list of aperture objects to be input to `aperture_photometry`.  All of the aperture inputs must have identical positions.  For multiple apertures, the output table column names are appended with the position index.
This also works for sky apertures, provided they have the same positions.
Examples:
```
from photutils import CircularAperture, aperture_photometry
pos = [(40, 40), (50, 50), (60, 60)]
radii = [3, 5, 7]
apers = [CircularAperture(pos, r=r) for r in radii]
data = np.ones((100, 100))
tbl = aperture_photometry(data, apers)
print(tbl)
id xcenter ycenter aperture_sum_0 aperture_sum_1 aperture_sum_2
pix     pix                                               
--- ------- ------- -------------- -------------- --------------
1    40.0    40.0  28.2743338823  78.5398163397 …
```

Allow a list of apertures to be input to aperture_photometry

---

CHANGES.rst

I forgot to write the changelog entries for those PRs, which resulted in a misleading changelog for the 0.3 release. Sorry.
cc @eteq @larrybradley

Update 0.3 changelog

---

photutils/psf/models.py

This fixes a subtle but very important bug in how the `FittableImageModel` represents its center.  This is a pretty major functionality bug so it might be reason for a 0.3.1 release soonish...
cc @larrybradley

fix subtle oversampling bug

---

README.rst
docs/index.rst

This PR fixes an issue where the RTD builds are failing with the latest `docutils` release.  Remote images in the `Sphinx` docs must now have a `:remote:` tag

Add remote tag for remote image in docs

---

CHANGES.rst
docs/index.rst
docs/photutils/aperture.rst
photutils/aperture/__init__.py
photutils/aperture/bounding_box.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/mask.py
photutils/aperture/rectangle.py
photutils/utils/__init__.py
photutils/utils/misc.py

This `BoundingBox` class was introduced in the `regions` package.  This PR makes `photutils.aperture` similar to region masking in the `regions` package.
Also the `ApertureMask` `apply()` method was renamed to `multiply()`, which matches the `regions` package.

Update aperture subpackage to use BoundingBox class

---

.travis.yml

I've switched on travis to run once a week from cron on master, unless there has been a build in the previous 24 hours. 
However I think it's no use to run it on the whole matrix, we don't expect any changes and failure with old versions of dependencies that were tested and passed when the last build was run.

Selecting jobs to run with travis cron

---

CHANGES.rst
docs/photutils/aperture.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py

This PR removes the `pixelwise_errors` keyword from `aperture_photometry`.  With the recent refactoring of the aperture subpackage to use mask objects, using pixelwise errors is actually slightly *faster* than using the approximation.  When refactoring, I also discovered a long-standing bug when not using pixelwise errors and the central aperture pixel happened to be masked -- in that case the resulting aperture sum error was always 0 (there is not an easy fix for that issue -- it likely requires using masked arrays).
I discussed this issue with @astrofrog at the JWST data analysis workshop and he agreed with removing the `pixelwise_errors` keyword.

Remove pixelwise_errors keyword from aperture_photometry

---

CHANGES.rst
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py

Example:
```python
>>> from photutils import CircularAperture
>>> a = CircularAperture((10, 20), r=3)
>>> a
<CircularAperture([[10, 20]], r=3.0)>
>>> print(a)
Aperture: CircularAperture
positions: [[10, 20]]
r: 3.0
```

Add __repr__ and __str__ for aperture classes

---

CHANGES.rst
photutils/aperture/core.py

This PR improves the plotting annuli apertures.  When creating the annulus patch, it uses the bezier curve path instead of line segments between vertices.
Old:
New:

Use Bezier curve for annulus plotting

---

.travis.yml
appveyor.yml
photutils/extern/nddata_compat.py

Probably we need to wait a bit more until all the dependencies become available on python 3.6.

Adding python 3.6 to CI builds

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This PR fixes https://github.com/astropy/photutils/issues/496.  The x and y array padding widths were swapped (sigh), so this bug affected input arrays that required unequal padding along each axis.  The tests were also updated to catch this case now.

Fix Background2D for unequal array padding

---

photutils/aperture/bounding_box.py

This is yet another fix for BoundingBox.from_float(). In the case where the upper bound is at the pixel edge (e.g. xmax=2.5), the code was effectively rounding up and then adding 1. In those cases, the bounding box upper bound is too large by one pixel.
Note that this "fix" affects only aperture masks, not photometry.

Fix BoundingBox from_float() upper bounds

---

docs/conf.py

Explicitly set docs `highlight_language` to `python3`.  This will fix the missing button to hide output in code blocks.
Related to https://github.com/astropy/astropy-helpers/pull/287

Highlight docs as python 3

---

CHANGES.rst
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py

The current bounding box for rectangular apertures is defined as the smallest square that will contain the rectangle at all rotation angles.
Note that the minimal bounding box here is defined for the "exact" rectangle.  For `method="center"` the bounding box could have an extra pixel of padding on each side.
Addresses #499.

Use true minimal bounding box for rectangular apertures

---

CHANGES.rst
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py

The current bounding boxes are not optimized.

Define minimal bounding box for exact elliptical apertures

---

docs/conf.py

This is necessary to build the docs locally.  I shouldn't have removed it in #506!

Add html_static_path

---

CHANGES.rst
docs/photutils/aperture.rst
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py
photutils/utils/wcs_helpers.py

This PR also centralizes the `to_pixel` calculations in the core `SkyAperture` class.

Add to_sky method for pixel apertures

---

docs/photutils/psf.rst
photutils/extern/decorators.py
photutils/psf/models.py
photutils/psf/photometry.py
photutils/psf/tests/test_misc.py
photutils/psf/tests/test_photometry.py

Fixes #464 and #478. 
This works fine for ``BasicPSFPhotometry``. However, we should be careful for ``IterativelySubstractedPSFPhotometry``, for instance, in case where ``positions`` is not ``None`` and ``niters > 1``,  there is no way to get initial guesses for additional parameters in the next iterations. For now, the code uses the default value of the parameter in the PSF model.
cc @eteq 
@Gabriel-p do you have time to review this? :)

add <param>_0 and <param>_fit machinery back

---

.travis.yml
appveyor.yml
docs/conf.py
photutils/psf/sandbox.py

Adds a `Reproject` class to the PSF sandbox for reprojecting pixel coordinates between unrectified and rectified images.

Add Reproject class

---

photutils/psf/photometry.py

This is a small improvement on ``_model_params2table``.
The method ``_model_params2table`` does not need to receive the table ``star_group``, it only needs its size.
cc @eteq

Only pass the size of the star group instead of the whole star group table

---

photutils/datasets/make.py
photutils/datasets/tests/test_make.py

This PR slightly generalizes the machinery in `photutils.datsets` to support generic models rather than just gaussian models.
The proximate use case is for code I regularly re-do in some of the notebooks to mock up PSF-photometry.  More generally, this is going to be useful down the line for doing artificial star tests.  
A couple questions for @larrybradley : I followed the naming scheme of `make_random_gaussians` and `make_gaussian_sources`, but I find that a bit confusing - it's not clear from the names which makes the table, and which makes the "image".  Is there some reason I'm missing for this naming scheme?  And do you think we can change it even if it's a subtle backwards-compatibility break? (Or should we deprecate?)
And a related question: does it make more sense to instead move …

Add a generic model-based image generator

---

docs/photutils/aperture.rst
docs/photutils/detection.rst
docs/photutils/grouping.rst
docs/photutils/morphology.rst
docs/photutils/psf.rst

This prevents the `.. doctest-requires:: scipy, skimage` directive to appear as a code block in the HTML documentation.

remove double colon before doctest-requires

---

CHANGES.rst
photutils/segmentation/core.py
photutils/utils/colormaps.py
photutils/utils/tests/test_colormaps.py

`random_cmap` can now be used more generally, while the `background_color` option is reserved for the `SegmentationImage.cmap()` method.

Remove background_color keyword from random_cmap

---

docs/photutils/install.rst

`DBSCANGroup` requires `scikit-learn` as an optional dependency, which is now noted in the installation docs.

Add scikit-learn as optional dependency

---

CHANGES.rst
photutils/utils/errors.py

This is required to propagate errors in `calc_total_error`.  Addresses #535.

Ensure data and bkg_error have the same units in calc_total_error

---

.travis.yml
CHANGES.rst
docs/photutils/install.rst

I still have check whether we have any workaround, but opening this nevertheless to keep this in out mind.

Remove numpy 1.8 and python 3.3 from testing

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

Prompted by #543, this PR improves the mesh rejection algorithm such that it now also applies to any pixels rejected from sigma clipping.  Previously the mesh rejection applied only to the input `mask` array.  This PR also simplifies the API by combining the functionality of the `exclude_mesh_method` and`exclude_mesh_percentile` keywords into a single `exclude_percentile` keyword.  A few tests were also added to increase test coverage.

Background2D improvements

---

CHANGES.rst
docs/photutils/background.rst
photutils/background/core.py
photutils/background/tests/test_core.py
photutils/extern/biweight.py
photutils/extern/stats.py

`biweight_scale` is a standard deviation (RMS) estimator.  This change follows https://github.com/astropy/astropy/pull/5991.

Rename BiweightMidvarianceBackgroundRMS to BiweightScaleBackgroundRMS

---

CHANGES.rst
photutils/psf/photometry.py

`IterativelySubtractedPSFPhotometry` iterates until the star finders detect no more sources.  The star finders issue a warning when no sources are detected.  Thus, `IterativelySubtractedPSFPhotometry` will always raise this warning, even when everything worked perfectly fine.
This PR catches this warning after the first iteration of `IterativelySubtractedPSFPhotometry`.  In other words, if no stars are detected on the first iteration, the warning is still issued.  After that, the warning is suppressed.
Also, this warning is the reason why the Sphinx builds are failing for #562.

Catch warning about no detected sources in IterativelySubtractedPSFPhotometry

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_deblend.py

This PR fixes a bug reported in https://github.com/astropy/photutils/issues/563 by @karpov-sv.
`deblend_sources` now correctly deblends multiple blended sources.

Fix source deblender to handle multiple blended sources

---

CHANGES.rst
docs/photutils/install.rst
docs/photutils/psf.rst
photutils/aperture/tests/test_aperture_photometry.py
photutils/background/tests/test_background_2d.py
photutils/psf/matching/tests/test_windows.py
photutils/psf/models.py
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_properties.py

This PR also bumps the minimum required version of `scipy` from `0.15` to `0.16`.

Remove code for outdated dependencies

---

.travis.yml

* disabling astropy LTS testing as ci-helpers will cancel it anyway while stable==lts
* adding numpy 1.12 to the matrix

Revising travis matrix post astropy 2.0

---

.travis.yml

As astropy doesn't support python2 any more, this test is expected to always fail from now on.

Removing astropy dev testing using python2

---

photutils/datasets/make.py
photutils/datasets/tests/test_make.py

Useful for testing....
`make_wcs` hasn't been released yet, so I don't think this needs a changelog entry.

Add option to make_wcs to produce WCS in Galactic coordinates

---

photutils/psf/funcs.py
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

See https://github.com/astropy/photutils/issues/558#issuecomment-319665484
`prepare_psf_model` sets attributes `xname`, `yname`, but `_extract_psf_fitting_names` looks for `psf_xname` and `psf_yname`.

Fix finding of psf attribute names

---

photutils/datasets/load.py

This PR updates the `datasets.load()` function to:
* cache by default
* have an explicit option to download from the `photutils-datasets` repo
* use the `photutils-datasets` repo as a backup in case the astropy data server is down

Update to datasets.load()

---

CHANGES.rst
docs/photutils/aperture.rst
docs/photutils/datasets.rst
docs/photutils/detection.rst
docs/photutils/getting_started.rst
docs/photutils/psf_matching.rst
photutils/datasets/load.py

Also sets `show_progress=False` by default so the local doctests will pass with `--remote-data` (even if the file has already been cached).

 Add show_progress keyword to datasets.get_path

---

.travis.yml
setup.cfg

This PR:
* moves the OSX test from regular testing to a cron test
* implements the new build stages
* adds a `flake8` test
* removes the pycodestyle from `setup.cfg`

Updates to travis-ci

---

docs/photutils/segmentation.rst

This is a temporary workaround for the doctests until https://github.com/astropy/astropy/pull/6714 is released.  By giving the tables different names, the columns should not be garbage collected.

Rename table variables to prevent table-format bug

---

.run_docker_tests.sh
.travis.yml
CHANGES.rst
appveyor.yml
docs/conf.py
docs/photutils/install.rst
photutils/aperture/core.py
photutils/background/core.py
photutils/detection/findstars.py
photutils/psf/groupstars.py
setup.cfg

This may need a changelog entry, as now six becomes formally a dependency?

Use system six rather than the deprecated astropy bundled one

---

docs/photutils/segmentation.rst

The table column format bug randomly occurred again.  Using a different format string should fix this (the format string is used as part of the cached dictionary key).

Use different format string to fix caching

---

docs/index.rst
docs/photutils/isophote.rst

The notebooks are in the `photutils-datasets` repo (https://github.com/astropy/photutils-datasets/pull/13).
CC: @ibusko, @SaraOgaz, @pllim

 Add links to isophote notebooks

---

CHANGES.rst
docs/photutils/morphology.rst
docs/photutils/segmentation.rst
photutils/conftest.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_properties.py

The `SourceCatalog` class holds the list of `SourceProperties` instances and is returned by the `source_properties` function.  This simplifies the API (and the underlying code).
This PR also deprecates the `properties_table` function.  Instead, the `SourceCatalog` has a `to_table()` method to create an astropy `QTable` of the catalog.

Add SourceCatalog class

---

CHANGES.rst
photutils/utils/interpolation.py
photutils/utils/tests/test_interpolation.py

This PR replaces #526.  For some reason, github won't let me push to @pllim 's branch.

Deprecate unused interpolate_masked_data function

---

.travis.yml

ci-helpers now takes care of installing pytest-astropy for astropy dev (and later for stable when 3.0 is out)

Minor travis cleanup

---

.gitignore

This `v` directory started appearing on failed tests when running `pytest`.

Ignore pytest last failed cache directory

---

docs/segmentation.rst

Alas, the astropy table-format bug showed up again in `travis-ci`.  This PR works around it by using a variety of format strings (which are used in addition to the `id()` as the key for the cache dictionary).

Workaround Table format bug using a variety of formats

---

CHANGES.rst
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

This is useful for excluding pixels/regions from source detection.
This will also be used to fix the deblending bug reported in #616.

Add mask keyword to detect_sources

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_deblend.py

Fix #616.
To deblend a source a small stamp is created and can contain other
sources, depending on the shape of the source mask. These neighboring
sources are not masked so they are used in the deblending process. Given
that the data array is also used for flux computation before the
watershed, the most abvious solution is to put values outside the source
mask to zero. 
Maybe there is a better approach ? I will also try to make a test with a simulated image which reproduce the issue.

Fix deblending with sources not in the segmentation mask

---

photutils/aperture/tests/test_aperture_photometry.py

Maybe we also need to test the warning when there is both a unit for the input data and provided by kwarg?

Minor fix to the tests to test the input unit not kwarg

---

.travis.yml

Numpy stable is now v1.14, so v1.13 wasn't being tested.

Add numpy 1.13 to travis tests

---

photutils/aperture/mask.py
photutils/aperture/tests/test_mask.py

This PR fixes an aperture photometry bug that was triggered when the aperture `x` and `y` positions were both negative *and* the aperture had no overlap with the data.  Instead of returning `nan`, it would incorrectly return a value.
This PR also adds a `copy` keyword to the `ApertureMask.cutout()` method and `ApertureMask` unit tests.
Fixes #637.

Fix corner-case aperture photometry bug

---

photutils/aperture/circle.py

The `CircularAnnulus` plots will now be circles instead of polygon-approximated circles.

Use Circle instead of CirclePolygon patches for CircularAnnulus plots

---

photutils/isophote/tests/test_fitter.py
photutils/isophote/tests/test_geometry.py
photutils/isophote/tests/test_harmonics.py
photutils/isophote/tests/test_integrator.py
photutils/isophote/tests/test_isophote.py

I tracked down the newly-failing `Travis-CI` tests to a change somewhere in the `pytest.approx` function in the latest `pytest` release.  This PR replaces the use of `pytest.approx` with `numpy.testing.allclose`.  All of the tests now pass locally for me.

Update isophote subpackage tests

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_deblend.py
photutils/segmentation/tests/test_properties.py

This PR fixes two issues in the `segmentation` subpackage.  `deblend_sources` will now properly deblend sources when the data within the segment contain one or more NaNs.  The `source_properties` function will now also properly handle any NaNs in the data (instead of raising an error).  In both cases, the NaN values are ignored.

Fixed issues with deblend_sources and source_properties when NaNs are present

---

photutils/conftest.py

Adds version number reports for `Cython` and `scikit-learn` and removes `Pandas`.

Add more package version numbers when running tests

---

CHANGES.rst
docs/segmentation.rst
photutils/aperture/bounding_box.py
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py
photutils/segmentation/tests/test_detect.py
photutils/segmentation/tests/test_properties.py

This PR adds several enhancements to the segmentation subpackage, mostly within the `SegmentationImage` class.  This class now has a property which can be used to generate a list of `Segment` objects, one for each labeled region.  The `Segment` object holds the cutout image and properties (e.g. slices, `BoundingBox`, area) of a single source segment.  There is also new ``check_labels`` method and ``missing_labels`` property.  Some `SegmentationImage` attributes were also renamed (with the old names deprecated).  The segmentation subpackage narrative docs were also improved, particularly additions to the source deblending section.
This PR also includes a fix to not include the zero (background) label in the `areas` attribute.
Finally, ``plot`` and ``to_aperture`` methods were added to the …

Enhancements to source segmentation

---

CHANGES.rst
photutils/isophote/ellipse.py
photutils/isophote/fitter.py
photutils/isophote/geometry.py
photutils/isophote/integrator.py
photutils/isophote/model.py
photutils/isophote/sample.py
photutils/isophote/tests/test_ellipse.py

This PR fixes an issue in isophote fitting where the fitting could fail when the input image is elongated and the initial object center is not specified.  The fitting could also fail for elongated images if the source was close to the image edge.
Fixes #670.  Thanks to @hujh08 for reporting this!

Fix isophote fitting when initial centers are not specified

---

photutils/psf/models.py

`ky` argument (spline degree for the Y-axis) for `RectBivariateSpline` is incorrect: `ky` should be set to `degy` - no to `degx`.

Fix typo in spline degree for Y axis

---

CHANGES.rst
docs/centroids.rst
docs/detection.rst
docs/getting_started.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/detection/findstars.py
photutils/detection/tests/test_core.py
photutils/detection/tests/test_findstars.py
photutils/morphology/core.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_detect.py
photutils/utils/_moments.py
photutils/utils/tests/test_moments.py

The tests are failing due to an upstream change in `scikit-image 0.14` where the row-column order was is swapped in the output of the moments function.  This PR implements a (private) moments function, removing the `sckit-image` moment dependencies.
As a result of the changes, the `centroid_com` function was generalized and can now accept an n-dimensional array as input.

Fix failing tests

---

photutils/centroids/core.py
photutils/centroids/tests/test_core.py

This PR allows the `centroid_com` `mask` keyword to be a non-boolean array.  Previously, if an integer mask array was input, it could give a wrong result (instead of raising an error).
Thanks to @ysBach for reporting this.

Allow centroid_com mask to be non-boolean

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py
photutils/utils/wcs_helpers.py

This PR replaces the `is` operator with `==` for when checking input quantity units.  Thanks to @shiaki for reporting this issue.
Closes #692.

Fix issue where aperture Quantity inputs would sometimes fail

---

.rtd-environment.yml

I don't think we need `jupyter` any longer in the RTD environment.  This should speed up the RTD builds some.
CC:  @bsipocz

Remove jupyter from RTD environment

---

docs/epsf.rst

Forget to include `origin='lower'` in the last `imshow` plot....

Fix origin in epsf docs [docs only]

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/tests/test_core.py

Remove NaNs to avoid RuntimeWarnings in find_peaks

---

CHANGES.rst
docs/background.rst
photutils/background/background_2d.py
photutils/background/core.py
photutils/detection/core.py
photutils/detection/tests/test_core.py

In `astropy.stats.SigmaClip` and `astropy.stats.sigma_clipped_stats`, the `iters` keyword was recently deprecated and renamed to `maxiters`.  This PR updates photutils function to support both the `iters` (for astropy < 3.1) and `maxiters` (for astropy >= 3.1) keywords, eliminating the deprecation warnings.
This PR replaces #718.

Update SigmaClip and sigma_clipped_stats calls for deprecated keywords

---

CHANGES.rst
docs/epsf.rst
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/tests/test_epsf.py

As discussed in #714, this PR deprecates and renames the `Star`, `Stars`, and `LinkedStars` classes to `EPSFStar`, `EPSFStars`, and `LinkedEPSFStars`, respectively.
Closes #714.

 Rename "Star" classes with EPSF prefix

---

photutils/psf/epsf.py

The smoothing kernels in the EPSF builder are custom kernels meant only for oversampling factors around 4.  This PR adds a warning if the user tries to use them with a substantially different oversampling.
Later on it would be nice to auto-generate the kernels for something more appropriate given the oversampling... If/when we do that the warnings can be removed.

Add warnings for using a bad smoothing kernel/oversampling combo

---

photutils/psf/epsf_stars.py
photutils/segmentation/core.py
photutils/utils/cutouts.py
photutils/utils/interpolation.py

Minor cleanup to use the API and namespace consistently throughout the package (everything worked here perfectly though, not using strings is only a problem when deprecating is happening in a bugfix version number).

Making deprecations API consistent

---

photutils/psf/epsf.py
photutils/psf/tests/test_epsf.py

`EPSFBuilder` will now raise a `TypeError` if a user does not input a `EPSFFitter` instance (instead of getting a cryptic error message).

Check that the input ePSF fitter is an EPSFFitter instance

---

photutils/psf/epsf.py

This PR reverses the warnings added in #715.  I spoke with Jay Anderson and the predefined smoothing kernels are not limited to oversampling factors near 4.
CC: @eteq

Remove warnings about ePSF smoothing kernels

---

photutils/detection/core.py
photutils/detection/findstars.py
photutils/detection/tests/test_core.py
photutils/detection/tests/test_findstars.py

This gives the user helpful messages for invalid input shapes or types.

Raise errors for invalid inputs to star or peak finders

---

CHANGES.rst
photutils/detection/findstars.py
photutils/detection/tests/test_findstars.py

This PR adds two new parameters to `IRAFStarFind` and `DAOStarFind` star detection classes to allow source selection/filtering by:
1. `peakmax` - maximum peak pixel value for selecting stars.
2. `brightest` - number of brightest objects to keep.
The rationale for these parameters is that `peakmax` could allow automatic exclusion of sources that reach a known saturation level of the detector and `brightest` would keep top `brightest` stars eliminating the faintest objects that could be false detections.
CC: @larrybradley

Add filtering/selection by peakmax and brightest

---

docs/aperture.rst

This PR adds ``# doctest: +SKIP`` to the ``matplotlib`` import line in ``aperture.rst``, avoiding the issue where CircleCI builds fail in testing due to parsing the import statement without previously installing the module in the test suite.

Added doctest skip to matplotlib import line in aperture.rst

---

CHANGES.rst
docs/detection.rst
photutils/detection/findstars.py
photutils/detection/tests/test_findstars.py

This PR adds a  `mask` keyword to `DAOStarFinder` and     `IRAFStarFinder` that can be used to mask regions of the input image.

Allow for masking regions in star finders

---

photutils/detection/findstars.py

This PR make output of `DAOStarFinder` and `IRAFStarFinder` consistent regardless of whether any stars have been found. This addresses the issue https://github.com/astropy/photutils/issues/757
CC: @larrybradley

Make table output of DAOStarFinder and IRAFStarFinder consistent

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/findstars.py
photutils/detection/tests/test_core.py

This PR adds column names and types to `find_peaks` output empty tables if no peaks are found.

Update find_peaks to return empty table with column names if no peaks are found

---

photutils/datasets/make.py
photutils/datasets/tests/test_make.py

For `astropy >= 3.1` use the new `pixel_shape` attribute instead of the deprecated private `_naxis[1/2]` attributes.

Do not use deprecated _naxis1/2 for astropy<3.1

---

photutils/_astropy_init.py

This one-line change prevents pytest from picking up the test function as a test. See astropy/package-template#373.
*This is an automated fix by @pllim. If this is opened in error, please close without merge.*

Prevent pytest from picking up test function as a test

---

.travis.yml
setup.cfg
setup.py

This PR adds `numpy` and `Cython` to `setup_requires` for those building the package from source.

Include setup_requires in package setup

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py

If a single aperture is input as a list into the ``aperture_photometry`` function, then the output columns will be called ``aperture_sum_0`` and ``aperture_sum_err_0`` (if errors are used).  Previously these column names did not have the trailing `_0`.
Fixes #705.

Fix aperture_photometry output for a length-1 list of apetures

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/models.py

After discussion with Jay Anderson, the EPSF pixel scale is unnecessary.  This PR deprecates the `pixel_scale` keyword in `EPSModel`, `EPSFStar`, and `EPSFBuilder`.

Deprecate ESPF pixel scale

---

.travis.yml
CHANGES.rst
photutils/__init__.py
setup.cfg

`travis` started picking up `astropy 3.1` and `2.0.9`, which caused failures because these packages are not built in conda with `numpy 1.10`.  It doesn't seem that we can currently use conda to test `numpy 1.10`.  To solve conda environment issues, this PR bumps the minimum support numpy version to 1.11.

Require numpy >= 1.11

---

photutils/datasets/make.py
photutils/datasets/tests/test_make.py
photutils/psf/tests/test_photometry.py

Changed test image creation in ``test_photometry`` to correctly create discrete pixel images, instead of evaluating the Gaussian PDF at the pixel centre. The PR adds a new function, ``make_gaussian_prf_sources_image`` which is analogous to the original ``make_gaussian_sources_image`` except it calls ``IntegratedGaussianPRF`` instead of ``Gaussian2D`` as the input model. Minor changes were made to the various tests as ``IntegratedGaussianPRF`` takes differing inputs -- ``x_mean`` becomes ``x_0``, etc.
This fixes the issue seen where fit and input fluxes were incompatible, as two differing models were being fit and producing differing results. Thus the accuracy of several ``assert_allclose`` statements could be improved with the conflict resolved.

Updated test_photometry to correctly use IntegratedGaussianPRF

---

photutils/geometry/circular_overlap.pyx
photutils/geometry/core.pxd
photutils/geometry/core.pyx
photutils/geometry/elliptical_overlap.pyx
photutils/geometry/rectangular_overlap.pyx

Fix #786
I am no Cython expert, so please think about whether this is what you need. At least I don't see any PY2 jobs in your CI, so I don't have to worry about PY2. This patch does get rid of all the language level warnings on my local installation.
p.s. While testing this patch locally, I encountered #787 failures. If the CI here pass, then they are unrelated. ~~If CI here shows the same failures, then they are indeed a side effect of setting Cython language level somehow. Only time will tell...~~ UPDATE: CI passed for this PR.

MNT: Set Cython language level for PY3

---

setup.py

Fixes an issue where an `ImportError` is raised before the warning about the package requiring python 3.5+.  Fixes #793.

Make setup.py be python 2 compatible

---

photutils/conftest.py

to the test header
This is the guinea pig counterpart from the packages side to make use of https://github.com/astropy/astropy/pull/8201
ps: @pllim - if you're happy with this I can add it to the template (with a bit more care to add a the `astropy_helpers_version` in a try/except given that packages may not yet caught up with astropy-helpers 2.0.6/3.0.1 that introduced it)

Print astropy_helpers used here rather than in astropy

---

docs/morphology.rst
photutils/conftest.py
photutils/detection/core.py
photutils/detection/tests/test_core.py
photutils/utils/tests/test_cutouts.py

This has been switched off in #608. Instead of disabling it, we can catch the warnings coming from out test suite.
Astropy currently doesn't offer infrastructure to deprecate a keyword, but ideally it should as currently we don't always issue the deprecation warning for e.g.  the usage of `subpixel`. As a workaround, I suggest to move the warning to the top of the function.

Enable raising deprecations

---

.circleci/config.yml
.travis.yml
appveyor.yml

`scikit-image 0.14.1` is broken (`_validate_lengths` bug) with `numpy >= 1.16`.   `scikit-image 0.14.2` has been released with a fix, but unfortunately it's not yet available in conda.  The PR switches to use `pip` to install the latest `scikit-image`.
This PR also removes a `pytest` restriction in circleci.

Use pip to install scikit-image>0.14.1 in CI

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_deblend.py
photutils/utils/convolution.py
photutils/utils/tests/test_convolution.py

This PR fixes an issue with source deblending that occurs specifically for ~source id=512~ sources whose id number is greater than 255 and a power of 2 when using `scikit-image >= 0.13`.
Fixes #803.

Fix corner-case deblending bug

---

CHANGES.rst
photutils/segmentation/core.py

This PR significantly improves the performance of segmentation relabeling, e.g. the `remove_labels`, `keep_labels`, and `relabel` methods.
CC:  @stsci-hack

Significantly improve performance of segmentation relabeling

---

photutils/psf/tests/test_groupstars.py

In the star group tests, `assert_array_equal` fails when comparing tables on Windows.  This PR relaxes the test constraint.  Fixes #787.
@pllim Can you please test this on your Windows machine?

Replace assert_array_equal in star group tests

---

CHANGES.rst

This makes a simple change to the changelog to put in the "empty" (i.e., don't have anything yet) sections to the changelog.
I think this is better because it makes it easier for new contributors to see where to put things.  I propose in the future the four sections get moved to whatever the new dev version is and then deleted if empty for the release version.  Am I right that there's not explicit release process docs for photutils, @larrybradley ? If I just missed it this could get added there, but I didn't see it...

Add empty sections to changelog

---

photutils/centroids/core.py

An upcoming PR in astropy.modeling will deprecate and subsequently remove the ability to combine model classes. The one case of model class combination in photutils was replaced by combining model instances.  
Please let me know if a Change log is needed.

combine instances of models instead of classes

---

CHANGES.rst
docs/grouping.rst
docs/segmentation.rst
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py
photutils/utils/colormaps.py
photutils/utils/tests/test_colormaps.py

This PR makes several improvements to `SegmentationImage` (and `Segment`):
* Adds new `background_area` attribute.
* Add new `find_index`, `find_indices`, `find_areas`, `check_label`, `keep_label`, `remove_label`, and `reassign_labels` methods.
* Adds `__repr__` and `__str__` methods.
* Fixed `outline_segments` to include segment outlines along the image boundaries.
* Renamed methods `cmap` (deprecated) to `make_cmap` and `relabel` (deprecated) to `reassign_label`.  The `reassign_label` gains a `relabel` keyword.
* The `segments` and `slices` attributes now have the same length as `labels` (i.e. no `None` placeholders for non-consecutive labels).
* Remove all old deprecated attributes and methods.
* Adds new `data_ma` attribute to `Segment` class.
Relatedly, the ``random_cmap`` …

Additions and improvements to SegmentationImage

---

photutils/isophote/geometry.py
photutils/isophote/isophote.py

This comes from work discussed in issue #802. 
In a nutshell, when profiling the code, we found  that vectorization of the `geometry.to_polar` method caused a significant performance degradation. In this PR we modify `to_polar` so it can handle scalar input quantities using scalar code, but still keeping its vectorized habilities. 
Profiling analysis indicates that the code returned to its overal performance level, similar to we had before.
Due to its own nature, the ellipse fitting algorithm as originally coded is slow. We are still investigating other approaches that involve a more in-depth vectorization of the entire algorithm, or caching of intermediate data (or both). This PR is to be taken as a stopgap solution to a pressing problem.
We tested this using both the test code provided …

Improve performance of ellipse fitting

---

photutils/detection/findstars.py

I'm using photutils as a testbed to figure out why the astropy docs is not compatible with the new numpydoc version, and apparently we had duplicate references that are now an issue.

removing duplicate references from docstrings

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/models.py
photutils/psf/tests/test_models.py

This PR gives ``FittableImageModel`` the option to accept ``oversampling`` factors that give differing values in the x and y direction, as a tuple of ``(x_oversamp, y_oversamp)``. It maintains backwards compatibility by accepting a scalar, interpreted as providing the same oversampling factors for both x and y (i.e., treating it as ``(oversampling, oversampling)``).
cc @eteq @larrybradley for comments. Forms part of a wider branch change with #815, #816 and #817 (see [here](https://github.com/astropy/photutils/pull/815#issuecomment-486709606) for more details).

Expanded FittableImageModel's oversampling factor to allow differing oversampling in x and y

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/findstars.py
photutils/detection/tests/test_core.py
photutils/detection/tests/test_findstars.py
photutils/psf/photometry.py
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py
photutils/segmentation/tests/test_detect.py
photutils/segmentation/tests/test_properties.py
photutils/utils/__init__.py
photutils/utils/exceptions.py

This PR makes the handling of cases when there are no source/peak detection consistent across the various `photutils` detection functions (i.e. star finders, local peak finder, and segmentation).  In all cases a new `NoDetectionsWarning` is issued and `None` is returned from the function.  This is an API change because previously some functions returned an empty `QTable/Table`.  Non-detections should now be checked using e.g. `if result is None: ...`.
If desired, the `NoDetectionsWarning` can be suppressed using the `warnings` package, e.g.:
```python
import warnings
from photutils import detect_sources
from photutils.utils import NoDetectionsWarning
with warnings.catch_warnings():
warnings.simplefilter('ignore', NoDetectionsWarning)
cat = detect_sources(data, ...)    # any photutils …
```

Consistent handling of cases when there are no source/peak detections

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/models.py

This pull request removes any reference to ``pixel_scale`` from ``EPSFModel``, ``EPSFBuilder``, and ``EPSFStar``, instead only using ``oversampling`` to define the relative grid sizes and ePSF pixel scale.
It is part of a larger PR refactor as part of #725 along with #816 and #817, and I leave the PR available for context and the discussions therein as to how these PRs relate to one another.
cc: @larrybradley @eteq

Removal of pixel_scale from ePSF framework

---

photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/models.py

Removed unused `AstropyDeprecationWarning` s following the removal of the ePSF `pixel_scale` in #815.
CC: @Onoddil

Remove unused imports

---

CHANGES.rst
photutils/aperture/mask.py
photutils/aperture/tests/test_mask.py

This PR fixes an issue where the `ApertureMask.cutout` method would drop the data units when `copy=True`:
```python
>>> import astropy.units as u
>>> from photutils import CircularAperture
>>> data = np.ones((11, 11))
>>> aper = CircularAperture((5, 5), r=1.)
>>> mask = aper.to_mask()[0]
>>> cutout = mask.cutout(data*u.adu, copy=True)
>>> cutout
array([[1., 1., 1.],
[1., 1., 1.],
[1., 1., 1.]])
```

Fix ApertureMask.cutout to preserve units when copy=True

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/mask.py
photutils/aperture/tests/test_aperture_photometry.py

This PR fixes a corner-case issue where aperture photometry would return NaN for non-finite data values outside the aperture but within the aperture bounding box.

Fix aperture photometry corner case for non-finite data values within the bounding box

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py

This PR fixes a corner-case issue where the `celestial_center` column (for sky apertures) would be a length-1 array containing a `SkyCoord` object instead of a length-1 `SkyCoord` object.

Fix scalar SkyCoord column in aperture_photometry table

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py
photutils/utils/_wcs_helpers.py
photutils/utils/wcs_helpers.py

This PR adds validation of the input parameters for all aperture classes using new descriptor classes.  Users will no longer get cryptic error messages for invalid parameter inputs.
The documentation for all apertures has also been updated to make it explicitly clear that apertures have a single fixed size/shape, but they can have multiple positions.
The descriptor classes made it possible to deprecate the `utils.wcs_helpers` functions, which will be removed in v0.8.
Closes #827.

Add validation of parameters for all aperture classes

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py

For naming consistency and consistency with segmentation-based properties, this PR renames the `celestial_center` column in the aperture photometry table (when using `Sky` apertures) to `sky_center`.

Rename celestial_center to sky_center

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py
photutils/psf/photometry.py

This PR deprecates inputting aperture pixels positions shaped a `2xN`.  This "feature" led to some confusion, especially for the `2x2` case where positions were interpreted as Nx2 (i.e. two rows of (x, y)).  Pixel positions now should be input as a `(x, y)` pixel position or a list or array of `(x, y)` pixel positions, e.g. `[(x1, y1), (x2, y2), (x3, y3)]`.  
This PR also adds "Examples" sections to the aperture docstrings.  Closes #790.

Deprecate inputting aperture pixel positions shaped as 2xN

---

CHANGES.rst
photutils/aperture/bounding_box.py
photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_bounding_box.py

This PR adds several improvements to the `BoundingBox` class:
* Adds a `from_float` method (previously private)
* Adds `union` and `intersection` methods
* Enables unions and intersections via the `|` and `&` operators, respectively
* Renames the `as_patch` method to `as_artist` (for consistency with the `regions` package); deprecates the `as_patch` method
Examples:
```python
>>> from photutils import BoundingBox
>>> bbox1 = BoundingBox(1, 10, 2, 20)
>>> bbox2 = BoundingBox(5, 21, 7, 32)
>>> bbox1.union(bbox2)
BoundingBox(ixmin=1, ixmax=21, iymin=2, iymax=32)
>>> bbox1 | bbox2
BoundingBox(ixmin=1, ixmax=21, iymin=2, iymax=32)
>>> bbox1.intersection(bbox2)
BoundingBox(ixmin=5, ixmax=10, iymin=7, iymax=20)
>>> bbox1 & bbox2
BoundingBox(ixmin=5, ixmax=10, iymin=7, iymax=20)
```

BoundingBox improvements

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_common.py
photutils/aperture/tests/test_aperture_photometry.py
photutils/aperture/tests/test_circle.py
photutils/aperture/tests/test_ellipse.py
photutils/aperture/tests/test_mask.py
photutils/aperture/tests/test_rectangle.py

The PR adds indexing, slicing, and iteration to non-scalar Aperture objects.  This change required the definition of "scalar" Apertures as those initialized with a single `(x, y)` position (input as a 1D, shape (2,)).  Scalar Apertures can be checked using the new `isscalar` property.
Aperture objects also now have a `shape` property.
Scalar Aperture objects now return scalar `positions` and `bounding_boxes` properties and its `to_mask` method now returns an `ApertureMask` object instead of a length-1 list containing an `ApertureMask`.  This is an API change that affects only scalar apertures.
Examples:
```python
>>> from photutils import CircularAperture
>>> pos = [(10, 10), (20, 20), (30, 30), (40, 40)]
>>> aper = CircularAperture(pos, r=3)
>>> aper
<CircularAperture([[10., 10.],
[20., …
```

Add indexing, slicing, and iteration to non-scalar Aperture objects

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_common.py

This PR is a followup to #852 to fix some docstrings, unused imports, and the `mask_area` method for scalar aperture objects.  The `mask_area` is now deprecated as the `ApertureMask` objects should be directly used.

Cleanup for scalar aperture

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/bounding_box.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_photometry.py
photutils/background/background_2d.py

The focus of this PR is mainly to simplify some aspects of the aperture implementation, mainly in the area of plotting apertures.  The Aperture `plot` method is now simplified and defined only in the `PixelAperture` base class.
This PR includes also two API changes.  The `plot` `ax` keyword is deprecated and renamed to `axes` for both the Aperture `plot` methods and the `Background2D.plot_meshes()` method.  Also Aperture `area` is now an attribute instead of a method (this is arguably a bug fix).

Aperture plotting improvements

---

docs/conf.py

These intersphinx URLS now use https instead of http.

Update intersphinx urls

---

ah_bootstrap.py

~DO NOT MERGE.~ This PR now points to the 3.2 release tag. I'll merge once this and other test PRs for that tag pass.
This PR  is part of testing the refactored astropy_helpers that will become v3.2. It should not be merged/released before a proper helpers release is done.

Update astropy-helpers to v3.2

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py
photutils/segmentation/tests/test_properties.py

This PR makes several improvements in the segmentation subpackage related to source properties, including:
* Adds `__repr__` and `__str__` methods to `SourceProperties` and `SourceCatalog`
* Adds `slices`, `indices`, and `filtered_data_cutout_ma` attributes to `SourceProperties`
* Deprecates the `values` and `coords` attributes in `SourceProperties`
* Deprecates the (unused) `mask_value` keyword in `make_source_mask`
A new perimeter algorithm also replaces the previous one, which depended on `scikit-image`.
This PR also adds more robust validation of `SourceProperties` inputs and improves the test coverage of the segmentation subpackage.

Improvements for segmentation-based properties

---

CHANGES.rst
docs/morphology.rst
photutils/segmentation/properties.py
photutils/segmentation/tests/test_properties.py

This PR includes several improvements to source properties, including:
* Significantly improved the performance of `background_at_centroid` in `SourceCatalog`
* The default table output columns are now defined in a publicly-accessible variable (`photutils.segmentation.properties.DEFAULT_COLUMNS`)
* The `bbox` property now returns a `BoundingBox` instance
* The `xmin/ymin` and `xmax/ymax` properties are deprecated with the replacements having a `bbox_` prefix (e.g.`bbox_xmin`)
* The `orientation` property is now returned as a `Quantity` instance in units of degrees.

Improvements for source properties

---

CHANGES.rst
docs/segmentation.rst
photutils/morphology/non_parametric.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_properties.py

This PR adds the `gini` source property to segmentation-based photometry.

Add Gini coefficient as source property

---

docs/morphology.rst
docs/psf.rst

These doc tests do not require `skimage`.

Remove skimage from several doctest-requires

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py

This pull request allows ``centroid_com`` to be used on grids with oversampled pixel indices, returning a centre of mass on the original pixel scale (e.g., a 100x100 pixel grid with ``oversampling=4`` would have a centre of 12.5, not 50).
It also includes a new centroiding method, ``centroid_epsf``, based on the methodology laid out in Anderson & King (2000) for centroiding ePSFs based on their symmetries.
It is part of a larger PR refactor as part of #725 along with #815 and #817, and I leave the PR available for context and the discussions therein as to how these PRs relate to one another. In particular, this PR laids down the groundwork for #817 in which the ePSF framework changes the way it handles oversampled and undersampled grid pixel indices, with necessary changes to the …

Extended Centroid Functionality to Handle Oversampled Grids

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py

This PR adds support for `NDData` input with its `uncertainty` attribute set to a `StdDevUncertainty` to input errors to `aperture_photometry`.  To accomplish this, the `@support_nddata` decorator was removed.  The `units` keyword in `aperture_photometry` was also deprecated because its primary purpose was to support the `@support_nddata` decorator.  Instead `Quantity` `data` and `error` objects should be explicitly input (with the same units) if one wants units.

Support NDData with StdDevUncertainty in aperture_photometry

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/core.py
photutils/aperture/tests/test_aperture_photometry.py

This PR deprecates `PrimaryHDU`, `ImageHDU`, and `HDUList` inputs to `aperture_photometry` as part of continuing cleanup of the API.

Deprecate HDU and HDUList inputs to aperture photometry

---

CHANGES.rst
photutils/utils/convolution.py
photutils/utils/tests/test_convolution.py

This PR fixes a bug where `filter_data` would drop the units for if the input data was a `Quantity` object.

Fix filter_data to preserve units

---

.travis.yml
photutils/segmentation/tests/test_properties.py

The travis tests with optional dependencies disabled was actually installing some optional dependencies via `PIP_DEPENDENCIES`.  I expect that travis test to now fail due to a bug in a test that requires scipy.  Once I see that indeed this test fails, then I'll add a commit here to fix the bad test.

Fix travis test with optional dependencies disabled

---

CHANGES.rst
docs/epsf.rst
docs/isophote.rst
docs/psf.rst
photutils/background/tests/test_core.py
photutils/datasets/make.py
photutils/isophote/tests/make_test_data.py
photutils/isophote/tests/test_ellipse.py
photutils/psf/tests/test_photometry.py
photutils/segmentation/detect.py

This PR renames (and deprecates) the `type` keyword in `make_noise_image` to `distribution`.  `type` is a protected word in Python.

Rename type keyword to distribution in make_noise_image

---

CITATION.rst
docs/citation.rst
docs/contributing.rst
docs/getting_started.rst
docs/index.rst
docs/install.rst
docs/license.rst
docs/overview.rst
docs/pixel_conventions.rst

This PR updates the main doc pages.  In particular there are new doc pages for reporting issues and contributing, pixel coordinate conventions, the license, and citing photutils.  The main page is much cleaner now.
This PR also bumps the minimum required version of some of the optional dependencies.

Update main doc pages

---

docs/epsf.rst

This PR updates the ePSF-docs to explicitly exclude stars that cannot be cut out because they are too close to the image boundaries.  This prevents a warning from being raised while building the docs.

Update ePSF-building docs to explicitly exclude border stars

---

CHANGES.rst
photutils/psf/epsf_stars.py
photutils/psf/tests/test_epsf_stars.py

This PR fixes a bug in the `EPSFStar` `register_epsf` and `compute_residual_image` computations.
Many thanks to @SunilSimha and @mattabern for reporting this issue.
Fixes #805.

Fix bug in EPSFStar residual image

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR fixes `SegmentationImage.is_consecutive` to return `True` only if the labels are consecutive *and* start with label=1.

Fix is_consecutive to check starting label

---

photutils/aperture/attributes.py
photutils/aperture/bounding_box.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/mask.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_common.py

This PR mainly simplifies aperture property validation by changing the descriptor classes to use the `instance.__dict__`.  It also moves the aperture `_shape_params` to a class-level tuple instead of an instance-level tuple.  It also includes a few minor implementation changes.

 Simplify aperture property validation

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py

This PR fixes the bug in the dev version of `deblend_sources` reported by @stephenmwilkins in #880.
While investigating and testing this bug, I discovered two other bugs that could be triggered:
* Sources could be deblended too much when `connectivity=8`.
* The `contrast` parameter had little effect if the original segment contained three or more sources.
Both are also fixed in this PR.
Closes #880 .
A separate PR will be forthcoming that improves the performance of source deblending.

Fix deblend_sources

---

CHANGES.rst
photutils/utils/interpolation.py
photutils/utils/tests/test_interpolation.py

This PR removes the long-deprecated `interpolate_masked_data` function and deprecates `mask_to_mirrored_num`.

Clean up of interpolation utils

---

CHANGES.rst
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_photometry.py

This PR simplifies the aperture bounding box calculations by consolidating the code in the `PixelAperture` base class.  The `bounding_boxes` attribute for pixel-based apertures is now deprecated and has been renamed `bbox` for consistency across the `photutils` package.

Simplify aperture bounding box calculation

---

CHANGES.rst
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/photometry.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_photometry.py
photutils/datasets/make.py
photutils/detection/core.py
photutils/detection/tests/test_core.py
photutils/psf/epsf_stars.py
photutils/psf/sandbox.py
photutils/segmentation/properties.py
photutils/utils/_wcs_helpers.py
photutils/utils/wcs_helpers.py

This PR implements support for the [Astropy unified WCS APE](http://docs.astropy.org/en/stable/wcs/wcsapi.html).
This required removing the `mode` keyword in the ``to_sky`` and ``to_pixel`` aperture methods.  All WCS transforms now include distortions (if present).

Allow WCS objects that support the shared WCS interface

---

photutils/datasets/make.py
photutils/isophote/tests/make_test_data.py
photutils/segmentation/core.py
photutils/utils/check_random_state.py
photutils/utils/colormaps.py

The numpy `RandomState` documentation is at `numpy.random.mtrand.RandomState`.

Update numpy RandomState intersphinx link

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

`aperture_radius` is used to compute initial estimates for the fluxes of sources.  If initial flux guesses are not input to the photometry class via the ``init_guesses`` keyword, then `aperture_radius` must be set.  Currently, a cryptic error is raised if that's not the case.  This PR raises a `ValueError` with a helpful message if `aperture_radius` is needed and it is not set or cannot be determined from the input `psf_model`.
This issue was reported in #728, #804, and #849 (and via other channels).
Closes #728.

Raise ValueError in PSF fitting if aperture_radius is not set

---

docs/morphology.rst
docs/segmentation.rst

Minor fix to narrative docs to ensure correct units for source `orientation`.

Update orientation units in narrative docs

---

CHANGES.rst
photutils/segmentation/core.py

With this change, cached (lazy) properties can now be reset in `SegmentationImage` subclasses.

 Simplify reseting lazy properties in SegmentationImage

---

CHANGES.rst
docs/background.rst
docs/segmentation.rst
photutils/detection/core.py
photutils/detection/tests/test_core.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

`make_source_mask` returns a bool array of all `False` if there are no detections.
Fixes https://github.com/astropy/photutils/issues/904.
This PR also renames the `snr` (deprecated) keyword to `nsigma` is `make_source_mask` and `detect_threshold`.

Fix make_source_mask for no detections

---

CHANGES.rst
photutils/aperture/photometry.py
photutils/detection/findstars.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/properties.py
photutils/utils/convolution.py
photutils/utils/misc.py
photutils/utils/stats.py
photutils/utils/tests/test_convolution.py
photutils/utils/tests/test_stats.py

The deprecated functions are used internally by `photutils`, but should not have been part of the public API.

Deprecate util functions

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/models.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_epsf_stars.py

This pull request, building upon the changes in #815 and #816, reworks the framework of the ``EPSFModel`` (and ``EPSFBuilder`` & ``EPSFStar``) to handle the oversampled pixel grid scale while correctly treating the ePSF pixels as being convolved with the original, undersampled pixel grid. This avoids the issue where flux is dependent on ``oversampling``, now properly handling the normalization of the grid by normalizing on every Nth ePSF pixel (for ``oversamping=N``).
There are also a few minor changes to ``EPSFBuilder``, changing the flow of ``_build_epsf_step`` to more closely match the algorithm detailed by Anderson & King (2000).
It is part of a larger PR refactor as part of #725 along with #815 and #816, and I leave the PR available for context and the discussions therein as to how …

Fixes to ePSF Framework: Normalization Handling & ePSF Building

---

photutils/psf/epsf.py
photutils/psf/models.py

This does a couple of straightforward documentation tweaks mainly in the PSF and ePSF realm.  Specifically, mainly it's focusing on getting rid of "default is X" statements in the docstrings.
My reasoning here is that the default is already specified in what the default actually *is*, and both the `?` tool in ipython/jupyter and the sphinx docs display that pretty clearly.  So philisophically I think it's best not to state it in the docstring because that's asking for trouble if someone changes the default in the code but not the docstring.
cc @Onoddil @larrybradley

Docstring tweaks in psf/epsf

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py

This PR improves the performance of source deblending.  For large (e.g. ~4k x 4k) images with a few thousand sources, it's about ~40-50% faster.   For several hundred sources in smaller images (~1k x 1k), it's about 25% faster.  More performance improvements will come in a later PR.

Improve performance of source deblending

---

photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/tests/test_epsf.py

Misc PEP8 cleanup in psf subpackage

---

.travis.yml

The `astropy-dev` test is failing due to upstream changes in `astropy.modeling`.
This PR also moves the Windows tests earlier for overall faster completion.

Temporarily allow astropy-dev travis test failures

---

photutils/utils/interpolation.py
photutils/utils/tests/test_interpolation.py

Fix so that `AstropyDeprecationWarning` isn't raised in testing for this deprecated function.

Fix deprecation warnings in tests

---

.readthedocs.yml
docs/rtd_requirements.txt

RTD builds started failing late last week due to excessive memory consumption.  @bsipocz suggested this possible fix.

Pin MPL to <3.1 for RTD builds

---

CHANGES.rst
photutils/isophote/sample.py
photutils/isophote/tests/test_ellipse.py
photutils/isophote/tests/test_model.py

This was uncovered when fixing issue #920 . 
The fix may generate slightly different results in a few cases, but mostly it increases stability in low SNR areas on the image, typically at the outskirts of galaxies. The algorithm is able to keep iterating on wider ellipses than before.
Tests were verified and modified accordingly The fix was also verified on the notebooks in `photutils-datasets`, for which there is also PR #17

Fix radial gradient computation in `ellipse`

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/models.py

Mostly minor miscellaneous code fixes and cleanup in the psf subpackage.  Also, this PR adds some missing changelog entries from  #817 due to API changes and backwards-incompatible changes.
The one major fix is in https://github.com/astropy/photutils/commit/2c9cbdf55ad83f0a91864ccd8cde677880d9e974 which fixes the logic for defining the EPSF centroids.  The first `centroid_func` call was overwritten by a subsequent call, thus the `shift_val` keyword value had no effect.
CC: @Onoddil, @eteq, @bsipocz

PSF fixes and code cleanup

---

photutils/isophote/tests/test_fitter.py

This test (with the remote M51 data) started failing after the new gradient computation was added in #934.

Fix ellipse fitting test for new gradient computation

---

photutils/psf/models.py

A very small pull request to tweak a bugfix for a bug found and fixed in #937, where in `EPSFModel._initial_norm` the `flux` assignment incorrectly failed to be returned, rather than being an unused variable (cf. the equivalent function in `FittableImageModel` [here](https://github.com/astropy/photutils/blob/59a85c05dcf4735da7a13bdcefb95c154e0a3600/photutils/psf/models.py#L162-L171)), as was implemented in the above PR.

Fix to EPSFModel initial_norm, where flux failed to be returned

---

.travis.yml
photutils/isophote/tests/test_ellipse.py

The travis test for remote data was using the `--remote-data=astropy` flag, which apparently stopped pulling in the remote data.  Using simply `--remote-data` correctly pulls in the remote data.
This is the reason why #938 was not caught by travis.

Update travis remote-data test

---

CHANGES.rst
photutils/psf/photometry.py

Very small pull request to fix the case where `self._residual_image` is never initialised for the case where `bkg_estimator=None` in `IterativelySubtractedPSFPhotometry`.

Fix to IterativelySubtractedPSFPhotometry where residual_image was not set for non-background subtracted images

---

.pep8speaks.yml

Attempt to fix #944 . Not sure how to test.
Looking at https://github.com/OrkoHunter/pep8speaks/blob/master/.pep8speaks.yml , I am not sure why `max-line-length` is not working, so I copy over the one thing that appears missing here compared to that one.

TST: Update flake8 setting for pep8speaks

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

``output_cols`` is added as an additional input parameter to ``BasicPSFPhotometry``, ``IterativelySubtractedPSFPhotometry`` and ``DAOPhotPSFPhotometry`` allowing for the inclusion of a list of strings of parameters derived by the ``finder`` instance. If not ``None`` these additional columns are then passed back to the user in the output table. 
For example, if sharpness and roundness are parameters of interest from ``DAOStarFinder`` then ``output_cols = ['sharpness', 'roundness1', 'roundness2']`` would return the values calculated during the finder process, along with such values as ``x_fit``, etc.
Closes #680

Added the ability to pass additional column names to PSFPhotometry classes to be returned to the user

---

.circleci/config.yml

… in the doctestplus plugin
Revert when pytest-doctestplus 0.4 is released.

Pinning pytest version to workaround 5.1 issue

---

.travis.yml
CHANGES.rst
docs/install.rst
setup.cfg

The next version of `photutils` will require `python >= 3.6` and `astropy >= 3.2`.  Updating the astropy dependency allows us to take advantage of significant performance improvements (starting with v3.1) and the latest version (i.e fixes) of the shared interface for WCS (APE14).  `astropy 4.0` will be released in the fall.

 Update minimum python and astropy dependencies

---

docs/conf.py
docs/high-level_API.rst
docs/index.rst
docs/test_function.rst
photutils/__init__.py

The `high-level_API` doc page relies on *not* having `__all__` defined in the package init.  Here I remove that page, since it's not really necessary.

Remove high level API doc page

---

.pep8speaks.yml

In a way that will not make @eteq unhappy. :wink: 
(I would go with the default 79 if I can have my way though!)

Reduce max line length in pep8speak

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_deblend.py

This PR fixes #959, which was caused by a re-labeling bug introduced in v0.7 in `deblend_sources`.
Many thanks to @thriveth for reporting the original bug and providing the data and a MWE that enabled me to debug this issue!

Fix a labeling bug in deblend_sources

---

photutils/psf/tests/test_photometry.py

This PR fixes a PSF photometry test that was raising a `FutureWarning` from elementwise `==` comparison.  The test started failing with astropy dev (https://github.com/astropy/astropy/pull/8506) because `FutureWarning` is now treated as an exception.

Fix FutureWarning in PSF photometry test

---

CHANGES.rst
photutils/segmentation/properties.py

This PR fixes two issues in `source_properties` related to `Quantity` objects with astropy dev and numpy 1.17.2.  The code was previously using `np.where` (with 3 arguments) with both `ndarray` and `Quantity` inputs.  In the `Quantity` case, the units are no longer silently stripped, thus raising an `UnitConversionError`.  This PR explicitly strips the units before calling `np.where`.
This PR also explicitly strips the units on `Quantity` inputs to `np.linalg.eigvals` to prevent a new warning.
These are pre-emptive bug fixes for the next astropy release.

Explicitly strip units in source properties

---

photutils/conftest.py

This should fix the failing astropy-dev build.

Using new pytest-astropy-header plugin directly

---

photutils/aperture/tests/test_photometry.py
photutils/background/background_2d.py
photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/datasets/make.py
photutils/detection/findstars.py
photutils/detection/tests/test_core.py
photutils/isophote/isophote.py
photutils/morphology/core.py
photutils/morphology/tests/test_core.py
photutils/psf/groupstars.py
photutils/psf/photometry.py
photutils/psf/sandbox.py
photutils/psf/tests/test_groupstars.py
photutils/segmentation/core.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_detect.py
photutils/segmentation/tests/test_properties.py
photutils/utils/interpolation.py
photutils/utils/tests/test_convolution.py
photutils/utils/tests/test_interpolation.py

These numpy dtypes are simply aliases for the Python builtin dtypes and should be avoided.

Replace numpy dtypes with Python versions

---

CHANGES.rst
docs/epsf.rst
photutils/psf/epsf.py
photutils/psf/tests/test_epsf.py

This PR fixes the bug in `EPSFBuilder` in its v0.7 update. The bug, as best I pinned it down, is due to a subtle interaction between a "halfway" algorithm update to the original Anderson & King (2000) paper, from its form in v0.6 which was, as I understand it, implemented via discussions with Jay, unbeknownst to me at the time. I have subsequently found what I believe to be a citable version of the updates (and referenced them accordingly), and thus re-aligned the ePSF algorithm with its updated version. Ironically if I had made more code changes instead of fewer, and further aligned the code with the workflow of AK00 it would likely have been ok, but there we are...!
The main differences should therefore lie in the removal of the `residual smooth and recenter` loop of AK00, to follow …

Fix to ePSF algorithm changes in v0.7

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

Currently the `_do_photometry` loop of `IterativelySubtractedPSFPhotometry` assumes that if no sources are detected then the returned variable will be `None`. If a user provides a custom finder which instead returns an empty `Table` object, this won't be caught by the while loop and will error. This PR makes a simple fix to this, adding a check for a zero-length variable returned by `self.finder` in addition to a `None` variable.
This PR blocks #740, which needs this PR merged before one of its tests will pass.

Fix to IterativelySubtractedPSFPhotometry failing when Finder does not return None if no sources are detected

---

photutils/datasets/make.py

It's educational to use np.radians instead of dividing and multipliing.

* np.pi / 180. -> np.radians

---

.travis.yml

I'm trying to add  python 3.8 to be tested. It's possible that there are still issues with dependencies, so I would not be surprised if it is failing.
Also, noticed that there are currently 5 jobs in the initial tests. The 5. doesn't really need to be in that group, and I feel the docs build, along with passing with astropy-dev (as we don't allow that to fail) is better suited to be run once the basic tests pass.
(Double checking the last ~10 failing builds job3 is very much the dominant failure, with a few that are failing only with the astropy-dev job).

Using python 3.8 for one of the jobs, and adding one more stage

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py

Minor PR to fix a typo where `y_shiftidx` used `oversampling[0]`, rather than `oversampling[1]` for deriving the grid point index distance to compute the difference and gradients at; includes verification test (fails on master, passes in this branch).
Closes #996

Fix to centroid_epsf, where y_shiftidx was using the x-axis oversampling for its calculation

---

photutils/centroids/core.py
photutils/centroids/tests/test_core.py

Fixes `centroid_1dg` to prevent `numpy-dev` deprecations where object arrays are no long created automatically for lists with unequal numbers of elements.

Fix centroid_1dg to prevent deprecations with numpy-dev

---

CITATION
CITATION.rst
MANIFEST.in
docs/citation.rst

Replaces `CITATION` symlink with a file containing a URL to citation file.

Replace CITATION symlink

---

setup.cfg

`pytest 4.6` is the oldest currently-supported version.

Bump minimum pytest version

---

photutils/aperture/tests/test_mask.py

aperture mask test: assert almost equal

---

CHANGES.rst
photutils/utils/errors.py
photutils/utils/tests/test_errors.py

This PR allows the `effective_gain` parameter in `calc_total_error` to be zero (or contain zeros in an array).  For pixels where `effective_gain` is zero, the source Poisson noise component is not included in the total error array.  Thanks to @dancoe for discovering this issue.

Allow effective_gain to be zero in calc_total_error

---

CHANGES.rst
photutils/segmentation/properties.py
photutils/segmentation/tests/test_properties.py
photutils/utils/_wcs_helpers.py

This PR fixes a bug where `source_properties` would fail with unitless `gwcs.wcs.WCS` objects.  For unitless `gwcs` objects, the x, y input to `pixel_to_world` must not be `Quantity` objects.

Fix source_properties for unitless gwcs objects

---

docs/install.rst

- This is about installing photutils, not astropy.
- photutils itself comes as a wheel and does not require a compiler for most operating systems.
[skip ci]

two fixes in install.rst

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/tests/test_epsf.py

This was implemented by @Onoddil in #974 but because it was a new feature we decided to "hide" it for 0.7.2.  This PR just brings it back for 0.8.
Note I'm starting it as a "draft" because it needs to be rebased on master after #974 is in.

Restore flux_residual_sigclip

---

CHANGES.rst
photutils/psf/models.py

This addresses #1011 
This adds the method `_compute_local_model` to `photutils.psf.models.GriddedPSFModel`.   There was really no change to the code, just splitting the previous `evaluate()` method into two separate methods.
This allows the user to generate a FittableImageModel for the PSF around some (x,y).  Currently, every time `evaluate()` is called, the gridded model is bilinearly interpolated, then turned into a FittableImageModel, which is then interpolated/evaluated onto the image grid.  This is very slow when doing something like fitting an object iteratively.  Splitting the evaluate method into two parts allows for the FittableImageModel to be computed just once, and then that output model to be evaluated for any small changes in position.  This shouldn't be much different in …

Added method to compute local model from GriddedPSFModel (issue #1011)

---

photutils/psf/photometry.py

Minor PR to remove an unused keyword `param_tab` from the `_do_photometry` function in `IterativelySubtractedPSFPhotometry`.
Closes #993

Removed param_tab as keyword from IterativelySubtractedPSFPhotometry

---

photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/models.py
photutils/psf/photometry.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_models.py

These numpy dtypes are simply aliases for the Python builtin dtypes and should be avoided.  Followup to #982.

Replace numpy dtypes in psf subpackage

---

docs/aperture.rst
docs/background.rst
docs/centroids.rst
docs/detection.rst
docs/segmentation.rst

`matplotlib 3.2` changed the default `imshow` interpolation from `"nearest"` to `"antialiased"` (https://github.com/matplotlib/matplotlib/pull/13724). This breaking change causes "rainbow" outlines when plotting segmentation images (integer data).  This PR explicitly sets the `interpolation="nearest"` to restore the correct plots.
interpolation='nearest':
interpolation='antialiased':

 Add interpolation="nearest" for imshow plots in documentation

---

photutils/datasets/make.py
photutils/isophote/tests/make_test_data.py
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/utils/check_random_state.py
photutils/utils/colormaps.py

The scikit-image watershed function was moved from morphology to segmentation.    Note that the import from segmentation has worked since at least 0.14 (i.e., all scikit-image dependent versions), so there's no need to have an alternate import for older scikit-image versions.  The import from segmentation was deprecated in `skimage 0.17.2`.
This fixes the failing travis-ci test, which was triggered by the deprecation warning.

Update scikit-image watershed import

---

CHANGES.rst
photutils/isophote/model.py

This PR fixes the issue #1038 (``build_ellipse_model``). 
Only two lines are added
```python
else:
break
```
and moved a one-line coment just above this ``else``. (Tests passed on my computer, just for confirmation)
Fix #1038

Break the while loop outside the image [Fixes #1038]

---

photutils/psf/tests/test_sandbox.py

This test creates an array of shape (999, 999, 11, 11), requiring 922 MiB.  This can cause failures with some CI services.

Remove legacy PRF test due to excessive memory usage

---

photutils/detection/tests/test_core.py
photutils/detection/tests/test_findstars.py

The check for the warning category is unnecessary since only that warning type is caught in the context manager.  Somehow this test started failing in travis-ci, but I cannot reproduce the failure.

Remove unnecessary check for warning class

---

CHANGES.rst
docs/background.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This PR adds `coverage_mask` and `fill_value` keyword options to `Background2D`.  `coverage_mask` is used for blank areas of the image without coverage (e.g., due to an image mosaic or image rotation).  The `coverage_mask` is applied to the output `background` and `background_rms` maps -- pixels where `coverage_mask` is `True` get set to `fill_value` in these output images.
This PR also requires that all `Background2D` keywords options be input as keywords and not as positional arguments.  That is a small breaking API change.

Add coverage_mask keyword to Background2D

---

CHANGES.rst
photutils/psf/utils.py

numpy 0.20dev now raises `ValueError: cannot convert float NaN to integer` when attempting to assign to np.nan in an integer array.  This PR fixes `subtract_psf` by changing the input array dtype to float.

Change dtype to float for nan fill_value

---

.pep8speaks.yml
CHANGES.rst
docs/centroids.rst
photutils/centroids/__init__.py
photutils/centroids/core.py
photutils/centroids/gaussian.py
photutils/centroids/tests/test_core.py
photutils/centroids/tests/test_gaussian.py

This PR makes some changes in the `centroids` subpackage:
* Moves `centroid_1dg`, `centroid_2dg`, `gaussian1d_moments`, `fit_2dgaussian`, and `GaussianConst2D` to a new`photutils.centroids.gaussian` module
* Deprecates `fit_2dgaussian` and `GaussianConst2D`
* Adds `centroid_sources` to the narrative docs
* Code cleanup/PEP8
I preserved the git history of both `core.py` and `gaussian.py`.

Deprecate fit_2dgaussian and GaussianConst2D

---

CHANGES.rst
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_photometry.py

This PR adds keywords to ellipse and rectangle annulus apertures to allow the user to input both the inner semimajor and semiminor axes (for ellipse) or both the inner width and height (for rectangles).

Add user to input both parameters for ellipse and rectangle inner annuli

---

docs/psf.rst

Fix #557 
I guess they can also be removed from https://github.com/astropy/photutils-datasets/ but I'll leave that up to the `photutils` maintainers to decide.

MNT: Remove outdated PSF notebooks

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/models.py
photutils/psf/tests/test_epsf.py

This PR removes the constraint of excluding odd oversampling factors in `EPSFBuilder`.  This PR also improves the normalization calculation within a given radius (and also allows for both even and odd oversampling).
Example Jupyter notebook of odd oversampling:
https://gist.github.com/larrybradley/1affa63921b1582e65286ce595d53e1c
Comparison using a simulated HST/WFC3 F160W image (from the narrative docs):
Oversampling=4:
Oversampling=5:

Allow odd oversampling factors in EPSFBuilder

---

.travis.yml
CHANGES.rst
docs/install.rst
photutils/aperture/tests/test_photometry.py
photutils/background/background_2d.py
photutils/detection/findstars.py
setup.cfg
tox.ini

This PR bumps the minimum supported version of Numpy from 1.16 to 1.17.  This mirrors the minimum supported numpy version for `astropy 4.2`.

MNT: Drop Numpy 1.16

---

CHANGES.rst
docs/epsf.rst
docs/grouping.rst
docs/isophote.rst
docs/psf.rst
docs/segmentation.rst
photutils/aperture/bounding_box.py
photutils/background/tests/test_core.py
photutils/datasets/make.py
photutils/datasets/tests/test_make.py
photutils/isophote/tests/make_test_data.py
photutils/isophote/tests/test_ellipse.py
photutils/isophote/tests/test_fitter.py
photutils/isophote/tests/test_harmonics.py
photutils/isophote/tests/test_isophote.py
photutils/isophote/tests/test_model.py
photutils/isophote/tests/test_sample.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_photometry.py
photutils/segmentation/core.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_core.py
photutils/utils/check_random_state.py
photutils/utils/colormaps.py
photutils/utils/interpolation.py
photutils/utils/tests/test_colormaps.py
photutils/utils/tests/test_interpolation.py
photutils/utils/tests/test_random_state.py

This PR addresses the fact that [numpy's `RandomState` is now considered legacy](https://numpy.org/doc/stable/reference/random/legacy.html) (also see https://numpy.org/doc/stable/reference/random/new-or-different.html#new-or-different).  As a result, the `check_random_state` function is deprecated.  The `random_state` keyword in several functions is now deprecated and was renamed to `seed`.

Replace RandomState with default Generator

---

.travis.yml
CHANGES.rst
docs/install.rst
setup.cfg
tox.ini

`gwcs 0.12` (an optional `photutils` dependency) requires `astropy >= 4.0`.
`specutils` also requires `astropy >= 4.0`.

Bump minimum astropy to 4.0

---

docs/install.rst

All installs should be done using `pip install`, not `python setup.py install`.

Update dev install instructions

---

.bandit.yaml
.travis.yml
tox.ini

This PR adds the python security analysis tool `bandit` (https://bandit.readthedocs.io/en/latest/) as a `tox` test environment.  It also adds `bandit` to the `travis` CI test matrix.

Add bandit to tox and add as a CI job

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_circle.py

I updated the `photutils.aperture.core.PixelAperture.plot` method so it returns the Patches to be used later. For example, I wanted to compare the apertures found with `DAOStarFind` and `IRAFStarFind` and add a legend. Having the patches allows me to create a legend to identify the apertures. 
Here is an example of what I wanted to do:
And here is the code that generated the code:
```python
...
iraf_patches = iraf_apertures.plot(color='blue', lw=1.5, alpha=0.5, axes=ax)
dao_patches = dao_apertures.plot(color='red', lw='1.5', alpha=0.5, axes=ax)
ax.legend([iraf_patches[0], dao_patches[0]], ['IRAFStarFind', 'DAOStarFind'],
framealpha=1)
...
```
I added some tests to `photutils.aperture.tests/test_circle.py` and updated the docstring of the updated function. Please, let me know if you need …

Update `CircularAperture.plot()` to return patches

---

photutils/isophote/fitter.py

In the below issue thread, I mentioned an infinite loop that can rarely occur when using photutils for elliptical isophote analysis.
https://github.com/astropy/photutils/issues/707
Changing the log message from info to a warning allows users to catch it using ```warnings.filterwarnings("error")```.

Changed "info" log to warning to allow for infinte loop catching.

---

README.rst

Travis migrated to `travis-ci.com`.

Fix travis link in README

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This PR fixes a bug I discovered (while reviewing #1103) where `Background2D` with `BkgIDWInterpolator` would give incorrect results for the full-sized interpolated background image.

Fix bug in Background2D when using BkgIDWInterpolator

---

CHANGES.rst
photutils/background/background_2d.py

Using numpy.indices is a factor of 25 faster than the itertools.product method. This is a dramatic improvement for the Background2D execution time when analyzing large (2048x2048) images.

modify _data_coords calculation

---

photutils/background/background_2d.py

This PR removes the private `_calc_coordinates` method.  The mesh x/y positions are now calculated as (private) cached lazy properties and the `data_coords` calculation was moved to the `BkgIDWInterpolator`, the only place where it is needed.
This PR also fixes an issue where if the input `mask=None` and the image size in each dimension is an integer multiple of the corresponding `box_size` dimension,  a masked array was created with `mask=None`.  Many thanks to @jdermigny for reporting that in #1105 
Fixes #1105.

Refactor Background2D to improve performance with default interpolator

---

docs/grouping.rst
photutils/aperture/photometry.py
photutils/datasets/make.py
photutils/isophote/isophote.py

Photutils 1.1 will require python >3.7, so we can replace `OrderedDict` with `dict`.  `dict` insertion-order is preserved in python 3.7+.

Replace OrderedDict with dict

---

.github/workflows/ci_tests.yml
.github/workflows/cron_tests.yml

The linkcheck sometimes fails due to remote server failures.

Move linkcheck to weekly cron job

---

CHANGES.rst
photutils/segmentation/properties.py

As reported in #1122, if the numerator or denominator of the Kron radius calculation were negative, then the Kron radius would be negative.  With a negative Kron radius, the Kron flux raises an exception because the aperture radius must be >= 0.
This PR fixes this issue.  If either the numerator or denominator <= 0 in the Kron radius formula, then ``np.nan`` will be returned. In this case, the Kron aperture will be defined as a circular aperture with a radius equal to ``kron_params[2]``. If ``kron_params[2] <= 0``, then the Kron aperture will be `None` and the Kron flux will be ``np.nan``.

Fix negative Kron radius

---

CHANGES.rst
photutils/background/background_2d.py

This PR fixes the failing tests reported in #1136 caused by changes to `scipy.ndimage.zoom` in scipy v1.6.0.
Fixes #1136.

Change BkgZoomInterpolator default method to constant

---

CHANGES.rst
photutils/isophote/isophote.py
photutils/isophote/tests/test_harmonics.py

The upper harmonics and related errors are corrected. (`scipy.optimize.leastsq()` returns the inverse of Hessian matrix) 
Was previously discussed in #1004 and #1008.

correcting upper harmonics (and related errors)

---

CHANGES.rst
photutils/isophote/geometry.py
photutils/isophote/sample.py

I discovered an unrelated bug while testing https://github.com/astropy/photutils/pull/1089 with https://github.com/astropy/photutils-datasets/blob/master/notebooks/isophote/isophote_example4.ipynb.  PR #922 added a `fixed_parameters` parameter to the `EllipseSample.update()` method, but it did not do so as a keyword parameter with a default value of not fixing any parameters (breaking old existing code in the process). This PR defines the default parameter.

Add missing default fixed params in EllipseSample

---

photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

Hi, I found that when calling SegmentationImage.remove_border_labels(relabel=True) on a segmentation image where all segments lie within the specified border, resulting in zero segments remaining, the relabelling throws a ValueError. Example code:
```
data = [[1, 1, 0, 0, 4, 4],
[0, 0, 0, 0, 0, 4],
[0, 0, 0, 0, 0, 0],
[7, 0, 0, 0, 0, 5],
[7, 7, 0, 5, 5, 5],
[7, 7, 0, 0, 5, 5]]
segm = SegmentationImage(data)
segm.remove_border_labels(border_width=1, relabel=True)
```
Result:
```
Traceback (most recent call last):
File "test_photutils_segmentation.py", line 11, in <module>
segm.remove_border_labels(border_width=1, relabel=True)
File "/Users/davidgrant/Work/Code/ResearchScience/photutils/photutils/segmentation/core.py", line 1058, in remove_border_labels
relabel=relabel)
File …
```

Fix segmentation bug: remove_border_labels and relabel=True when no remaining segments

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

All of the following are now allowed inputs to `Background2D`:
```python
data = np.random.randn(100, 100)
data = np.random.randn(100, 100) << u.ct
data = CCDData(np.random.randn(100, 100), unit=u.ct)
data = NDData(np.random.randn(100, 100), unit=u.ct)
data = NDData(np.random.randn(100, 100), unit=None)
bkg = Background2D(data, 3)
```
The output `bkg.background`, `bkg.background_rms`, `bkg.background_median`, `bkg.background_rms_median` will be `Quantity` objects if the input has units.
Closes #696.

Allow Quantity, NDData, and CCDData input to Background2D

---

CHANGES.rst
photutils/isophote/isophote.py
photutils/isophote/tests/test_isophote.py

I wanted to be able to export to_table all, or some of the properties of an isophote_list. Thus, I:
Added an option key_properties to ``to_table()`` in the ``IsophoteList`` class. 
This allows to select which properties to be exported.'
Added a new function ``get_names`` in the ``IsophoteList`` class. 
It prints the IsophoteList key_properties that can be used with ``to_table()``
Added a test_to_table() test function in test_isophote.py
I run the pytest and all seemed fine. 
Old functionality of ``to_table()`` is preserved.

Add new feature to_table

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/tests/test_epsf.py

As per several issues raised, but most recently #969, there remains an outstanding issue in some cases with ePSF building. It seems that the issue now lies in the recentering function used during the process, which was left as `centroid_epsf` after #974 fixed some issues with the original bug fix of #817.
Thus this PR is a minor one to change the default `recentering_func` within `EPSFBuilder` to `centroid_com`, reverting the implementation of `centroid_epsf`. This seems to solve the issue raised in #969, and likely closes several related issues at the same time.
The change makes our unit tests converge a little bit slower than they did with `centroid_epsf`, so I tweaked a few parameters in the various `EPSFBuilder` calls to pass again. I also wasn't sure whether this was an API change or …

Change Default EPSFBuilder Recentering Function

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

In some instances (still unclear why), the astropy fitter will not return a parameter covariance matrix, despite the fitter supporting it.  In those cases where the returned `fit_info` dictionary contains a `param_cov` key set the value of `None`, the PSF-photometry function returns `flux_unc`, `x_0_unc`, and `y_0_unc` columns in the output table with garbage values.  This PR fixes that check.  If `param_cov` is `None`, then no uncertainty values will be returned in the output table.

Fix invalid PSF fit uncertainties when fitter does not return a covariance matrix

---

CHANGES.rst
photutils/centroids/gaussian.py
photutils/centroids/tests/test_gaussian.py

This PR removes the deprecated `fit_2dgaussian` function and `GaussianConst2D` class.

Remove centroid deprecations

---

photutils/psf/epsf.py

Minor improvement to avoid warning message by reordering comparisons

don't cause warning when using custom smoothing kernel in EPSFBuilder

---

photutils/aperture/core.py

Apertures have a method `area` that gives the exact area of the aperture. This can be used, e.g., to calculate the [local background](https://photutils.readthedocs.io/en/stable/aperture.html#local-background-subtraction) for aperture photometry. However this is the wrong number to use if the aperture is on the edge of the image. We need a method that returns the *overlapping* area between the aperture mask and the data. I have attempted to implement that in `area_overlap`. I wasn't sure if this was the right place to put it, so feedback is welcome.

add area_overlap method for apertures

---

docs/aperture.rst

The aperture docs incorrectly were referring to `SourceProperties.source_sum_err`.

Fix typo in aperture docs

---

docs/aperture.rst

Removes the dead IRAF link that is causing the CI `linkcheck` test to fail.  Also moves the SourceExtractor link to inline.

Update links in aperture docs

---

CHANGES.rst
photutils/aperture/bounding_box.py
photutils/aperture/mask.py
photutils/aperture/tests/test_bounding_box.py
photutils/aperture/tests/test_mask.py
photutils/segmentation/tests/test_core.py

This PR also deprecates the `BoundingBox.slices` attribute in favor of this new method, which is better for partial overlaps.

Add get_overlap_slices method to BoundingBox

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/mask.py
photutils/aperture/tests/test_mask.py

This PR  adds a `get_values` method to `ApertureMask` that returns a 1D array of mask-weighted values.  It also fixes separate bugs with the `fill_value` keyword in the `multiply` and `cutout` methods.

Add ApertureMask get_values method

---

CHANGES.rst
photutils/aperture/rectangle.py
photutils/aperture/tests/test_mask.py

This PR fixes a bug where `RectangularAnnulus` instances with a non-default `h_in` parameter would produce an incorrect `ApertureMask`.

Fix RectangularAnnulus ApertureMask for non-default h_in

---

CHANGES.rst
photutils/segmentation/properties.py
photutils/segmentation/tests/test_properties.py

This PR fixes two issues with `local_background`.  First, an exception is no longer issued if `Quantity` data inputs are used with `source_properties`/`SourceProperties`.  Second, this PR fixes the `local_background` calculation for sources near the image edges.

Fix SourceProperties local background

---

CHANGES.rst
photutils/segmentation/properties.py
photutils/segmentation/tests/test_properties.py

Fixes the `kron_radius` to be `np.nan` for completely masked sources.  Previously an exception was raised.

Fix kron radius for sources that are completely masked

---

CHANGES.rst
photutils/aperture/mask.py
photutils/aperture/tests/test_mask.py
tox.ini

This new method gets a tuple of slices for the overlapping part of the aperture mask and a 2D array.

Add get_overlap_slices to ApertureMask

---

docs/conf.py
tox.ini

Current `linkcheck` failures are caused by a Sphinx update and an outdated `iraf.net` certificate.

Fix linkcheck tests

---

photutils/detection/findstars.py

Followup to #1175 to fix issue with `jwst` pipeline.

Issue deprecation warnings about moved star finder kernel class

---

CHANGES.rst
photutils/detection/__init__.py
photutils/detection/findstars.py
photutils/detection/starfinder.py
photutils/detection/tests/test_starfinder.py

This PR adds a `StarFinder` class to detect stars with a user-defined kernel.  The algorithm follows the `IRAFStarFinder` class where the properties are calculated using 2D image moments.

Add a StarFinder class

---

photutils/aperture/core.py
photutils/aperture/photometry.py

The PR adds a note to `aperture_photometry` for rectangular-aperture photometry.  `RectangularAperture` and `RectangularAnnulus` photometry with the "exact" method uses a subpixel approximation by subdividing each data pixel by a factor of 1024 (``subpixels = 32``). For rectangular aperture widths and heights in the range from 2 to 100 pixels, this subpixel approximation gives results typically within 0.001 percent or better of the exact value.

Remove warning message with rectangular apertures

---

photutils/psf/epsf_stars.py
photutils/psf/tests/test_epsf_stars.py

I've encountered an issue where I couldn't return EPSFStars through multiprocessing, due to the custom `__getattr__` causing infinite recursion with `multiprocessing.ForkingPickler`. It does not seem to be an issue with the regular pickle module due to some difference of how it tries to find `__getstate__` which I don't really understand...
The included test is probably not something worthwhile to keep, but should reproduce the problem.
BTW are these tiny PRs fine or should I wait until/if I get more "content"?

Make EPSFStars usable with multiprocessing

---

CHANGES.rst
photutils/psf/epsf_stars.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_epsf_stars.py
photutils/psf/tests/test_models.py

Slicing `EPSFStars` now returns a new `EPSFStars` instance instead of a list.
Closes #968

Fix slicing EPSFStars

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/properties.py
photutils/segmentation/tests/test_catalog.py
photutils/segmentation/tests/test_core.py

This PR adds a `bbox` attribute to `SegmentationImage`.  It also removes the ability to slice a `Segmentation`.  Instead, one should slice `SegmentationImage.segments`.

Add bbox attribute to SegmentationImage

---

CITATION.rst
CONTRIBUTING.rst
README.rst
docs/dev/releasing.rst
docs/isophote.rst
photutils/datasets/load.py

This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
This is part of #1176

MNT: Replace master with main

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

After running into https://github.com/astropy/photutils/issues/845 I tried to fix it generically (https://github.com/krachyon/photutils/tree/parameter_name_matching) by comparing the parameter names of the psf model and matching them to those that should be output in `_model_params2table()` but ran into the issue that sometimes a compound model seems to have the parameters combined by adding a postfix (param_i->param_i_j) or by incrementing a existing postfix(param_i -> param_j). More Details on that train of thought in the comment in `photometry.py`
I decided it's not really worth trying to predict that behaviour and came up with this pretty hacky way to handle both. I'm not sure if this is something merge worthy, but for now it seems to solve the issue on my end. 
I guess the proper …

formerly hacky fix for incorrect model names trying to be accessed if more than two stars in group

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

Added a fallback ``aperture_radius`` to BasicPSFPhotometry and IterativelySubtractedPSFPhotometry for non-Gaussian PSF models that do not have either a sigma or FWHM attribute. If neither are found, routines fall back to the smaller of the two ``fitshape`` lengths, using the available (e)PSF model pixels to compute an aperture radius flux. Closes #728

Add fallback aperture_radius to psf photometry

---

CHANGES.rst
photutils/__init__.py

This is the first step in the direction of requiring the subpackage name for all imports.  This PR starts with the `centroids` and `morphology` subpackges.  Other subpackages may come later.

Deprecate top-level imports from centroids and morphology subpackages

---

CHANGES.rst
docs/whats_new/1.1.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

The FHWM is estimated as the circularized FWHM of the 2D Gaussian function that has the same second-order central moments as the source.  `fwhm = 2 sqrt(ln(2) * (a^2 + b^2))`, where a and b are the 1-sigma semimajor and semiminor lengths, respectively.

Add FWHM property to SourceCatalog

---

CHANGES.rst
docs/whats_new/1.1.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

The `fluxfrac_radius` method can be used to estimate the half-light radius.

Add fluxfrac_radius method to SourceCatalog

---

CHANGES.rst
photutils/detection/findstars.py

Also adds the missing changelog entries for the deprecation of the `photutils.detection.findstars.py` module.

Fix the DAOStarFinder import deprecation message

---

photutils/_astropy_init.py

In https://github.com/astropy/astropy/issues/11497, astropy has deprecated `update_default_config` and `ConfigurationMissingWarning` to make the configuration file optional. This PR removes these dependencies.

Remove update_default_config and ConfigurationMissingWarning

---

.github/workflows/ci_tests.yml
.readthedocs.yml

RTD is now configured to build on PRs.  This PR updates the RTD config to fail on warnings  and updates python to ~3.9~ 3.8.
EDIT:  This PR also removes `build_docs` from the GitHub Actions CI tests.

Update RTD config

---

photutils/detection/peakfinder.py

The deprecated `subpixel` keyword was removed two years ago in https://github.com/astropy/photutils/pull/835. While the functionality of the keyword was removed along with its documentation, unfortunately the keyword was not removed from the function signature.  This PR fixes that issue.

Remove deprecated subpixel keyword in find_peaks

---

CHANGES.rst
photutils/segmentation/_utils.py
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py
photutils/segmentation/tests/test_utils.py

This PR fixes a corner-case issue where `apermask_method = 'correct'` would ignore the user-input `mask` when calculating Kron-related properties.

Fix SourceCatalog aperture masking

---

setup.cfg

Sphinx 4 starting giving warnings about duplicate references, e.g. https://github.com/astropy/astropy/issues/11723.
This PR is to temporarily pin the max version of Sphinx until we figure out how to fix the failure permanently.

Pin Sphinx<4

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/mask.py
photutils/aperture/tests/test_circle.py
photutils/aperture/tests/test_mask.py

This PR changes  `ApertureMask.get_values()` to return an empty array if there is no overlap with the data.

Return an empty array for no aperture overlap

---

CHANGES.rst
photutils/aperture/bounding_box.py
photutils/aperture/core.py
photutils/aperture/tests/test_bounding_box.py

This PR removes the deprecated ``BoundingBox.slices`` and ``PixelAperture.bounding_boxes`` attributes.

Remove PixelAperture and BoundingBox deprecations

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

`SourceCatalog` `segment` arrays should never have units.

Fix SourceCatalog segment units

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_photometry.py
photutils/detection/peakfinder.py
photutils/segmentation/properties.py
photutils/utils/_wcs_helpers.py

This PR fixes an issue where the `SkyAperture.to_pixel` and `PixelAperture.to_sky` methods did not work for `gwcs` objects.  
Fixes #1219.

Fix pixel/sky aperture conversions for GWCS

---

CHANGES.rst
photutils/utils/interpolation.py
photutils/utils/tests/test_interpolation.py

This PR fixes an issue in ``ShepardIDWInterpolator`` to allow its initialization with scalar data values and coordinate arrays having more than one dimension.
Examples:
```python
>>> from photutils.utils import ShepardIDWInterpolator as idw
>>> value = 10.
>>> f = idw(2, value)  # 1D
>>> f = idw([[1, 2]], value)  # 2D
>>> f = idw([[7, 4, 1]], value)  # 3D
```
Fixes #1224

Fix ShepardIDWInterpolator for scalar data values

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This PR fixes an issue where ``Background2D`` could fail when using the ``'pad'`` edge method.
It also updates the `Background2D` `exclude_percentile` docs.

Fix Background2D bug with 'pad' edge method

---

CHANGES.rst
photutils/background/background_2d.py

This PR adds a `markersize` keyword to the `Background2D.plot_meshes()` method.

Add markersize keyword to Background2D plot_meshes method

---

CHANGES.rst
photutils/background/core.py
photutils/background/tests/test_core.py

This PR adds `__repr__` to all background classes.  Example:
```python
>>> from photutils.background import MeanBackground
>>> bkg = MeanBackground()
>>> bkg
<MeanBackground(sigma_clip=SigmaClip(sigma=3.0, sigma_lower=3.0, sigma_upper=3.0, maxiters=10, cenfunc='median', stdfunc='std', grow=False))>
```

Add __repr__ to background classes

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_circle.py

This PR adds a `mask` keyword to the aperture `area_overlap` method to account for any masked pixels in the data.

Add mask keyword to aperture area_overlap method

---

CHANGES.rst
photutils/datasets/make.py
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/peakfinder.py
photutils/detection/starfinder.py
photutils/isophote/isophote.py
photutils/psf/photometry.py
photutils/psf/utils.py
photutils/segmentation/catalog.py
photutils/utils/_misc.py

This PR adds package version metadata to all output tables and also uses `QTable` for all output tables instead of `Table`.  The version metadata is stored as a dictionary keyed on the package name with the values being the package version.

Use QTable with version metadata

---

CHANGES.rst
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py

This PR adds a `xycoords` keyword to `DAOStarFinder` and `IRAFStarFinder`.  If `xycoords` are input, then the source-detection algorithm is skipped and they are used directly.
`xycoords` are input as a `Nx2` numpy.ndarray.  If x and y are stored in a table, then one would input `xycoords` as e.g., `xycoords = np.transpose((tbl['x_peak'], tbl['y_peak']))`.
This is an alternate solution to #1231.  It was made possible by the refactoring completed in #1245.
Closes #1231.
CC: @stsci-hack

Add xycoords keyword to DAOStarFinder and IRAFStarFinder

---

photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py

This PR adds descriptions for the aperture attributes (defined using descriptor classes) that is used for attribute documentation.

Add docstrings for aperture attributes

---

CHANGES.rst
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

With regards to issue #1163 I'm now reasonably sure that the model to fit the EPSF to a star in EPSF photometry needs to be inverted. 
This seemed to produce sensible results in multiple trials on simulated and real images, while the original shift produces results indistinguishable from just running the respective starfinder on the image.

Apply correct shift in prepare_psf_model

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

when doing something like
```python
result_table = photometry(image)
result_table['x'] = result_table['x_fit']
result_table['y'] = result_table['y_fit']
result_table['flux'] = result_table['flux_fit']
second_result = other_photometry(image, result_table)
```
a bunch of errors occur due to the re-naming of columns by `Table.hstack`, trying to create existing column `group_id` and caring about the order of the `id` column. These changes should enable the `Photometry`-classes to update tables with the fields already defined.

Make result of psf-photometry re-usable as initial guess

---

CHANGES.rst
photutils/detection/starfinder.py

This PR renames the ``StarFinder`` ``label`` column to ``id`` for consistency with the other star finder classes.

Rename StarFinder label column

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

New features
* new `copy` method
* new `kron_photometry` method
* new `add_extra_property`, `remove_extra_property`, and `remove_extra_properties` methods and `extra_properties` attribute
* new `name` and `overwrite` keywords to `circular_photometry`
* improved `fluxfrac_radius` for cases where the source flux doesn't monotonically increase with increasing radius.
Fixes
* `detection_catalog` centroids are used to calculate `circular_aperture`, `circular_photometry`, and `fluxfrac_radius`
* Units are applied to `circular_photometry` output
* `circular_photometry` returns scalar values for scalar catalog
* `fluxfrac_radius` returns a `Quantity` with pixel units

SourceCatalog improvements

---

CHANGES.rst
docs/segmentation.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py
photutils/utils/_misc.py

This PR adds the following `SourceCatalog` features
* new `rename_extra_property` method
* new `meta` and `properties` attributes
* new `make_kron_apertures` method
* new `plot_circular_apertures` and `plot_kron_apertures` methods
* `to_table` meta now includes a field for date/time
Fixes:
* `detection_catalog` is now indexed/sliced when `SourceCatalog` is indexes/sliced
* ``circular_photometry`` now returns NaN for completely-masked sources
* ``kron_flux`` is always NaN for sources where ``kron_radius`` is NaN
* ``fluxfrac_radius`` now returns NaN if ``kron_flux`` is zero
API changes:
* Renamed the ``SourceCatalog`` ``circular_aperture`` method to ``make_circular_apertures``. The old name is deprecated.
* ``kron_params`` keyword must have a minimum circular radius that is greater than …

SourceCatalog fixes and improvements

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/utils/_round.py

This PR makes a number of improvements to the centroid functions:
* Extra keyword arguments can be input to ``centroid_sources`` that are then passed on to the ``centroid_func`` if supported.  This feature was requested in #1270.
*  A ``ValueError`` is now raised in ``centroid_sources`` if the input ``xpos`` or ``ypos`` is outside of the input ``data``.
* A ``ValueError`` is now raised in ``centroid_quadratic`` if the input``xpeak`` or ``ypeak`` is outside of the input ``data``.
*  NaNs are now returned from ``centroid_sources`` where the centroid failed. This is usually due to a ``box_size`` that is too small when using a fitting-based centroid function.
Closes #1270

Centroid improvements

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py

This is a followup fix to PR #1276, where the `mask` keyword in `centroid_sources` was not passed to the `centroid_func`.

Fix centroid_sources mask

---

.circleci/config.yml
.github/workflows/ci_tests.yml
CHANGES.rst
docs/install.rst
setup.cfg
tox.ini

This PR drops support for Python 3.7 and updates the following minimum dependencies:
* numpy 1.18+
* Astropy 5.0+
* Matplotlib 3.1+
* scikit-image 0.15.0+
* gwcs 0.16.0+

Drop support for Python 3.7 and update minimum dependencies

---

photutils/background/tests/test_background_2d.py
photutils/centroids/tests/test_core.py
photutils/centroids/tests/test_gaussian.py
photutils/conftest.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py
photutils/detection/tests/test_peakfinder.py
photutils/detection/tests/test_starfinder.py
photutils/isophote/tests/test_ellipse.py
photutils/isophote/tests/test_model.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/segmentation/tests/test_deblend.py
photutils/segmentation/tests/test_detect.py
photutils/utils/tests/test_convolution.py
photutils/utils/tests/test_errors.py
setup.cfg

This pull request is to remove soon to be deprecated code; also see astropy/astropy#12633 .
* MNT: Stop using deprecated astropy.tests stuff
* TST: Turn unhandled warnings into exceptions.

MNT: Stop using deprecated astropy.tests stuff

---

photutils/isophote/tests/test_model.py

This is a followup to https://github.com/astropy/photutils/pull/1281, where the `RuntimeWarning` only *sometimes* occurs.  In particular, this test started failing on `ubuntu-latest, py38-test-alldeps` because the `RuntimeWarning` did not occur.  Here, we simply ignore the `RuntimeWarning` whether there is one or not.

Handle test warning that only sometimes occurs

---

CHANGES.rst
photutils/aperture/_photometry_utils.py
photutils/aperture/tests/test_photometry.py
photutils/segmentation/catalog.py

This PR fixes a bug in ``aperture_photometry`` where an error was not raised if the data and error arrays have different units.

Fix unit check in aperture_photometry

---

CHANGES.rst
docs/background.rst
photutils/background/background_2d.py

This PR does two things:
* adds a `alpha` keyword to `Background2D.plot_meshes` that applies to both the markers and boxes
* updated the background subtraction example in the narrative docs for the rotated image

Background improvements

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This PR fixes a bug in `Background2D` where using the `pad` edge method would result in incorrect image padding if only one of the axes needed padding.
Fixes #1289

Fix Background2D pad bug

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_circle.py
photutils/aperture/tests/test_ellipse.py
photutils/aperture/tests/test_photometry.py
photutils/aperture/tests/test_rectangle.py

A `ValueError` is now raised if non-positive sizes are input to sky-based apertures.
This PR also renames two of the descriptor classes used for validation, but those classes are not part of the public API.

Raise ValueError for non-positive sizes

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py

This PR fixes an issue in `centroid_sources` where if `error`, `xpeak`, or `ypeak` was set to `None` an error would be raised.
Fixes #1294.

Fix centroid_sources for keywords set to None

---

docs/aperture.rst

I want to be able to reference to this page by intersphinx.

DOC: Add ref to Aperture Photometry top level

---

photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py

This PR updates the descriptors (used as aperture attribute validators) to use `__set_name__` (PEP-487).

Update attribute descriptors to use __set_name__

---

CHANGES.rst
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_aperture_common.py
photutils/aperture/tests/test_circle.py
photutils/aperture/tests/test_ellipse.py
photutils/aperture/tests/test_rectangle.py

This PR adds a `copy` method to `Aperture` and adds the ability to compare `Aperture` objects for equality (or inequality). This is especially useful for testing.

Add Aperture copy method and ability to compare Aperture objects

---

CHANGES.rst
photutils/aperture/bounding_box.py
photutils/aperture/tests/test_bounding_box.py

The PR updates the ``BoundingBox.plot()`` method to now return a ``matplotlib.patches.Patch`` object.  This is useful, for example, when creating plot legends.

Return a matplotlib Patch from BoundingBox plot

---

photutils/psf/__init__.py
setup.cfg

Starting with `Sphinx 4.0`, when building the docs warnings were issued about duplicate objects for the `psf.matching` functions.  `psf.__init__` is importing all from `psf.matching`, and I think Sphinx is getting confused by seeing these tools both as `psf.<tool>` and `psf.matching.<tool>`.
I don't know if this is the best solution, but explicitly removing the `psf.matching` tools from `psf.__all__` seems to solve the issue.
Closes #1238

Fix Sphinx warnings about duplicate objects

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/attributes.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_ellipse.py
photutils/aperture/tests/test_rectangle.py

The PR allows the ``theta`` keyword for ``EllipticalAperture``, ``EllipticalAnnulus``,  ``RectangularAperture``, and ``RectangularEllipse`` to be an Astropy ``Angle`` or ``Quantity`` in angular units.

Allow ellipse and rectangle pixel aperture to take Quantity rotation angle

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_photometry.py

This PR deprecates:
* Inputting ``PixelAperture`` positions as an Astropy ``Quantity`` in pixel units
* Inputting ``SkyAperture`` shape parameters as an Astropy ``Quantity`` in pixel units

Deprecating pixel Quantity inputs in apertures

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

This PR fixes a `SourceCatalog` bug reported in #1302 where a ``UFuncTypeError`` would be raised if the input ``data`` has an integer ``dtype``.
Fixes #1302.

Fix SourceCatalog UFuncTypeError if data has integer dtype

---

CHANGES.rst
photutils/aperture/stats.py
photutils/aperture/tests/test_stats.py

This PR allows `SkyAperture` to be input to `ApertureStats` if a `wcs` object is also input.  Follow up to #1309.

Allow SkyAperture inputs to ApertureStats

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/stats.py
photutils/aperture/tests/test_stats.py

This PR adds a `local_bkg` keyword to `ApertureStats` to allow for local background subtraction within each aperture position. Followup to #1309.

Add local_bkg keyword to ApertureStats

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py

This PR fixes a bug in ``centroid_quadratic`` where inputting a mask would alter the input data array.

Fix centroid_quadratic when mask is input

---

CHANGES.rst
photutils/aperture/stats.py

This PR fixes the performance and memory issue in `ApertureStats` for large arrays as reported in #1316.
Closes #1316.

Improve ApertureStats performance for large arrays

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_catalog.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py

This PR make the following changes to `SegmentationImage`:
* performance improvements when initializing with large datasets
* performance improvements for the `areas` and `background_area` attributes
* adds a `cmap` attribute defining a default mpl colormap
* a `TypeError` is now raised if the input data does not have integer type
* allows initialization with an array of all zeros

SegmentationImage improvements

---

CHANGES.rst
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

This PR  deprecates the ``mask_value`` keyword in ``detect_threshold`` (use the ``mask`` keyword instead) and the  ``filter_fwhm`` and ``filter_size`` keywords in ``make_source_mask`` (use the ``kernel`` keyword instead).

Deprecate segmentation detect keywords

---

photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py

Pixel apertures currently inherit `to_mask` from the mask `Mixin` classes, but the `to_mask` is also defined as an abstract method in the `PixelAperture` base class.  In this PR, `to_mask` is explicitly added to point to the `to_mask` methods of the `Mixin` classes.  Note that everything currently works given the python class MRO, but this PR makes it explicit.

Explicitly add to_mask method to pixel apertures

---

CHANGES.rst
docs/whats_new/1.1.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_deblend.py

Removes the deprecated ``circular_aperture`` method from ``SourceCatalog`.  Use `make_circular_apertures` instead.

Remove deprecated circular_aperture method from SourceCatalog

---

.readthedocs.yml

`bottleneck` wheels are now available for Python 3.10.

Update RTD config to use Python 3.10

---

CHANGES.rst
docs/segmentation.rst
photutils/segmentation/__init__.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/finder.py
photutils/segmentation/tests/test_finder.py

This PR adds a `SourceFinder` class, which is a convenience class combining ``detect_sources`` and ``deblend_sources``.  This PR also updates and improves the segmentation narrative docs.

Add SourceFinder class

---

CHANGES.rst
photutils/segmentation/_utils.py
photutils/segmentation/catalog.py
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py

Inputing an `ndarray` is no longer allowed.
This PR also makes several small improvements to the segmentation docstrings.

Require a SegmentationImage be input to deblend_sources

---

CHANGES.rst
photutils/psf/photometry.py

This PR fixes a bug where the `mask` was not passed to the `nstar` method in `IterativelySubtractedPSFPhotometry`.  Followup to #1350.

Apply mask to IterativelySubtractedPSFPhotometry

---

photutils/utils/tests/test_convolution.py

Astropy kernels are now always normalized (as advertised).

Remove test due to upstream astropy changes

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/core.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py
photutils/utils/_stats.py

The `sigma_clip` keyword accepts an `astropy.stats.SigmaClip` object, which has more options than using the `sigclip_*` keywords.

Add sigma_clip keyword in detect_threshold and deprecate sigclip_* keywords

---

CHANGES.rst
docs/background.rst
photutils/segmentation/core.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py
photutils/utils/__init__.py
photutils/utils/footprints.py
photutils/utils/tests/test_footprints.py

This PR also deprecates the standalone `make_source_mask` method in favor of `SegmentationImage.make_source_mask`.
It also add the `circular_footprint` convenience function.  These footprints can be input into `SegmentationImage.make_source_mask` to dilate the sources when creating the mask.

Add SegmentationImage.make_source_mask

---

CHANGES.rst
photutils/psf/sandbox.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_sandbox.py
photutils/psf/tests/test_utils.py

This PR deprecates the `DiscretePRF` and `Reproject` classes.  These classes are part of the PSF "sandbox" module as experimental tools.  For discrete PSFs, one may use the `EPSFModel` or `GriddedPSFModel` classes.

Deprecate DiscretePRF and Reproject classes

---

CHANGES.rst
photutils/aperture/tests/test_photometry.py
photutils/background/background_2d.py
photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/models.py
photutils/psf/tests/test_epsf.py
photutils/segmentation/utils.py
photutils/utils/_parameters.py
photutils/utils/tests/test_parameters.py

This PR uses the new `as_pair` helper function for more robust size-related parameter validation.
This PR also changes the `oversampling` keyword axes order when input as a tuple so as to not violate the principle of least surprise.  This a breaking changing, but using different oversampling for each axis is not a common use case.

Improve "size" parameter validation

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py
photutils/utils/colormaps.py
photutils/utils/tests/test_colormaps.py

With this PR, the colormap returned from `make_random_cmap` will have colors in RGBA format.  Also, the `SegmentationImage.make_cmap` `background_color` keyword can now be input in `#rrggbbaa` format (for RGBA) colors.

Return colormap with RGBA colors from make_random_cmap

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR adds an `imshow` convenience method for plotting a`SegmentationImage`.

Add imshow method to SegmentationImage

---

photutils/segmentation/core.py

This PR updates the labels checking from computing the segmentation image minimum to computing the labels themselves (and storing them).  This ultimately saves time because the labels will need to be computed later in order to use most `SegmentationImage` features.

Compute labels when setting SegmentationImage data

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

This PR deprecates the `kernel` keyword in ``detect_sources`` and ``deblend_sources``. Instead, if filtering is desired, input a convolved image directly into the ``data`` parameter.

Deprecate kernel keyword

---

CHANGES.rst
photutils/psf/epsf.py

If `tqdm` is not installed, the progress bar will fall back to the previous (simpler) text-based version.

Use optional tqdm progress_bar in EPSFBuilder

---

CHANGES.rst
docs/segmentation.rst
photutils/segmentation/deblend.py
photutils/segmentation/finder.py
photutils/segmentation/tests/test_deblend.py

This PR adds a `nproc` keyword to `deblend_sources` and `SourceFinder` to optionally enable multiprocessing when deblending sources.

Add ability to use multiprocessing in source deblender

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/finder.py
photutils/segmentation/tests/test_deblend.py

If the mode in ``deblend_sources`` is "exponential" or "sinh" and there are too many potential deblended sources within a given source (watershed markers), a warning will be raised and the mode will be changed to "linear".  This sometimes occurs, especially with "exponential" mode (where there are many thresholds at low detection levels), where the detection threshold and/or `npixels` was too low, resulting in many noise spikes being found.  That in turn causes the watershed algorithm to run for a long time for non-real sources.

Switch to linear deblending mode if there are too many watershed markers

---

photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/centroids/tests/test_gaussian.py

This could occur if the (masked) array sums to zero.

Prevent zero-divide runtime error in centroid_com

---

.gitignore
CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py
photutils/utils/__init__.py
photutils/utils/cutouts.py
photutils/utils/tests/test_cutouts.py

This PR adds a `CutoutImage` class for making cutouts.
This PR also adds a `make_cutouts` method to `SourceCatalog`, which can be used to make custom-shaped cutout images for each source in the catalog.
The PR also changes the `SourceCatalog` `make_circular_apertures` and `make_kron_apertures` methods to return an aperture object instead of a list with one aperture for scalar `SourceCatalog` objects.

Add CutoutImage class and SourceCatalog.make_cutouts method

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/psf/epsf.py
photutils/psf/models.py

This PR:
* Deprecates the ``oversampling`` keyword in ``centroid_com``. 
* Removes the unused  ``shift_val`` keyword in ``EPSFBuilder`` and ``EPSFModel``.  This keyword value was not used in the code.
* Fixed the oversampling axis order (followup to #1358).

Deprecate oversampling keyword in centroid_com

---

CHANGES.rst
photutils/psf/epsf.py
photutils/psf/tests/test_epsf.py

This PR renames the ``flux_residual_sigclip`` keyword (now deprecated) to ``sigma_clip`` in ``EPSFBuilder`` for consistency with other functions in `photutils`.

Rename flux_residual_sigclip to sigma_clip

---

CHANGES.rst
photutils/psf/epsf.py

The ``EPSFBuilder`` progress bar now requires that the optional ``tqdm`` package be installed.

Require tqdm for EPSFBuilder progress bar

---

CHANGES.rst
docs/segmentation.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

This PR fixes the ability to set a minimum unscaled Kron radius in `SourceCatalog`.  
It also adds an optional third item to `kron_params` to allow the user to define a minimum circular radius.
Finally, the ``SourceCatalog`` ``kron_radius`` is now set to the minimum Kron radius (the second element of ``kron_params``) if the data or radially weighted data sum to zero.

Fix the ability to set a minimum unscaled Kron radius

---

CHANGES.rst
photutils/psf/epsf.py

The star's coordinates were not being printed in the warning message.

Fix warning message in EPSFFitter

---

photutils/isophote/tests/test_regression.py

Now that `remote_data_strict = true`

Mark test that requires remote data

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/circle.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/tests/test_photometry.py
photutils/centroids/core.py
photutils/centroids/tests/test_core.py
photutils/psf/epsf.py
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

This PR removes various deprecations from the `aperture`, `centroids`, `psf`, and `segmentation` subpackages.

Remove deprecations

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_circle.py

This PR fixes a bug in the `PixelAperture.area_overlap` method so that it no longer returns values with the same units as the input data.

Fix `PixelAperture` `area_overlap` unit bug

---

CHANGES.rst
photutils/aperture/stats.py
photutils/aperture/tests/test_stats.py

This PR allows astropy `NDData` objects to be input to the ``ApertureStats`` class.

Allow NDData input to ApertureStats

---

photutils/aperture/ellipse.py
photutils/aperture/rectangle.py

Passing the `angle` parameter to matplotlib patches is deprecated in mpl 3.6.  This PR inputs the angle as keyword in patch objects.

Use keyword angle for mpl patches

---

tox.ini

Minor changes, I think only the first one is controversial, I opted into building the dev version, but it's probably not worth the added extra minutes:
- scikit-image doesn't seem to have nightly wheels. We can either build a dev version or only test releases.
- mpl has nightly
- pip freeze once we installed everything
- duplicate conftest, so CI will show the custom test header

CI: minor fixes to tox config

---

CHANGES.rst
photutils/utils/cutouts.py
photutils/utils/tests/test_cutouts.py

This PR adds a `xyorigin` attribute to `CutoutImage`.  This is useful when plotting apertures (or bounding boxes) on cutout images.

Add xyorigin attribute to CutoutImage

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

The PR adds the ``mode`` and ``fill_value`` keywords to the ``SourceCatalog`` ``make_cutouts`` method.

Add keywords to SourceCatalog make_cutouts

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

This PR fixes an issue in the ``SourceCatalog`` ``kron_photometry``, ``make_kron_apertures``, and ``plot_kron_apertures`` methods where the input minimum Kron and circular radii would not be applied. Instead the instance-level minima would always be used.  This does not affect the `kron_flux` and `kron_fluxerr` values, which are based on the instance-level `kron_params`.
It also fixes an issue where the ``SourceCatalog`` ``plot_kron_apertures`` method would raise an error for a scalar ``SourceCatalog``.

Fix Kron photometry for custom minimum Kron or circular radius

---

setup.cfg

With `sphinx` >= 5.2, the sidebar started getting filled with every method and attribute.  They overfill the horizontal size of the sidebar.

Pin sphinx to <5.2

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py
photutils/segmentation/utils.py

This PR introduces an API change to `SourceCatalog` when `detection_cat` is input.  If ``detection_cat`` is input to ``SourceCatalog``, then the detection catalog source centroids and morphological/shape properties will be returned instead of calculating them from the input data. Also, if ``detection_cat`` is input, then the input ``wcs``, ``apermask_method``, and ``kron_params`` keywords will be ignored.  This makes the output catalog self-consistent and removes any potential confusion about which centroids and elliptical shape parameters are used for the circular and elliptical Kron aperture photometry (even though this was previously documented).
This PR also adds a ``segment_area`` source property and ``wcs``, ``localbkg_width``, ``apermask_method``, and ``kron_params``  attributes to …

Use detection catalog centroids and shape parameters in SourceCatalog

---

setup.cfg

The emerging convention for licenses is the [SPDX License List](https://spdx.org/licenses/).

Used SPDX license expression in project metadata

---

.github/workflows/ci_tests.yml
.github/workflows/cron_tests.yml

Python 3.11 wheels are now available for `scikit-image` and `scikit-learn`.

Add py311 to CI tests

---

.github/workflows/publish.yml

...to build and publish Python 3.11 wheels.

Add Python 3.11 to publish workflow

---

CHANGES.rst
docs/segmentation.rst
photutils/aperture/bounding_box.py
photutils/aperture/core.py
photutils/background/background_2d.py
photutils/segmentation/catalog.py
photutils/segmentation/core.py

This PR deprecates the `axes` keywords in favor of `ax` for consistency with other packages (e.g., `scipy`, `pandas`, `astropy`, `regions`).

Deprecate axes keywords in favor of ax

---

CHANGES.rst
photutils/__init__.py
photutils/segmentation/core.py

This PR requires that importing tools from all subpackages now requires including the subpackage name, e.g., `from photutils.aperture import CircularAperture` instead of `from photutils import CircularAperture`.  The photutils package has significantly grown over time with many different subpackages.  Requiring the using the user to explicitly use the subpackage name improves the import performance and is common in other packages (e.g. `scipy`, `astropy`, `specutils`, etc.).  It also prevents namespace confusion (e.g., #1065).
Closes #1065.
Followup to #1190.

Deprecate top level imports

---

photutils/aperture/stats.py
photutils/segmentation/catalog.py

This PR updates the `ApertureStats` and `SourceCatalog` centroid docstrings to note that the centroid is calculated as the center of mass of the unmasked pixels within the aperture or segment.
Closes #1435

Update ApertureStats and SourceCatalog centroid docstrings

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/bounding_box.py
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py

This PR improves the performance of aperture photometry by 10-25% (depending on the number of aperture positions) by caching certain aperture properties using `lazyproperty`.

Improve performance of aperture photometry

---

CHANGES.rst
docs/install.rst
setup.cfg

Following NEP 29, the minimum required Numpy is now 1.20.
Optional dependencies:
- matplotlib 3.3.0+
- scikit-image 0.18.0+
- scikit-learn 1.0+

Update minimum versions of dependencies

---

pyproject.toml
setup.cfg

This PR pins the  `setuptools` max version to workaround https://github.com/numpy/numpy/issues/22623 and https://github.com/pypa/setuptools/issues/3693 until a more permanent solution for `astropy` can be found.

Pin setuptools max version

---

pyproject.toml
setup.cfg

`astropy` has replaced `numpy.ctypeslib` with `cython`, which resolves the convolution input error with setuptools 65.6.0. This PR removes the version pin set in #1443.
Closes: #1444

Remove setuptools pin

---

CHANGES.rst
photutils/datasets/load.py
photutils/datasets/tests/test_load.py
setup.cfg

Also removes the ignoring of `pytest` warnings for unclosed files during tests.

Ensure load functions close FITS files

---

CHANGES.rst
photutils/datasets/load.py
photutils/datasets/tests/test_load.py

This dataset is not used anywhere in `photutils` for testing or documentation.

Deprecate load_fermi_image

---

CHANGES.rst
photutils/psf/photometry.py

The PSF photometry classes will no longer emit a RuntimeWarning if the fit parameter variance is negative (returned from scipy).

Ignore RunTimeWarning when calculating PSF parameter uncertainties

---

photutils/aperture/tests/test_stats.py
setup.cfg

Also fixes the test that generated the warning.

Remove invalid value from pytest filterwarnings

---

photutils/aperture/stats.py

This PR prevents the "converting a masked element to nan" warning message for `ApertureStats.sum_err` when a source is completely masked.

Prevent ApertureStats sum_err from giving a warning for completely masked sources

---

photutils/isophote/tests/test_regression.py
setup.cfg

This PR resolves a warning in an `isophote` test and also removes all the pytest warningfilters that are resolved.

Remove pytest filterwarnings from setup

---

docs/conf.py
setup.cfg

This PR unpins the sphinx version and turns off the table of contents entries for functions and classes.  This can be revisited if the astropy sphinx theme sidebar width is increased.
Followup to #1424.

Unpin sphinx version

---

CHANGES.rst
photutils/centroids/core.py
photutils/segmentation/catalog.py

This PR adds `centroid_quad` and `cutout_centroid_quad`, calculated using `centroid_quadratic` (2D quadratic fit), to `SourceCatalog`.

Add quadratic centroids to SourceCatalog

---

CHANGES.rst
photutils/segmentation/catalog.py

This PR adds `xcentroid_quad`, `ycentroid_quad`, and `sky_centroid_quad` to `SourceCatalog`.
Followup to #1467

Add addition quadratic centroid properties

---

CHANGES.rst
docs/whats_new/1.6.rst
photutils/segmentation/catalog.py

This PR adds a `progress_bar` keyword to `SourceCatalog` for displaying progress bars when calculating some source properties.

Add progress_bar option to SourceCatalog

---

photutils/aperture/photometry.py
photutils/aperture/stats.py
photutils/segmentation/catalog.py

This PR adds a note in the docstrings of `aperture_photometry`, `ApertureStats`, and `SourceCatalog` that these functions/classes do not convert the input data from surface brightness to flux.  The user will need to do that before using these functions/classes.
ref: https://github.com/astropy/photutils/issues/1403

Add notes about surface brightness units

---

CHANGES.rst
docs/whats_new/1.6.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

As requested in #1427, this PR adds a new ``subshape`` keyword to the PSF-fitting classes to define the shape over which the PSF is subtracted when computing the residual image. Previously, the PSF-subtraction region was always defined by the ``fitshape`` keyword. By default (and for backwards compatibility), ``subshape`` is set to `None`, which means the ``fitshape`` value will be used.
Closes #1427.

Add subshape keyword to PSF-fitting classes

---

setup.cfg

Setuptools is not required during runtime.
Remnant of #1443, #1454

Remove setuptools from install_requires

---

CHANGES.rst
docs/aperture.rst
photutils/aperture/core.py

This PR significantly improves the performance of the ``PixelAperture`` ``area_overlap`` method, especially for large arrays, by avoiding copying the input array.

Refactor area_overlap method for performance

---

tox.ini

astropy dev now requires numpy >= 1.21.

Update minimum numpy version for CircleCI

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/gaussian.py
photutils/centroids/tests/test_core.py

This PR fixes an issue where ``centroid_quadratic`` would sometimes fail if the input data contained NaNs.

Fix centroid_quadratic for data with NaNs

---

photutils/centroids/core.py
photutils/psf/models.py

Numpy 1.25 will deprecate `np.product` in favor of `np.prod` (https://github.com/numpy/numpy/pull/23314).

Use np.prod instead of deprecated np.product

---

CHANGES.rst
photutils/isophote/isophote.py
photutils/isophote/tests/test_harmonics.py

This PR fixes a bug in the sign of the isophote upper harmonics (a3, a4, b3, and b4).  I confirmed that these coefficients are fit to the correct equation in [Jedrzejewski 1987](https://ui.adsabs.harvard.edu/abs/1987MNRAS.226..747J/abstract), however, they are later scaled by the SMA and the local gradient.  Because the local gradient is negative, the sign of the upper harmonic values changes.  The original scaling in the IRAF/STSDAS version uses the absolute value of the gradient (see https://github.com/spacetelescope/stsdas_stripped/blob/043c173fd5497c18c2b1bfe8bcff65180bca3996/stsdas/pkg/analysis/isophote/src/elfit.x#L476-L477).  This PR updates the scaling to use the absolute value.
While investigating this PR, I also discovered a bug in the calculation of the upper harmonic errors. …

Fix sign of isophote upper harmonics

---

CHANGES.rst
photutils/aperture/stats.py
photutils/aperture/tests/test_stats.py

The ``ApertureStats`` ``local_bkg`` keyword can now be broadcast for apertures with multiple positions.

Allow ApertureStats local_bkg to be broadcast

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR adds a `size` keyword to the `SegmentationImage.make_source_mask` method to define square/rectangular footprints for source dilation.  It also significantly improves the performance of `make_source_mask` when using square/rectangular footprints.  This is accomplished by using `scipy.ndimage.grey_dilation` (instead of `binary_dilation`), which uses a separable footprint for better performance.

Add size keyword to SegmentationImage.make_source_mask

---

docs/aperture.rst

No reason not to use ``local_bkg``, right? Should put best practice in example? xref:
* #1316

DOC: Encourage local_bkg in ApertureStats

---

CHANGES.rst
docs/install.rst
docs/whats_new/1.7.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py
photutils/utils/_optional_deps.py
setup.cfg

With the PR, the ``SegmentationImage`` class now has a ``polygons`` attribute, which returns a list of `Shapely <https://shapely.readthedocs.io/>`_ polygons representing each source segment. It also now has ``to_patches`` and ``plot_patches`` methods, which return or plot, respectively, a list of `matplotlib.patches.Polygon` objects. These features require that both the `Rasterio <https://rasterio.readthedocs.io/>`_ and `Shapely <https://shapely.readthedocs.io/>`_ optional dependencies are installed.
The ``repr()`` notebook output for the ``Segment`` class now includes a SVG polygon representation of the segment if the ``rasterio`` and ``shapely`` packages are installed.
This PR also deprecates the `SegmentationImage` `outline_segments` method in favor of `plot_patches`.

Add ability to convert SegmentationImage segments to polygons

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/tests/test_daofinder.py

This PR fixes an issue with the starfinders (``DAOStarFinder``, ``IRAFStarFinder``, and ``StarFinder``) where an exception was raised if ``exclude_border=True`` and there were no detections.
Thanks to @cmccully for reporting this bug.
Fixes #1510

Fix star finders if exclude_border=True and there are no detections

---

photutils/detection/peakfinder.py

This PR adds a note about the integer values by default to the `find_peaks` API docs.  It is already mentioned in the narrative docs.
Closes: #1492

Add note to find_peaks

---

CHANGES.rst
docs/centroids.rst
photutils/centroids/core.py
photutils/centroids/tests/test_core.py

This PR updates `centroid_sources` to raise an error if the cutout mask is all `True` (completely masked), leaving no valid pixels from which to calculate the centroid.
It also adds an example to `centroid_sources`.
Closes https://github.com/astropy/photutils/issues/1514

Check that cutout mask in centroid_sources is not all True

---

CHANGES.rst
photutils/psf/photometry.py

This PR fixes an issue in the PSF photometry classes where even if `progress_bar=True`, the progress bar would not be shown.

Fix PSF progressbar

---

docs/epsf.rst
photutils/psf/epsf.py

`linkcheck` started reporting 403 errors for https://www.stsci.edu/files/live/sites/www/files/home/hst/instrumentation/wfc3/documentation/instrument-science-reports-isrs/_documents/2016/WFC3-2016-12.pdf
despite it being a valid URL.
Here I replaced the link for the ISR with the one for the ADS reference, which fixes the errors.

DO: Replace ISR link from PDF file to ADS

---

CHANGES.rst
photutils/psf/photometry.py

This PR fixes an issue where all PSF uncertainties were excluded if the last star group had no covariance matrix.
Many thanks to @kevinss5 for reporting this issue.
Fixes: #1505

Fix PSF uncertainties

---

CHANGES.rst
photutils/aperture/bounding_box.py
photutils/aperture/core.py
photutils/background/background_2d.py
photutils/segmentation/catalog.py
photutils/segmentation/core.py

This PR removes the deprecated ``axes`` keyword in favor of ``ax`` for consistency with matplotlib and other packages

Remove deprecated axes keyword in favor of ax

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

This PR removes the deprecated ``kernel`` keyword from ``detect_sources`` and ``deblend_sources``.

Remove deprecated kernel keyword

---

CHANGES.rst
docs/segmentation.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR removes the deprecated `outline_segments` method from `SegmentationImage`.  The `plot_patches` method should be used instead.

Remove deprecated outline_segments method from SegmentationImage

---

photutils/aperture/core.py
photutils/aperture/mask.py

This PR splits the `ApertureMask.get_values` method into two methods.  The new (private) method is separate from ``get_values`` to facilitate applying the same slices, aper_weights, and pixel_mask to multiple associated arrays (e.g., data and error arrays). It is used in this way by the `PixelAperture.do_photometry` method.

Refactor ApertureMask get_values for reuseability

---

.circleci/config.yml
tox.ini

Astropy dev now requires Python 3.9+

Update Python version for Astropy dev test

---

.github/workflows/32bit_tests.yml

Also updates the 32-bit test to use Python 3.9, which is now the minimum supported version for astropy dev.

Add 32-bit test to Actions

---

photutils/psf/models.py

The `devdeps` CI tests are failing due to a new numpy `DeprecationWarning` (Conversion of an array with ndim > 0 to a scalar is deprecated).  This PR fixes that issue to prevent the warnings.

Fix PRFAdapter for numpy 1.25+ deprecation

---

photutils/isophote/tests/test_harmonics.py

This test is randomly failing with `numpy` dev (likely due to recently precision changes with `numpy` sin/cos).  This PR lowers the test tolerance.

Lower tolerance of isophote harmonics test

---

CHANGES.rst
photutils/aperture/stats.py

This method is used only internally for handling `NDData` inputs.  It's not useful for the user.

Remove ApertureStats unpack_nddata from public API

---

CHANGES.rst
docs/profiles.rst
photutils/profiles/core.py
photutils/profiles/curve_of_growth.py
photutils/profiles/radial_profile.py
photutils/profiles/tests/test_curve_of_growth.py
photutils/profiles/tests/test_radial_profile.py

This PR changes the API for defining the radial bins for the ``RadialProfile`` and ``CurveOfGrowth`` classes.  While the new API allows for more flexibility (e.g., non-uniform radial spacing), unfortunately, it is not backwards-compatible.  This is a very rare case where breaking the API is necessary.  These classes were added in the last release (1.7.0) about a month ago, so hopefully the inconvenience will be minimal. 
Followup to #1538, #1529

Change radius API for RadialProfile and CurveOfGrowth

---

docs/install.rst

`pip` has deprecated the `git+https://github.com/astropy/photutils.git#egg=photutils[all]` format in favor of `photutils[all] @ git+https://github.com/astropy/photutils.git`

Update install instructions from git

---

photutils/psf/matching/tests/test_windows.py

`scipy.signal.tukey` is deprecated for `scipy.signal.windows.tukey` in SciPy 1.13.0+.
This fixes the failing CI devdeps test.

Fix deprecated namespace for scipy.signal.tukey

---

tox.ini

Also includes `scikit-image` dev in `devdeps` tests.

Update devdeps URL for nightly wheels

---

CHANGES.rst
photutils/background/__init__.py
photutils/background/local_background.py
photutils/background/tests/test_local_background.py

This PR adds a `LocalBackground` class for computing local backgrounds in a circular annulus aperture.

Add LocalBackground class

---

photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

Adds `xinit`, `x_0`, and `x0` (same for y) to the allowed column names.
Also adds unit tests for the column names.

Add more x/y column name options for PSFPhotometry init_params

---

tox.ini

`scikit-learn` dev is now available from https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/scikit-learn/
closes #1551

Update installation of scikit-learn dev

---

.github/workflows/ci_tests.yml
.github/workflows/publish.yml
.pre-commit-config.yaml
CHANGES.rst
docs/install.rst
setup.cfg
tox.ini

Per [NEP-0029](https://numpy.org/neps/nep-0029-deprecation_policy.html), "On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)".

Drop support for Python 3.8

---

photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

If a PSF fit's central pixel is outside the bounds of the image (`data`), the calculation for the `cfit` column in the photometry result table tries to index `data` out of bounds and fails with an error. This PR checks before it indexes out of bounds, and masks the result in that case.

Fix for PSF fitting cfit column with out of bounds centroids

---

.github/workflows/cron_tests_weekly.yml
photutils/detection/tests/test_irafstarfinder.py
photutils/isophote/tests/test_ellipse.py
photutils/isophote/tests/test_model.py
photutils/psf/tests/test_photometry-depr.py
tox.ini

Adds a `devinfra` tox env for testing development version of infrastructure packages and adds a weekly cron job in GA.
Also fixes warning issues from dev version of pytest 8.x.

Add devinfra tox test

---

.github/workflows/ci_tests.yml
.github/workflows/publish.yml
CHANGES.rst
docs/install.rst
setup.cfg
tox.ini

Per [NEP-0029](https://numpy.org/neps/nep-0029-deprecation_policy.html), "On Jun 23, 2023 drop support for NumPy 1.21 (initially released on Jun 22, 2021)".
Note the `numpy` stopped building wheels for 32-bit systems starting with `numpy 1.22`.  The weekly CI cron job still tests 32-bit versions of some architectures using 32-bit version of numpy from Debian.  If Debian stops providing 32-bit numpy, then those test will be removed.

Remove support for numpy 1.21

---

CHANGES.rst
photutils/psf/groupstars.py
photutils/psf/photometry_depr.py
photutils/psf/tests/test_groupstars.py
photutils/psf/tests/test_photometry-depr.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

This PR deprecates:
- `BasicPSFPhotometry`, `IterativelySubtractedPSFPhotometry`, and `DAOPhotPSFPhotometry` in favor of the new `PSFPhotometry` and `IterativePSFPhotometry` classes
- `DAOGroup`, `DBSCANGroup`, and `GroupStarsBase` in favor of the new `SourceGrouper` class
- `get_grouped_psf_model` and `subtract_psf` functions

PSF photometry deprecations

---

CHANGES.rst
docs/psf.rst
photutils/psf/models.py
photutils/psf/photometry.py
photutils/psf/tests/test_models.py
photutils/psf/tests/test_photometry.py

The copy method does not copy the internal grid of PSF data.  Deepcopy will make a deep copy of the entire model, including the grid of PSF data.
Fixes #1580

Add copy and deepcopy methods to GriddedPSFModel

---

CHANGES.rst
photutils/datasets/make.py

This makes it easy to directly input the table into `PSFPhotometry`.

Rename output columns in make_test_psf_data

---

CHANGES.rst
photutils/psf/models.py

This PR replaces `lru_cache` with `cache` now that Python 3.9 is the minimum supported version.
It also makes the `fill_value` attribute public and does some housekeeping.

Replace lru_cache with cache in GriddedPSFModel

---

.github/workflows/cron_tests_weekly.yml

Numpy 1.24 is available through the Ubuntu package manager:  https://packages.ubuntu.com/lunar/python3-numpy. So switching to the `ubuntu_rolling` distro should vix the problems.
Note, this reverts #1574.

Fix weekly CI Architecture builds

---

CHANGES.rst
docs/grouping.rst
docs/psf.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

As noted in the narrative docs, simultaneously fitting very large star groups is computationally expensive and error-prone.

Add warning for large groups

---

photutils/isophote/isophote.py

This fixes the new E721 `codestyle` error about comparing types in the `isophote` package.

Fix codestyle issue for type comparison

---

CHANGES.rst
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

(This is replacing #1584)
This PR adds a function to psf.utils to create a GriddedPSFModel from a list of EPSF models.
The tests I added run and pass, but I'm skipping them temporarily for CI since they use a remote dataset - I'll replace this with a follow up PR.

add function to create GriddedPSFModel from EPSFs

---

tox.ini

This should fix the issue that we've been testing with a ~month old astropy dev version (as `astropy-iers-data` is a new dependency that hasn't been picked up with a newer dev wheel)
https://github.com/astropy/astropy/issues/15146

CI: add extra astropy pip index to pick up new dependency

---

CHANGES.rst
docs/psf.rst
photutils/psf/photometry.py

With this PR only the fit residuals, covariance matrix, and fit status results are stored.  This will reduce the memory footprint of `PSFPhotometry` (xref: #1580).

Save only select fit info from PSF fitting

---

CHANGES.rst
photutils/psf/photometry.py

Prevents a temporary memory allocation when creating the residual image.

Reduce memory usage of make_residual_image

---

CHANGES.rst
docs/grouping.rst
photutils/psf/groupers.py
photutils/psf/tests/test_photometry.py

This PR changes the `SourceGrouper` class to use the `scipy.cluster.hierarchy.fclusterdata` function instead of the `sklearn.cluster.DBSCAN` class.  In my testing they produce the same results (for the default DBSCAN kwargs).  I don't know that the extra DBSCAN options are actually useful.  With this change, we can eventually remove `scikit-learn` as an optional dependency (after the deprecated `DBSCANGroup` class is removed).
CC: @bmorris3

Change SourceGrouper to use scipy instead of scikit-learn

---

README.rst
photutils/CITATION.rst

This PR also removes unicode characters in the `CITATION.rst` file.  The BibTex entry in that file is copied from Zenodo (e.g., https://zenodo.org/record/7804137/export/hx), which contains unicode characters.  Some users report that the unicode characters prevents `photutils` from being imported with an `UnicodeDecodeError` (see https://github.com/astropy/photutils/issues/1095).

Update citation information

---

docs/psf.rst
photutils/psf/photometry.py

`_fit_models` is currently used internally, but I'm planning a refactor where it may no longer be needed.  Here I make it private to prevent its use (for now), but I may eventually make it public (depending on the refactor).

Move fit_models to a private attribute

---

CHANGES.rst
photutils/psf/groupers.py
photutils/psf/tests/test_groupers.py

This PR fixes a bug where if `SourceGrouper` had only one (x, y) input it would fail.  Now it returns a single group.
Also, a helpful error message is now raised if x and y are empty.
Thanks to @bmorris3 for leading me down the path to this bug.

Fix SourceGrouper with one source

---

.github/workflows/ci_tests.yml
CHANGES.rst
docs/install.rst
pyproject.toml
tox.ini

Testing revealed that Astropy 5.1+ is required for a few recent features in photutils.

Bump minimum Astropy to 5.1

---

tox.ini

The `contourpy` dependency of matplotlib pins `numpy < 2.0`.

Force numpy-dev in devdeps

---

CHANGES.rst
photutils/segmentation/deblend.py
photutils/segmentation/tests/test_deblend.py

This PR fixes an issue where ``deblend_sources`` and ``SourceFinder`` would raise an error if the ``contrast`` keyword was set to 1 (meaning no deblending).

Fix source deblending if contrast = 1

---

CHANGES.rst
photutils/segmentation/core.py

Binary dilation is very slow, especially for large footprints. This PR adds a faster implementation using fast Fourier transforms (FFTs) that gives identical results to scipy's `binary_dilation`. Based on the following paper: "Dilation and Erosion of Gray Images with Spherical Masks", J. Kukal, D. Majerova, A. Prochazka (Jan 2007).

Use faster implementation of binary dilation using FFT

---

CHANGES.rst
photutils/aperture/photometry.py
photutils/aperture/stats.py
photutils/datasets/make.py
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/peakfinder.py
photutils/detection/starfinder.py
photutils/isophote/isophote.py
photutils/psf/photometry_depr.py
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py
photutils/utils/_misc.py
photutils/utils/tests/test_misc.py

The metadata in output tables now contains a timestamp (also with package versions).
Package versions in table metadata are now stored in the "versions" key.  Previously, this key was named "version".
Also, the order of the metadata in a table is now preserved when writing to a file.  The astropy Table class currently does not preserve key order when serializing `dict` objects (using yaml).  However, Table.meta currently uses `OrderedDict` and its key order is preserved when serializing.  Here, we use the default meta type to preserve key order.

Updates to table metadata

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR adds a `scale` keyword to `SegmentationImage.to_patches` to scale the size of the polygon patches.

Add option to scale polygon patches

---

pyproject.toml

This can be removed after upstream packages are updated.

Ignore numpy.core deprecation warnings

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR fixes an issue where the vertices of the `SegmentationImage` `polygons` were shifted by 0.5 pixels in both x and y.  This is because `rasterio.features.shapes` uses a coordinate frame with the (0, 0) origin at the *lower-left* corner of the lower-left pixel.

Fix xy coordinates of SegmentationImage polygon vertices

---

.pre-commit-config.yaml
docs/conf.py
photutils/__init__.py
photutils/aperture/circle.py
photutils/background/background_2d.py
photutils/conftest.py
photutils/isophote/fitter.py
photutils/isophote/harmonics.py
photutils/isophote/tests/test_regression.py
photutils/psf/griddedpsfmodel.py
photutils/psf/models.py
photutils/psf/photometry_depr.py
photutils/psf/tests/test_models.py
photutils/psf/tests/test_photometry-depr.py
photutils/psf/tests/test_utils.py

This PR adds the `double-quote-string-fixer` hook to pre-commit to replace double-quoted strings with single-quoted strings.

Use single quotes for consistency

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR makes three improvements to `Segmentation` image plotting:
- Improved the ``imshow`` method to ensure that labels are plotted with unique colors
- Added a ``imshow_map`` method for plotting segmentation images with a small number of non-consecutive labels.
- Added a ``reset_cmap`` method for resetting the colormap to a new random colormap.

Segmentation imshow improvements

---

.pre-commit-config.yaml
docs/whats_new/1.6.rst
photutils/profiles/core.py
photutils/psf/griddedpsfmodel.py
photutils/psf/photometry.py
photutils/psf/photometry_depr.py
photutils/psf/utils.py
photutils/segmentation/catalog.py
photutils/segmentation/core.py

The following words are ignored: 
- "exten" for "extension" (psf)
- "conver" for "convergence" (isophote)
- "fom" for "figure of merit" (isophote)

Add codespell to pre-commit hooks

---

photutils/segmentation/tests/test_catalog.py
photutils/utils/_misc.py
photutils/utils/tests/test_misc.py

Revert https://github.com/astropy/photutils/pull/1640/commits/b016c2c6e87879de7c54bfd9035989cae4a83755 because it breaks `jwst`.

Change meta key name back to version

---

CHANGES.rst
photutils/psf/griddedpsfmodel.py

The ``GriddedPSFModel`` ``plot_grid`` method now returns a ``matplotlib.figure.Figure`` object.

Return Figure object from GriddedPSFModel.plot_grid

---

CHANGES.rst
photutils/aperture/core.py

This PR fixes an issue where the aperture ``plot`` method ``**kwargs`` were stored and not reset to the default values when called multiple times.

Fix aperture plot kwargs

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

With this PR PSF models output from ``prepare_psf_model`` can now be input into the PSF photometry classes.

Allow PSF models output with prepare_psf_model

---

CHANGES.rst
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

This PR adds a `make_psf_model` function that replaces the `prepare_psf_model` function.  The new function is faster when normalizing models (using subsampling) and supports input `CompoundModels`, which the old function did not.  The `prepare_psf_model` function is now deprecated.

Add make_psf_model function

---

CHANGES.rst
photutils/psf/griddedpsfmodel.py
photutils/psf/tests/test_griddedpsfmodel.py

This PR fixed a bug in ``GriddedPSFModel`` ``plot_grid`` where the grid could be plotted incorrectly if the input ``xygrid`` was not sorted in y then x order. The ``GriddedPSFModel`` now stores the ePSF grid such that it is first sorted by y then by x. As a result, the order of the ``data`` and ``xygrid`` attributes may be different.

Fix GriddedPSFModel plot_grid

---

CHANGES.rst
photutils/psf/griddedpsfmodel.py
photutils/psf/tests/test_griddedpsfmodel.py

`GriddedPSFModel` does not work with 3D input x and y arrays.  With this PR, a ``ValueError`` is raised if it is called with x and y arrays that have more than 2 dimensions.
Closes: #1660

Check GriddedPSFModel inputs

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/starfinder.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py

This PR adds a ``min_separation`` keyword to ``DAOStarFinder`` and ``IRAFStarFinder``.  For `IRAFStarFinder`, `min_separation` will override the `minsep_fwhm` keyword.
Closes #1561

Add min_separation keyword to DAOStarFinder and IRAFStarFinder

---

CHANGES.rst
photutils/utils/_coords.py

This PR improves the performance of the (private) `apply_separation` function used in `ImageDepth` and `make_test_psf_data` when generating random coordinates.

Improve performance of apply_separation

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR fixes an issue where PSF models produced by ``make_psf_model`` would raise an error with ``PSFPhotometry`` if the fit did not converge.

Fix compound PSF model bug

---

CHANGES.rst
photutils/psf/griddedpsfmodel.py
photutils/psf/tests/test_griddedpsfmodel.py

This PR fixes an issue in the `GriddedPSFModel.copy()` method where the "fixed" values of parameters were not preserved in the model copy.
Many thanks to @aarranshaw for reporting #1678, which uncovered this bug.
Fixes #1678.

Fix GriddedPSFModel copy method

---

photutils/psf/griddedpsfmodel.py
photutils/psf/tests/test_griddedpsfmodel.py

This PR lowers the memory usage of `GriddedPSFModel` copies. It also removes the private `_nddata` attribute.  Followup to #1679.

Improve GriddedPSFModel copy

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/core.py
photutils/segmentation/tests/test_catalog.py

The ``SourceCatalog`` ``get_label`` and ``get_labels`` methods now raise a ``ValueError`` if any of the input labels are invalid.

Add a check for valid labels in get_labels

---

photutils/psf/griddedpsfmodel.py

In astropy 6.1, `min_cut` and `max_cut` are renamed to `vmin` and `vmax`, respectively.

Handle renamed keywords in astropy visualization

---

photutils/psf/photometry.py

This pull request is to solve issue #1690. I added a new keyword to the function `make_model_image' and `make_residual_image' of the PSFPhotometry-class to toggle whether the local background model is included or not.
> At the moment it is only possible to make a model image of the fitted PSF Photometry that includes the locally measured background for each star. However, when there is highly structures background and a crowded field, it may be desirable to only subtract a model of the fit stars from the image, without the local background estimate (that currently can only be a scalar). Otherwise we have overlapping regions of subtracted scalar backgrounds in the residual image when stars are close to each other.
> This option may also be useful for iterative PSF fitting of clustered …

Add option to exclude local background in residual image (#1690)

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

The PSF photometry ``make_model_image`` and ``make_residual_image`` methods no longer include the local background by default, which causes issues if the `psf_shape` of sources overlap.  This is a backwards-incompatible change. If the previous behavior is desired, set ``include_localbkg=True``.
Followup to #1691.

Change default to not include local background in PSF model/residual images

---

CHANGES.rst
docs/psf.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

The PSF photometry ``finder_results`` attribute is now returned as a ``QTable`` instead of a list of ``QTable``.

Return finder_results as a QTable

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR adds a `mode` keyword to `IterativePSFPhotometry` for controlling the fitting mode.
For the 'new' mode (default), `PSFPhotometry` is run in each iteration only on the new sources detected in the residual image. The 'new' mode preserves the original behavior of `IterativePSFPhotometry`.
For the 'all' mode, `PSFPhotometry` is run in each iteration on all the detected sources (from all previous iterations) on the original, unsubtracted, data. For the 'all' mode, a source ``grouper`` must be input.  Initial tests indicate that the 'all' mode may give better results than the older 'new' method.

Add mode keyword to IterativePSFPhotometry

---

pyproject.toml

This is needed for runtime compatibility with the upcoming numpy 2.0, and I *think* that it's also sufficient, but maybe I'm missing something ? anyway feel free to push to this branch or to incorporate it some other way.

BLD: build with numpy 2.0.0rc1 (or newer)

---

.github/workflows/ci_cron_daily.yml
.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_tests.yml
.github/workflows/publish.yml
CHANGES.rst
docs/install.rst
pyproject.toml
tox.ini

Following NEP-29, the minimum supported Python version is 3.10.  Also, the minimum NumPy is 1.23.
Other dependencies:
* Scipy >= 1.8
* scikit-learn >= 1.1
* pytest-astropy >= 0.11
* sphinx-astropy >= 1.9
* scikit-image >= 0.20

Update min versions of dependencies

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

With this PR, warnings will not occur if NaNs in the data are masked in ``coverage_mask`` passed to ``Background2D``.  Extension of #1712.

Remove warning in Background2D

---

CHANGES.rst
docs/profiles.rst
photutils/profiles/core.py
photutils/profiles/tests/test_curve_of_growth.py

This PR adds an ``unnormalize`` method to ``RadialProfile`` and ``CurveOfGrowth`` to return the profile to the state before any ``normalize`` calls were run.

Add unnormalize method to profiles

---

CHANGES.rst
docs/profiles.rst
photutils/profiles/curve_of_growth.py
photutils/profiles/radial_profile.py
photutils/profiles/tests/test_curve_of_growth.py

This PR adds ``calc_ee_from_radius`` and ``calc_radius_from_ee`` methods to ``CurveOfGrowth``, which use an interpolation function to compute encircled energy (EE) at a specified radius or vice versa.

Add encircled energy methods to CurveOfGrowth

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR checks the that the input `psf_model` to `PSFPhotometry` and `IterativePSFPhotometry` is two-dimensional with `n_inputs = 2` and `n_outputs = 1`.

Check dimensionality of PSF model

---

CHANGES.rst
docs/detection.rst
docs/epsf.rst
photutils/detection/peakfinder.py
photutils/detection/tests/test_peakfinder.py

Wit this PR:
* The ``find_peaks`` function now supports ``Quantity`` inputs.
* The ``Table`` returned from ``find_peaks`` now has an ``id`` column that contains unique integer IDs for each peak.

Add support for units in peak_finder

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/starfinder.py
photutils/detection/tests/conftest.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py
photutils/detection/tests/test_peakfinder.py
photutils/detection/tests/test_starfinder.py
photutils/utils/_quantity_helpers.py
photutils/utils/tests/test_quantity_helpers.py

With this PR, the `DAOStarFinder`, `IRAFStarFinder`, and `StarFinder` now support input data with units.  In that case, other keyword values like `threshold` must also have the same units as the data.
This PR also refactors the test suite in the detection subpackge.

Add support for units in DAOStarFinder, IRAFStarFinder, and StarFinder

---

photutils/segmentation/detect.py
photutils/segmentation/finder.py

Clarifies that units are needed on `threshold` if `data` has units.

Update segmentation docstrings

---

CHANGES.rst
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/starfinder.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py

This keyword will be removed in a future version.  The input data array should already be background-subtracted.

Deprecate sky keyword in DAOStarFinder and IRAFStarFinder

---

photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR makes changes to `PSFPhotometry` that are necessary after #1746 to support units.  It also adds unit tests for both `PSFPhotometry` and `IterativePSFPhotometry`.

FIx PSFPhotometry unit support

---

CHANGES.rst
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/starfinder.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py
photutils/detection/tests/test_starfinder.py

With this PR, sources that have non-finite properties (e.g., centroid, roundness, sharpness, etc.) are automatically excluded from the output table in ``DAOStarFinder``, ``IRAFStarFinder``, and ``StarFinder``.

Exclude sources with non-finite properties in star finders

---

photutils/aperture/tests/test_aperture_common.py
photutils/aperture/tests/test_photometry.py
photutils/segmentation/tests/test_detect.py

`assert_array_equal` runs `np.asanyarray` on the inputs and thus is not needed if the inputs are already arrays.

Replace assert_array_equal with assert_equal

---

CHANGES.rst
photutils/psf/models.py
photutils/psf/tests/test_models.py

This PR fixes the ``IntegratedGaussianPRF`` class ``bounding_box`` limits to always be symmetric. 
The ``bounding_box`` is also now a method instead of an attribute for consistency with Astropy models.  The method has a ``factor`` keyword to scale the bounding box.  The default scale factor is 5.5 times ``sigma``.

Fixes to IntegratedGaussianPRF bounding box

---

CHANGES.rst
photutils/psf/photometry.py

This PR adds an ``include_localbkg`` keyword to the ``IterativePSFPhotometry`` ``make_model_image`` and ``make_residual_image`` methods, mirroring the `PSFPhotometry` class.
The ``IterativePSFPhotometry`` ``make_model_image`` and ``make_residual_image``  methods no longer include the local background by default. This is a backwards-incompatible change. If the previous behavior is desired,  set ``include_localbkg=True``.
This PR also adds a new `ModelImageMixin` class that provides the common calculate model images and residuals for both `PSFPhotometry` and `IterativePSFPhotometry`.

Add include_localbkg keyword to IterativePSFPhotometry methods

---

photutils/isophote/geometry.py

just fixed a typo that caused me some confusion, also added some additional details about how that parameter is defined

fixed description of ellipticity parameter in EllipseGeometry

---

CHANGES.rst
photutils/psf/photometry.py

This PR prevents possible table merge conflict because of the date in the table metadata.

Prevent table merge conflicts in IterativePSFPhotometry

---

CHANGES.rst
docs/grouping.rst
photutils/datasets/images.py
photutils/datasets/sources.py
photutils/datasets/tests/test_images.py
photutils/datasets/wcs.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_photometry-depr.py
photutils/psf/tests/test_photometry.py

The ``make_gaussian_sources_image``, ``make_gaussian_prf_sources_image``, and `make_imagehdu` functions are now deprecated. 
For the Gaussian functions, use the more flexible ``make_psf_test_data`` or the new ``make_model_image`` functions instead.

Deprecate functions in datasets

---

CHANGES.rst
photutils/datasets/examples.py
photutils/datasets/images.py
photutils/datasets/sources.py
photutils/datasets/tests/test_sources.py

The ``make_gaussian_sources_table`` function now always returns both ``'flux'`` and ``'amplitude'`` columns.

Always return both amplitude and flux columns from make_random_gaussians_table

---

CHANGES.rst
photutils/datasets/sources.py
photutils/datasets/tests/test_noise.py
photutils/datasets/tests/test_sources.py

The ``make_gaussian_sources_table`` function is now deprecated.  Use the more general ``make_model_sources_table`` function instead.
The ``make_model_sources_table`` function now includes an "id" column in the output table.

Deprecate make_gaussian_sources_table

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR adds "x_fit", "xfit", "y_fit", "yfit", "flux_fit", and "fluxfit" as allowed column names in the ``init_params`` table input to the PSF photometry objects.
This PR also fixes a bug where the first matching column in the ``init_params`` table was not used in ``PSFPhotometry`` and ``IterativePSFPhotometry``.

Add additional allowed columns in PSF photometry init_params

---

CHANGES.rst
photutils/datasets/examples.py
photutils/datasets/images.py
photutils/datasets/sources.py
photutils/datasets/tests/test_sources.py
photutils/psf/photometry.py
photutils/psf/utils.py
photutils/utils/_coords.py

This PR adds a `make_model_params` function to make a table of randomly generated model positions and fluxes for simulated sources.
This PR also changes the new `make_model_image` keyword names to `x_name` and `y_name` for consistency with other existing functions.

Add make_model_params function

---

photutils/centroids/core.py
photutils/datasets/images.py
photutils/detection/starfinder.py
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py
photutils/utils/cutouts.py

This PR provides a temporary fix to an upstream corner-case bug in Astropy `overlap_slices`.  This fix can be removed when the minimum required astropy >= 6.1.1.

Fix for overlap bug

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

With this PR, ``PSFPhotometry`` and ``IterativePSFPhotometry`` will now raise a ``ValueError`` for invalid source positions in ``init_params``.

Add a check for invalid source positions in PSF photometry init_params

---

CHANGES.rst
photutils/psf/photometry.py

The ``IterativePSFPhotometry`` ``psfphot`` attribute has also been removed. Instead, use the ``fit_results`` attribute, which contains a list of ``PSFPhotometry`` instances for each fit iteration.

Some refactoring of IterativePSFPhotometry

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

The ``group_size`` column has been moved to come immediately after the ``group_id`` column in the output table from ``PSFPhotometry`` and ``IterativePSFPhotometry``.

Move group_size column in PSF photometry output

---

CHANGES.rst
docs/psf.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

The ``PSFPhotometry`` ``init_params`` table was moved from the``fit_results`` dictionary to a stand-alone attribute.
This PR also removeds  ``local_bkg``, ``psfcenter_indices``, ``fit_residuals``,``npixfit``, and ``nmodels`` keys from the ``PSFPhotometry`` ``fit_results`` dictionary.  `local_bkg`, `npixfit`, and `nmodels` are available in the output table.  `psfcenter_indices` and `fit_residuals` were used internally in the code and not intended to be public-facing.

Fit results keys

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

A ``ValueError`` is now raised if the shape of the ``error`` array does not match the ``data`` array when calling the PSF-fitting classes.

Ensure error and data arrays have the same shape

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR fixes an issue where ``IterativePSFPhotometry`` could sometimes raise an error about non-overlapping data.  This was caused by the fitter failing and returning positions well outside of the input image during the iterations.  When those invalid positions then were used an inputs in a subsequent iteration, a `ValueError` was raised.  With this PR, those invalid positions are automatically removed during the iterations.
Fixes #1769.

Fix IterativePSFPhotometry no overlap error

---

CHANGES.rst
docs/grouping.rst
docs/psf.rst
photutils/datasets/images.py
photutils/datasets/tests/test_images.py
photutils/datasets/wcs.py
photutils/detection/tests/conftest.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py
photutils/detection/tests/test_peakfinder.py
photutils/detection/tests/test_starfinder.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

This PR adds a new `make_psf_model_image` function.  This PR also deprecates the `make_test_psf_data` function in favor of `make_psf_model_image`.

Add function to make a simulated image from PSF models

---

CHANGES.rst
photutils/aperture/stats.py
photutils/aperture/tests/test_stats.py
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

This PR fixes an issue in ``ApertureStats`` and `SourceCatalog` where in very rare cases the ``covariance`` calculation could take a long time.
Fixes #1775

Fix issue with covariance matrix in ApertureStats and SourceCatalog

---

CHANGES.rst
photutils/datasets/images.py
photutils/datasets/tests/test_images.py

This PR fixes unit support in `make_model_image`.  To use units, one must input the model `params_table` as a `QTable` (not `Table`) with `Quantity` columns.

Fix unit support in make_model_image

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

The ``PSFPhotometry`` and ``IterativePSFPhotometry`` ``init_params`` table now allows the user to input columns for model parameters other than x, y, and flux. The column names must match the parameter names in the PSF model. They can also be suffixed with either the "_init" or "_fit" suffix.
This PR also fixes an issue in ``IterativePSFPhotometry`` where the ``fit_results`` attribute was not cleared between repeated calls.

Allow additional model parameters in PSF photometry init_params

---

CHANGES.rst
docs/psf.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR adds a new ``xy_bounds`` keyword to ``PSFPhotometry`` and ``IterativePSFPhotometry`` to allow one to bound the x and y model parameters during the fitting.  If any fitted x or y value is at the bounded value, then a new flag value of 32 is added to the bitwise `flags` column.
Closes #1801 
CC: @keflavich

Add xy_bounds keyword for PSF photometry

---

CHANGES.rst
docs/psf.rst
photutils/conftest.py
photutils/utils/_misc.py
photutils/utils/_optional_deps.py
photutils/utils/tests/test_misc.py

`sklearn` was removed as an optional dependency in 1.13.0.
As part of this removal, the ``sklearn`` version information has been removed from the meta attribute in output tables.

Remove stray references to sklearn

---

CHANGES.rst
photutils/isophote/model.py
photutils/isophote/tests/test_model.py

With this PR, the ``build_ellipse_model`` function now raises a ``ValueError`` if the input ``isolist`` is empty.

Raise ValueError if isolist is empty

---

CHANGES.rst
photutils/isophote/model.py
photutils/isophote/tests/test_model.py

This PR fixes the issues reported in #1776 and #1722 where the high-order harmonics were not properly being added to the ellipse model in `build_ellipse_model` when `high_harmonics=True`. 
Fixes: #1776, #1722

Do not average upper harmonics in build_ellipse_model

---

CHANGES.rst
photutils/aperture/core.py
photutils/aperture/tests/test_photometry.py

This PR fixes a bug in the check of the `subpixels` value in aperture photometry.  Many thanks to @havijw for reporting this!

Fix check of subpixels value

---

docs/conf.py

This PR updates the RTD settings because they are removing Sphinx context injection at build time. See https://about.readthedocs.com/blog/2024/07/addons-by-default/

DOC: Add new RTD settings in docs config

---

CHANGES.rst
photutils/psf/epsf_stars.py
photutils/psf/tests/test_epsf.py

With this PR, the ``extract_stars`` function can now accept ``NDData`` inputs with uncertainty types other than ``weights``.  This includes `InverseVariance`, `StdDevUncertainty`, and `VarianceUncertainty`.
Closes: #739

Allow NDData uncertainties in extract_stars

---

photutils/isophote/isophote.py
photutils/isophote/tests/test_isophote.py

This property is inherited from the parent class.

Remove unneeded x0 property from CentralPixel

---

.pre-commit-config.yaml
pyproject.toml

[pre-commit.ci](https://pre-commit.ci/) is now running on PRs.

Add pre-commit autoupdate schedule

---

.flake8
.pep8speaks.yml
.pycodestyle
photutils/aperture/circle.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/stats.py
photutils/aperture/tests/test_converters.py
photutils/aperture/tests/test_photometry.py
photutils/datasets/images.py
photutils/isophote/ellipse.py
photutils/profiles/core.py
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/photometry.py
photutils/segmentation/catalog.py
photutils/segmentation/deblend.py
photutils/utils/_progress_bars.py
photutils/utils/depths.py
tox.ini

Most of the package already uses 79 characters.  That is recommended by [PEP8](https://peps.python.org/pep-0008/#maximum-line-length), and is also what core CPython uses.
Note that for long parameter types, a line-continuation character "\" is recommended.  However, this will not work if the docstring is a raw string.  Here, I've removed the raw strings if a line-continuation character is needed.

Use consistent max line lengths

---

.github/workflows/publish.yml

This will upload the wheels here: https://anaconda.org/astropy as for reproject and astropy-healpix
I've set up the token in the repository settings under ANACONDA_TOKEN. If there are permission issues when trying to upload a wheel, I can try and update the token scope.

Add publishing of developer wheels to anaconda.org

---

docs/install.rst

Follow-up of #1834
p.s. The `[all]` actually does not work right now because of `bottleneck` but fixing that is out of scope here.

DOC: Mention nightly wheel in dev install

---

CHANGES.rst
docs/install.rst
pyproject.toml
tox.ini

This is need to support fitting PSF models with units (#1838).

Require astropy 5.3+

---

docs/epsf.rst
docs/grouping.rst
docs/psf.rst

This PR also makes some small improvements to the PSF docs and changes the docs to use the new `CircularGaussianPRF` model.
Closes: #412

Add section describing PSF models in PSF photometry docs

---

photutils/psf/functional_models.py
photutils/psf/tests/test_functional_models.py

This PR increases the size of the `MoffatPSF` and `AiryDiskPSF` model bounding boxes to include more of the integrated flux.  These profiles have broad wings.

Increase the size of the PSF model bounding boxes

---

photutils/utils/cutouts.py
photutils/utils/tests/test_cutouts.py

This PR ensures the shape is converted to a `tuple` before being input to `extract_array`.

Allow array-like shape in CutoutImage

---

CHANGES.rst
docs/centroids.rst
photutils/centroids/core.py
photutils/centroids/gaussian.py
photutils/centroids/tests/test_core.py
photutils/centroids/tests/test_gaussian.py

With this PR ``Quantity`` arrays can now be input to ``centroid_1dg`` and ``centroid_2dg``.
For consistency with other fitting functions (including PSF fitting), the ``centroid_1dg`` and ``centroid_2dg`` functions now fit only a 1D or 2D Gaussian model, respectively, excluding any constant component. The input data are required to be background-subtracted (as previously stated in the docs).

Allow Quantity inputs to centroid_1dg and centroid_2dg

---

CHANGES.rst
docs/psf.rst
photutils/psf/model_helpers.py
photutils/psf/tests/test_model_helpers.py

This PR deprecates the `PRFAdapter` class.  This class requires numerical integration of each pixel for every evaluation of the model. This makes it **extremely** slow (too slow to be practical), and only suited for experimentation over relatively few small regions. If a model class of this type is needed, it is strongly recommended that you create a custom PRF model instead.
If one needs a PRF model from an analytical PSF model, a more efficient option is to discretize the model on a grid using `astropy.convolution.discretize_model` using the ``'oversample'`` or ``'integrate'`` ``mode``. The resulting 2D image can then be used as the input to ``FittableImageModel`` to create an ePSF model.  In a test case, the differences between the `PRFAdapater` were on the order of 1e-5.

Deprecate PRFAdapter

---

photutils/background/background_2d.py
photutils/background/core.py
photutils/segmentation/detect.py
photutils/utils/_stats.py
photutils/utils/tests/test_stats.py

The PR changes the bottleneck stat functions when a tuple axis is used by moving the axis keywords to the last axis and then combining them so they can be operated on using axis=-1. The current implementation moves the axes to the first axis and then uses axis=0, but that operation is slower because the memory is non-contiguous (for the default C-like order).
Note the tuple axis reordering is necessary because bottleneck only allows integer axis values.
This PR also adds `_nansum, `_nanvar`, `_nanmin`, `_nanmax`.

Update bottleneck stat functions

---

CHANGES.rst
docs/background.rst
photutils/background/background_2d.py
photutils/background/core.py
photutils/background/interpolators.py
photutils/background/tests/test_background_2d.py
photutils/background/tests/test_interpolators.py
photutils/extern/biweight.py
photutils/segmentation/detect.py
photutils/utils/_stats.py
photutils/utils/tests/test_stats.py

This PR refactors the ``Background2D`` class to significantly reduce its memory usage. In some cases, it is also significantly faster.
With this PR, the ``background_mesh`` and ``background_rms_mesh``  properties will have units if the input data has units.  Also, a new `npixels_mesh` property was added.
This PR also includes a number of API changes/deprecations:
* the ``edge_method`` keyword is now deprecated. When ``edge_method`` is eventually removed, the ``'pad'`` option will always be used.
* the ``background_mesh_masked``, ``background_rms_mesh_masked``, and ``mesh_nmasked`` properties are now deprecated.
* to reduce memory usage, ``Background2D`` no longer keeps a cached copy of the returned ``background`` and ``background_rms`` properties.
* the ``data``, ``mask``, ``total_mask``, …

Refactor Background2D to reduce memory usage

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This new property gives a 2D array of the number of pixels used to compute the statistics in each mesh, resized to the shape of the input data.

Add npixels_map property to Background2D

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py
photutils/segmentation/tests/test_detect.py

With this PR, the ``SegmentationImage`` ``relabel_consecutive`` method now keeps the original dtype of segmentation image instead of always changing it to ``int`` (``int64``).  This change only affects segmentation image that were not already consecutively ordered.
Additionally, the ``detect_sources`` and ``deblend_sources`` functions now return a ``SegmentationImage`` instance whose data dtype is ``np.int32`` instead of ``int`` (``int64``) unless more than (2**32 - 1) labels  are needed.

Preserve SegmentationImage dtype

---

.github/workflows/ci_cron_daily.yml
.github/workflows/ci_tests.yml
CHANGES.rst
docs/install.rst
pyproject.toml
tox.ini

Following SPEC-0: https://scientific-python.org/specs/spec-0000/
This PR also adds Python 3.13 to the CI tests.

Update minimum dependencies

---

CHANGES.rst
photutils/detection/daofinder.py
photutils/detection/tests/test_daofinder.py

This PR fixes an issue (introduced in version 1.13.0) where `DAOStarFinder` would not return any sources if the input `threshold = 0`.  This is due to the `flux` being non-finite when `threshold = 0`, as defined by the original DAOFIND algorithm.  With this PR, the source parameters are returned, with the `flux` and `mag` columns being all infinite values.
Thanks to @mdlpstsci for reporting this issue.

Fix DAOStarFinder if threshold=0

---

photutils/aperture/stats.py

Fixes #1888
Many thanks to @qiushitian for reporting this.

[DOC] Fix typo in ApertureStats sum_err description

---

CHANGES.rst
docs/psf.rst
photutils/psf/epsf.py
photutils/psf/epsf_stars.py
photutils/psf/gridded_models.py
photutils/psf/image_models.py
photutils/psf/model_helpers.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_epsf_stars.py
photutils/psf/tests/test_image_models.py
photutils/psf/utils.py

This PR consolidates the `FittableImageMode` and `EPSFModel` into a new `ImagePSF` model.
The `FittableImageMode` and `EPSFModel` classes are now deprecated.

Add ImagePSF model class

---

photutils/background/background_2d.py

Bottleneck acceleration requires the data byte order to match the OS byte order.

Add note in Background2D about data byte order

---

CHANGES.rst
photutils/psf/model_helpers.py
photutils/psf/tests/test_model_helpers.py

This PR fixes a bug in ``make_psf_model`` where if the input model had amplitude units, an error would be raised. Now the units are carried through.

Fix unit bug in make_psf_model

---

CHANGES.rst
photutils/datasets/images.py
photutils/datasets/tests/test_images.py

This PR adds a new ``params_table_to_models`` function to create a list of models from a table of model parameters.

Add params_table_to_models function

---

CHANGES.rst
docs/psf.rst
docs/whats_new/2.0.rst
photutils/centroids/gaussian.py
photutils/profiles/radial_profile.py
photutils/psf/epsf.py
photutils/psf/matching/tests/test_fourier.py
photutils/psf/photometry.py
photutils/psf/tests/test_epsf.py
photutils/psf/tests/test_functional_models.py
photutils/psf/tests/test_model_helpers.py
photutils/psf/tests/test_photometry.py
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

This PR changes the default Astropy fitter for ``PSFPhotometry``, ``IterativePSFPhotometry``, and ``EPSFFitter``  from ``LevMarLSQFitter`` to ``TRFLSQFitter``.
``LevMarLSQFitter`` uses the Levenberg-Marquardt algorithm via the SciPy legacy function ``scipy.optimize.leastsq``, which is no longer recommended. This fitter supports parameter bounds using an unsophisticated min/max condition where parameters that are out of bounds are simply reset to the min or max of the bounds during each step. This can cause parameters to stick to one of the bounds during the fitting process if the parameter gets close to the bound. If needed, this fitter can still be used by explicitly setting the fitter in the ``PSFPhotometry``, ``IterativePSFPhotometry``, and ``EPSFFitter`` classes.
The fitter used in …

Remove LevMarLSQFitter

---

.github/workflows/ci_cron_daily.yml
.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_tests.yml
.github/workflows/codeql.yml
.github/workflows/publish.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

CHANGES.rst
docs/whats_new/2.0.rst
photutils/psf/functional_models.py
photutils/psf/gridded_models.py
photutils/psf/image_models.py
photutils/psf/tests/test_gridded_models.py

With this PR, the `~photutils.psf.GriddedPSFModel` class has been refactored to significantly improve its performance. In typical PSF photometry use cases, it is now about 4 times faster than previous versions.

Improve GriddedPSFModel performance

---

CHANGES.rst
docs/psf_matching.rst
docs/whats_new/2.0.rst
photutils/psf/__init__.py
photutils/psf/matching/windows.py

PSF matching tools must now be imported from ``photutils.psf.matching`` instead of ``photutils.psf``.

Imports from psf.matching

---

photutils/psf/functional_models.py
photutils/psf/gridded_models.py
photutils/psf/image_models.py

This PR replaces the `bounding_box` method with `set_bounding_box`.  The base `Model.bounding_box` is a property not a method, and this prevents the `bounding_box` docs from rendering.

Add set_bounding_box to models

---

docs/conf.py

To prevent the diagram from being cut off.

Fix PSF API class inheritance diagram

---

.pre-commit-config.yaml

`pre-commit` 4.0.0 removed `language: python_venv`, which breaks the `docformatter` hook.  See https://github.com/PyCQA/docformatter/pull/287

Temporarily disable docformatter pre-commit hook

---

CHANGES.rst
docs/user_guide/centroids.rst
docs/whats_new/2.0.rst
photutils/centroids/gaussian.py
photutils/centroids/tests/test_core.py
photutils/psf/tests/test_photometry.py

The default `stddev` of Astropy's `Gaussian1D` model is bounded to be strictly positive, so the `TRFLSQFitter` should be used.  Followup to https://github.com/astropy/photutils/pull/1899
I've opened a PR for `Gaussian2D` to have the same default bounds:  https://github.com/astropy/astropy/pull/17137
Many thanks to @astrofrog for pointing this out!

Replace LMLSQFitter with TRFLSQFitter

---

CHANGES.rst
docs/user_guide/psf.rst
photutils/psf/functional_models.py
photutils/psf/utils.py

All `*fwhm` and "radius" parameters are strictly positive by default.  The `MoffatPSF` `gamma` parameter is required to be > 1.

Add parameter bounds to PSF models

---

CHANGES.rst
docs/user_guide/psf.rst
docs/whats_new/2.0.rst
photutils/datasets/images.py
photutils/datasets/tests/test_images.py
photutils/psf/photometry.py
photutils/psf/simulation.py
photutils/psf/tests/test_photometry.py

With this PR, ``psf_shape`` is now an optional keyword in the ``make_model_image`` and ``make_residual_image`` methods of ``PSFPhotometry`` and ``IterativePSFPhotometry``. The value defaults to using the model bounding box to define the shape and is required only if the PSF model does not have a bounding box attribute.
This PR also fixes an issue in ``make_model_image`` where if the ``bbox_factor`` was input and the model bounding box did not have a ``factor`` keyword then an error would be raised.

Make psf_shape an optional keyword

---

CHANGES.rst
docs/whats_new/2.0.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

With this PR, the ``Background2D`` ``background``, ``background_rms``, ``background_mesh``, and ``background_rms_mesh`` properties now have the same ``dtype`` as the input data.

Preserve dtype in Background2D

---

CHANGES.rst
docs/whats_new/2.0.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

The ``SegmentationImage`` ``resassign_label(s)``, ``keep_label(s)``, ``remove_label(s)``, ``remove_border_labels``, and ``remove_masked_labels`` methods now keep the original dtype of the segmentation image instead of always changing it to ``int`` (``int64``).

Preserve Segmentation dtype

---

CHANGES.rst
docs/whats_new/2.0.rst
photutils/segmentation/deblend.py
photutils/segmentation/finder.py
photutils/utils/_optional_deps.py

This PR also uses `concurrent.futures.ProcessPoolExecutor` and gathers worker tasks as they are completed instead of sequentially.

Improve accuracy of progress bar for multiprocessing source deblending

---

docs/user_guide/segmentation.rst

Several fixes to the watershed function in scikit-image were made (https://github.com/scikit-image/scikit-image/pull/7071) for the upcoming 0.25 release.  These upstream fixes change the segmentation images produced from source deblending and are causing some tests to fail.  In this PR, I've pinned the doctests to require `skimage<=0.24'. After the 0.25 final release, I will update these tests.

Require skimage<=0.24 for deblend doctests

---

.github/workflows/ci_tests.yml
.github/workflows/publish.yml
.readthedocs.yaml
CHANGES.rst
docs/conf.py
docs/getting_started/install.rst
photutils/aperture/mask.py
photutils/aperture/tests/test_mask.py
photutils/psf/model_plotting.py
photutils/tests/helper.py
photutils/utils/_misc.py
pyproject.toml
tox.ini

Following [SPEC-0](https://scientific-python.org/specs/spec-0000/) and Astropy 7.0 release (https://github.com/astropy/astropy/pull/16903).

Drop support for Python 3.10

---

CHANGES.rst
photutils/background/core.py
photutils/background/tests/test_core.py

This PR fixes `SExtractorBackground` to ensure that dimensionality of the output array is preserved for single-value (array size = 1) output.  Previously, the dimensionality would be removed and a scalar float would be returned.

Fix SExtractorBackground output ndim

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

This PR fixes an issue in ``Background2D`` where if the ``box_size`` equals the input array shape the input data array could be modified.
Fixes #1933

Fix Background2D if box_size equals image shape

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/interpolators.py
photutils/background/tests/test_background_2d.py
photutils/background/tests/test_interpolators.py

This PR fixes a bug in ``Background2D`` where an error would be raised when using the ``BkgIDWInterpolator`` and when any mesh was excluded, e.g., due to an input mask.

Fix Background2D when using BkgIDWInterpolator

---

CHANGES.rst
photutils/extern/biweight.py
photutils/utils/_stats.py
photutils/utils/tests/test_stats.py

Due to an upstream bug in bottleneck with float32 arrays, bottleneck nan-functions are now used internally only for float64 arrays.  Using bottleneck with large float32 arrays gives incorrect results.  In this case, slower/correct is much better than faster/wrong.  Performance may be impacted for computations involving arrays with dtype other than float64. Affected functions are used in the aperture, background, detection, profiles, psf, and segmentation subpackages. This change has no impact if bottleneck is not installed.

Use bottleneck nanfunctions only for float64 arrays

---

photutils/psf/photometry.py

This PR fixes `make_model_image` and `make_residual_image` to not require keyword-only arguments. That was unintentionally added in v2.0.

Fix make_model_image and make_residual_image signatures

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/irafstarfinder.py
photutils/detection/peakfinder.py
photutils/detection/starfinder.py
photutils/detection/tests/test_irafstarfinder.py
photutils/detection/tests/test_peakfinder.py
photutils/detection/tests/test_starfinder.py

This PR fixes a bug in the star finders (``DAOStarFinder``, ``IRAFStarFinder``, and ``StarFinder``) when
``exclude_border=True``. It also fixes an issue reported by @lapeer in #1936 with``exclude_border=True`` where if all sources were in the border region then an error would be raised.
Fixes #1936.

Fix issues with exclude_border option in star finders

---

pyproject.toml

These ignored warnings no longer appear to be necessary.

Remove pytest filterwarnings

---

CHANGES.rst
photutils/psf/model_plotting.py

The ``'viridis'`` color map is now the default in the ``GriddedPSFModel`` ``plot_grid`` method when ``deltas=True``

Use viridis as default cmap for plot_grid

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

This PR fixes a bug where the table output from the ``SourceCatalog`` ``to_table`` method could have column names with a ``np.str_`` representation instead of ``str`` representation when using NumPy 2.0+.
Many thanks to @jensmelinder for reporting this in #1952.
Fixes #1952.

Prevent np.str_ column names in SourceCatalog table

---

CHANGES.rst
photutils/detection/core.py
photutils/detection/peakfinder.py
photutils/detection/tests/test_peakfinder.py

The ``find_peaks`` ``border_width`` keyword can now accept two  values, indicating the border width along the the y and x edges, respectively.
When ``exclude_border`` is set to ``True`` in the ``DAOStarFinder``  and ``StarFinder`` classes, the excluded border region can be different along the x and y edges if the kernel shape is rectangular.

Allow find_peaks border_width to be different along x and y

---

CHANGES.rst
docs/getting_started/install.rst
pyproject.toml
tox.ini

This PR updates the minimum required version of gwcs to 0.20 to avoid `pkg_resources` deprecation warnings.

Require gwcs 0.20+

---

CHANGES.rst
photutils/morphology/non_parametric.py
photutils/morphology/tests/test_non_parametric.py
photutils/segmentation/catalog.py

This PR adds an optional mask keyword to the `gini` function.
The `gini` function also now returns 0 instead of np.nan if the (unmasked) data values sum to zero.
The `SourceCatalog` `gini` property was also updated to use the `gini` function.

Add optional mask keyword to gini function

---

photutils/CITATION.rst

Update citation for v2.0.2

---

photutils/background/tests/test_background_2d.py

As reported in #1973, a few background tests were failing on equality due to float-point precision differences.
Closes #1973.

Use assert_allclose instead of assert_equal in background tests

---

README.rst

The previous installation link was outdated.

Fix outdated installation link

---

README.rst

...to match the narrative docs.

Update package description in readme

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_detect.py

This PR ensures that the `SegmentationImage` `labels` dtype matches that of the segmentation array.

Ensure labels dtype matches the segmentation data

---

CHANGES.rst
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py

Closes #1977
This PR modifies selection of sources by shapness, roundness, and peakmax to include the interval ends, i.e., that sources that have roundness 0.0 are selected instead of being rejected when `sharplo=0.0`.

Include interval ends for sharpless, roundness, and peakmax

---

photutils/detection/tests/test_daofinder.py
photutils/detection/tests/test_irafstarfinder.py

Cleanup dao- and iraf-starfinder tests. Remove unnecessary abs()

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/deblend.py
photutils/segmentation/detect.py
photutils/segmentation/tests/test_core.py
photutils/segmentation/tests/test_deblend.py

This PR adds  ``deblended_labels``, ``deblended_labels_map``, and ``deblended_labels_inverse_map`` properties to ``SegmentationImage`` to identify and map any deblended labels to the original parent segmentation image.
It also fixes a small bug in deblended labels if `relabel=False` (which is not the default).

Add map of deblended labels

---

photutils/isophote/tests/test_model.py
pyproject.toml

With the release of scipy 1.15, an isophote test started raising a warning about "RuntimeWarning: Mean of empty slice.", resulting in the test failing (see https://github.com/astropy/photutils/actions/runs/12601676522/job/35123249287).  The test fails only on windows.
The line causing this is
```
isophote\sample.py:299:
self.mean = np.mean(s[2])
```
This PR catches and filters the warning message.

Fix failing isophote test for scipy 1.15

---

CHANGES.rst
photutils/detection/daofinder.py
photutils/detection/irafstarfinder.py
photutils/detection/starfinder.py
photutils/detection/tests/test_starfinder.py

With this PR detected sources that match the maximum peak value (``peakmax``) are now included in the returned table of detected sources by ``StarFinder``. Followup to #1978.
This PR also updates the `DAOStarFinder` and `IRAFStarFinder` docstrings to reflect the changes in #1978.

Starfinder peakmax

---

CHANGES.rst
docs/whats_new/2.1.rst
photutils/datasets/images.py
photutils/datasets/tests/test_images.py

This PR adds a ``params_map`` keyword to ``make_model_image`` to allow a custom mapping between model parameter names and columns names in the parameter table.

Add params_map keyword to make_model_image

---

.github/workflows/ci_cron_daily.yml
.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_tests.yml

CC: @pllim 
The ARM64 test passed and it's very fast, so I moved it from the weekly CI to the regular CI tests.

Use the free ARM64 test runner

---

CHANGES.rst
docs/user_guide/profiles.rst
photutils/profiles/core.py
photutils/profiles/curve_of_growth.py
photutils/profiles/radial_profile.py
photutils/profiles/tests/test_radial_profile.py

This PR adds ``data_radius`` and ``data_profile`` attributes to the ``RadialProfile`` class for calculating the raw radial profile.
It also expands and improves the `profiles` narrative docs.

Add ability to calculate the raw radial profile of data points

---

.github/workflows/ci_tests.yml

rasterio does not have an ubuntu arm64 wheel and is now having trouble being built from source due to its GDAL dependency

Remove alldeps from ubuntu arm64 CI test

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR fixes an issue where the ``SegmentationImage`` ``polygons`` attribute would raise an error if any source segment contained a hole (i.e., multiply-connected polygon).

Fix SegmentationImage polygons for segments with holes

---

CHANGES.rst
photutils/aperture/attributes.py
photutils/aperture/core.py
photutils/aperture/ellipse.py
photutils/aperture/rectangle.py
photutils/aperture/stats.py
photutils/aperture/tests/test_converters.py
photutils/aperture/tests/test_ellipse.py
photutils/aperture/tests/test_photometry.py
photutils/aperture/tests/test_rectangle.py

The ``theta`` attribute of ``EllipticalAperture``, ``EllipticalAnnulus``, ``RectangularAperture``, and ``RectangularAnnulus`` is now always returned as an angular ``Quantity``.

Always return ellipse/rectangle pixel aperture theta as an angular Quantity

---

CHANGES.rst
photutils/aperture/converters.py
photutils/aperture/tests/test_converters.py

This PR adds an ``aperture_to_region`` function to convert an Aperture object to an astropy ``Region`` or ``Regions`` object.
``Region`` and ``Regions`` objects can be serialize to region files in various formats.

Add aperture_to_region function

---

CHANGES.rst
photutils/aperture/converters.py
photutils/aperture/tests/test_converters.py
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR adds a ``to_regions`` method to ``SegmentationImage`` that converts the segment outlines to a ``regions.Regions`` object.  The `Regions` object can saved to a file using its `write` method.

Add SegmentationImage to_regions method

---

CHANGES.rst
docs/user_guide/centroids.rst
photutils/centroids/gaussian.py

This PR fixed an issue with the initial Gaussian theta units in ``centroid_2dg``.  The Gaussian was given theta as a unitless value in degrees.  Without units, the Gaussian expects the value to be radians.  This PR updates the initialization to use the Quantity angle value.
Many thanks to @Lyalpha for reporting this issue in #2012.
Fixes #2012.

Fix initial Gaussian theta units for centroid_2dg

---

photutils/datasets/images.py
photutils/psf/epsf.py
photutils/psf/photometry.py
photutils/psf/simulation.py
photutils/segmentation/catalog.py
photutils/segmentation/deblend.py
photutils/segmentation/finder.py
photutils/utils/depths.py

I've tested that the `tqdm` progress bars now work in a Jupyter console with `tqdm.auto`.

Update progress_bar description in doc strings

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

With this PR ``PSFPhotometry`` and ``IterativePSFPhotometry`` now raise an error if the input ``error`` array contains non-finite or zero values.  Such values cause the fit weights to be non-finite, resulting in an error from the astropy fitter.

Raise error for non-finite errors in PSF fitting

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py
photutils/utils/cutouts.py

This PR adds an optional ``array`` keyword to the ``SourceCatalog`` ``make_cutouts`` method to allow making cutouts from other arrays than the input science array to `SourceCatalog`.

Add array keyword to SourceCatalog make_cutouts

---

docs/nitpick-exceptions.txt

The warnings from the inherited astropy model classes are no longer emitted.

Remove sphinx nitpick-exceptions

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_utils.py
photutils/psf/utils.py

The PR fixes a bug in ``fit_2dgaussian`` and ``fit_fwhm`` where the fit would fail if there were NaN values in the input data.
Many thanks to @mwcraig for reporting this in #2029!
Fixes #2029.

Fix bug in fit_2dgaussian and fit_fwhm when the input data contains NaN

---

docs/user_guide/psf.rst
photutils/psf/gridded_models.py
photutils/psf/image_models.py

This PR improves description of normalization for PSF image-based models, including the oversampling factor.
Thanks to @laldoroty for reporting this in #2031.
Closes #2031
Closes #859

Improve description of normalization for PSF image-based models

---

CHANGES.rst
photutils/psf/gridded_models.py
photutils/psf/tests/test_gridded_models.py

This PR fixes the check in ``GriddedPSFModel`` for rectangular pixel grids.

Fix GriddedPSFModel rectangular grid checks

---

CHANGES.rst
photutils/psf/gridded_models.py
photutils/psf/tests/test_gridded_models.py

With this PR, the `GriddedPSFModel``data` and `grid_xypos` attributes are now read-only.  These two attributes are closely coupled and making them read-only prevents them from becoming unsynced.  Instead, one can create a new `GriddedPSFModel`.

Make the GriddedPSFModel data and grid_xypos attributes read-only

---

CHANGES.rst
photutils/segmentation/catalog.py
photutils/segmentation/tests/test_catalog.py

When adding a new property to an existing `SourceCatalog` instance with `add_extra_property(..., overwrite=True`), it is not appended to the `_extra_properties` attribute, even if it doesn't already exist, due to: https://github.com/astropy/photutils/blob/0977e52be71ce0c30db8a575ae6ae46efa8f1ab4/photutils/segmentation/catalog.py#L662-L663
If one tries to then overwrite this new property, an unexpected error message occurs as this condition is triggered: https://github.com/astropy/photutils/blob/0977e52be71ce0c30db8a575ae6ae46efa8f1ab4/photutils/segmentation/catalog.py#L628-L630
This update will always append the new property to the `_extra_properties` attribute if it doesn't exist, regardless of `overwrite`, which would be the behaviour at least I was expecting. Apologies if I've misread …

Fix not appending to extra_properties when overwrite=True in SourceCatalog

---

CHANGES.rst
photutils/centroids/core.py
photutils/centroids/gaussian.py
photutils/centroids/tests/test_core.py
photutils/centroids/tests/test_gaussian.py

This PR fixes a corner-case issue where zero-sum arrays with ndim > 2 input to ``centroid_com`` would return only two np.nan coordinates instead of matching the dimensionality of the input array.

Fix centroid_com corner-case bug

---

.github/workflows/ci_tests.yml
pyproject.toml

Similarly to https://github.com/astropy/regions/pull/602, this disables limited API builds but keeps the wheel build jobs merged since those changes are fine and not breaking.
I've also added MacOS and Windows CI Python 3.13 builds.
Fixes: #2051

Partial revert of limited API builds

---

CHANGES.rst
photutils/aperture/converters.py
photutils/aperture/tests/test_converters.py
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR improves polygons, patches, and regions for SegmentationImages:
* Fixes issues when segment labels are non-contiguous
* Fixes issues when segments labels have holes
* The returned Shapely polygons may be Polygon or Multipolygon (non-contiguous)
* The `to_patches` and `plot_patches` methods now return `matplotlib.patches.PathPatch` objects
* Adds a `grouped` keyword to the `to_regions` method
* The returned region PolygonPixelRegion objects meta dictionary now contains the source label

Improve polygons for segmentation images

---

CHANGES.rst
photutils/background/background_2d.py
photutils/background/tests/test_background_2d.py

With this PR, an explicit ``ValueError`` is now raised in the input ``data`` to ``Background2D`` contains all non-finite values.

Raise ValueError if Background2D input is all non-finite values

---

docs/user_guide/psf.rst

The WebbPSF package has been renamed STPSF:
https://github.com/spacetelescope/stpsf
https://stpsf.readthedocs.io/en/latest/

Update WebbPSF package reference to STPSF

---

CHANGES.rst
photutils/segmentation/core.py
photutils/segmentation/tests/test_core.py

This PR fixes a bug where patches would not be returned for labels with "invalid" shapely polygons.  This happens when segments have pixels that intersect only at a corner (ring self-intersection).
This PR also renames the `grouped` keyword to `group` in the `to_regions` method (this affects dev only).

Fix segmentation patches in case of "invalid" shapely polygons

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR fixes a bug in ``PSFPhotometry`` where the ``'group_id'`` would be ignored if included in the ``init_params`` table.

Fix user-defined group_id in PSFPhotometry init_params

---

photutils/background/background_2d.py
photutils/background/core.py
photutils/background/local_background.py
photutils/psf/epsf.py
photutils/psf/iterative.py
photutils/psf/photometry.py
photutils/segmentation/detect.py
photutils/utils/_parameters.py
photutils/utils/depths.py
pyproject.toml

These default keyword class instances are mutable in principle.  While the risk of changing these is minor, this PR ensures that each function/class gets its own instance.

Remove mutable default arguments

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR fixes a bug in ``PSFPhotometry`` and ``IterativePSFPhotometry`` where an error would be raised if the x or y columns in the ``init_params`` table had units.

Fix x/y units of PSF photometry init_params table

---

CHANGES.rst
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR fixes an edge-case bug in ``PSFPhotometry`` and ``IterativePSFPhotometry`` for the boundary conditions where flag=2 would be set.

Fix boundary conditions for PSF photometry flag=2

---

CHANGES.rst
photutils/psf/iterative.py
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR adds a ``group_warning_threshold`` keyword to ``PSFPhotometry`` and ``IterativePSFPhotometry``.
Requested by @keflavich in https://github.com/astropy/photutils/pull/1856#issuecomment-3002013995.

Add keyword to customize the group warning threshold

---

CHANGES.rst
photutils/psf/_components.py
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

This PR fixes an issue where the fit metrics and flags would be in the wrong order when init_params IDs were not consecutive.
Followup to #2084.

Fit PSFPhotometry order for metrics and flags 

---

CHANGES.rst
photutils/psf/_components.py
photutils/psf/iterative.py
photutils/psf/photometry.py
photutils/psf/tests/test_photometry.py

With this PR, ``PSFPhotometry`` and ``IterativePSFPhotometry`` now return a reduced chi-squared statistic.  It is found in the `reduced_chi2`` column in the results table.

Add reduced chi-squared statistic to PSF photometry

---

CHANGES.rst
photutils/psf/__init__.py
photutils/psf/flags.py
photutils/psf/tests/test_flags.py

This PR adds a ``decode_psf_flags`` utility function for decoding PSF photometry bit flags.

Add utility function to decode PSF photometry flags

---

CHANGES.rst
docs/whats_new/2.3.rst
photutils/psf/_components.py
photutils/psf/photometry.py
photutils/psf/tests/test_components.py
photutils/psf/tests/test_photometry.py

With this PR, the PSF photometry classes now use a dynamically generated "flat" model instead of a compound model for grouped sources. This eliminates recursion limits and significantly reduces memory usage for large groups.
Fixes: #1808

PSF photometry: Replace compound model with flat model for grouped sources
